sqlrelay:prepareQuery("begin exampleproc(:in1,:in2,:in3,:out1,:out2,:out3); end;"),
sqlrelay:inputBindLong("in1", 1),
sqlrelay:inputBindDouble("in2", 1.1, 2, 1),
sqlrelay:inputBindString("in3", "hello"),
sqlrelay:defineOutputBindInteger("out1"),
sqlrelay:defineOutputBindDouble("out2"),
sqlrelay:defineOutputBindString("out3", 20),
sqlrelay:executeQuery(),
Out1 = sqlrelay:getOutputBindInteger("out1"),
Out2 = sqlrelay:getOutputBindDouble("out2"),
Out3 = sqlrelay:getOutputBindString("out3"),
