sqlrelay:prepareQuery("call exampleproc(?,?,?,?)"),
sqlrelay:inputBindLong("1", 1),
sqlrelay:inputBindDouble("2", 1.1, 2, 1),
sqlrelay:inputBindString("3", "hello"),
sqlrelay:defineOutputBindInteger("4"),
sqlrelay:executeQuery(),
Result = sqlrelay:getOutputBindInteger("4"),
