// Copyright (c) David Muse
// See the file COPYING for more information.

#include <sqlrelay/sqlrclient.h>
#include <rudiments/charstring.h>
#include <rudiments/process.h>
#include <rudiments/stdio.h>

#include "assert.cpp"

sqlrconnection	*con;
sqlrcursor	*cur;
sqlrconnection	*secondcon;
sqlrcursor	*secondcur;

int main(int argc, char **argv) {

	const char	*subvars[4]={"var1","var2","var3",NULL};
	const char	*subvalstrings[3]={"hi","hello","bye"};
	int64_t		subvallongs[3]={1,2,3};
	double		subvaldoubles[3]={10.55,10.556,10.5556};
	uint32_t	precs[3]={4,5,6};
	uint32_t	scales[3]={2,3,4};
	const char * const *cols;
	const char * const *fields;
	uint16_t	port;
	char		*socket;
	uint16_t	id;
	char		*filename;
	uint32_t	*fieldlens;

	// instantiation
	con=new sqlrconnection("sqlrelay",9000,"/tmp/test.socket",
						"testuser","testpassword",0,1);
	cur=new sqlrcursor(con);


	// get database type
	stdoutput.printf("IDENTIFY: \n");
	assertEquals(con->identify(),"sap");
	stdoutput.printf("\n");

	// ping
	stdoutput.printf("PING: \n");
	assertTrue(con->ping());
	stdoutput.printf("\n");

	// bind format
	stdoutput.printf("BIND FORMAT: \n");
	assertEquals(con->bindFormat(),"@*");
	stdoutput.printf("\n");

	// nextval format
	stdoutput.printf("NEXTVAL FORMAT: \n");
	assertEquals(con->nextvalFormat(),"%s.nextval");
	stdoutput.printf("\n");

	// drop existing table
	cur->sendQuery("drop table testtable");

	stdoutput.printf("CREATE TEMPTABLE: \n");
	assertTrue(cur->sendQuery("create table testtable (testint int, testsmallint smallint, testtinyint tinyint, testreal real, testfloat float, testdecimal decimal(4,1), testnumeric numeric(4,1), testmoney money, testsmallmoney smallmoney, testdatetime datetime, testsmalldatetime smalldatetime, testchar char(40), testvarchar varchar(40), testbit bit, testtext text)"));
	stdoutput.printf("\n");

	stdoutput.printf("CREATE STORED PROCEDURES: \n");
	cur->sendQuery("drop procedure testproc");
	assertTrue(cur->sendQuery("create procedure testproc @in1 int, @in2 float, @in3 varchar(20), @out1 int output, @out2 float output, @out3 varchar(20) output as select @out1=@in1, @out2=@in2, @out3=@in3"));
	cur->sendQuery("drop procedure testselectproc");
	assertTrue(cur->sendQuery("create procedure testselectproc as select * from testtable order by testint"));
	stdoutput.printf("\n");

	stdoutput.printf("BEGIN TRANSACTION: \n");
	assertTrue(cur->sendQuery("begin tran"));
	stdoutput.printf("\n");

	stdoutput.printf("INSERT: \n");
	assertTrue(cur->sendQuery("insert into testtable values (1,1,1,1.1,1.1,1.1,1.1,1.00,1.00,'01-Jan-2001 01:00:00','01-Jan-2001 01:00:00','testchar1','testvarchar1',1,'testtext1')"));
	stdoutput.printf("\n");

	stdoutput.printf("AFFECTED ROWS: \n");
	assertEquals(cur->affectedRows(),1);
	stdoutput.printf("\n");

	stdoutput.printf("BIND BY POSITION: \n");
	cur->prepareQuery("insert into testtable values (@var1,@var2,@var3,@var4,@var5,@var6,@var7,@var8,@var9,@var10,@var11,@var12,@var13,@var14,@var15)");
	assertEquals(cur->countBindVariables(),15);
	cur->inputBind("1",2);
	cur->inputBind("2",2);
	cur->inputBind("3",2);
	cur->inputBind("4",2.2,2,1);
	cur->inputBind("5",2.2,2,1);
	cur->inputBind("6",2.2,2,1);
	cur->inputBind("7",2.2,2,1);
	cur->inputBind("8",2.00,3,2);
	cur->inputBind("9",2.00,3,2);
	cur->inputBind("10","01-Jan-2002 02:00:00");
	cur->inputBind("11","01-Jan-2002 02:00:00");
	cur->inputBind("12","testchar2");
	cur->inputBind("13","testvarchar2");
	cur->inputBind("14",1);
	cur->inputBindClob("15","testtext2",9);
	assertTrue(cur->executeQuery());
	cur->clearBinds();
	cur->inputBind("1",3);
	cur->inputBind("2",3);
	cur->inputBind("3",3);
	cur->inputBind("4",3.3,2,1);
	cur->inputBind("5",3.3,2,1);
	cur->inputBind("6",3.3,2,1);
	cur->inputBind("7",3.3,2,1);
	cur->inputBind("8",3.00,3,2);
	cur->inputBind("9",3.00,3,2);
	cur->inputBind("10","01-Jan-2003 03:00:00");
	cur->inputBind("11","01-Jan-2003 03:00:00");
	cur->inputBind("12","testchar3");
	cur->inputBind("13","testvarchar3");
	cur->inputBind("14",1);
	cur->inputBindClob("15","testtext3",9);
	assertTrue(cur->executeQuery());
	cur->clearBinds();
	cur->inputBind("1",4);
	cur->inputBind("2",4);
	cur->inputBind("3",4);
	cur->inputBind("4",4.4,2,1);
	cur->inputBind("5",4.4,2,1);
	cur->inputBind("6",4.4,2,1);
	cur->inputBind("7",4.4,2,1);
	cur->inputBind("8",4.00,3,2);
	cur->inputBind("9",4.00,3,2);
	cur->inputBind("10","01-Jan-2004 04:00:00");
	cur->inputBind("11","01-Jan-2004 04:00:00");
	cur->inputBind("12","testchar4");
	cur->inputBind("13","testvarchar4");
	cur->inputBind("14",1);
	cur->inputBindClob("15","testtext4",9);
	assertTrue(cur->executeQuery());
	stdoutput.printf("\n");

	stdoutput.printf("BIND BY NAME: \n");
	cur->clearBinds();
	cur->inputBind("var1",5);
	cur->inputBind("var2",5);
	cur->inputBind("var3",5);
	cur->inputBind("var4",5.5,2,1);
	cur->inputBind("var5",5.5,2,1);
	cur->inputBind("var6",5.5,2,1);
	cur->inputBind("var7",5.5,2,1);
	cur->inputBind("var8",5.00,3,2);
	cur->inputBind("var9",5.00,3,2);
	cur->inputBind("var10","01-Jan-2005 05:00:00");
	cur->inputBind("var11","01-Jan-2005 05:00:00");
	cur->inputBind("var12","testchar5");
	cur->inputBind("var13","testvarchar5");
	cur->inputBind("var14",1);
	cur->inputBindClob("var15","testtext5",9);
	assertTrue(cur->executeQuery());
	cur->clearBinds();
	cur->inputBind("var1",6);
	cur->inputBind("var2",6);
	cur->inputBind("var3",6);
	cur->inputBind("var4",6.6,2,1);
	cur->inputBind("var5",6.6,2,1);
	cur->inputBind("var6",6.6,2,1);
	cur->inputBind("var7",6.6,2,1);
	cur->inputBind("var8",6.00,3,2);
	cur->inputBind("var9",6.00,3,2);
	cur->inputBind("var10","01-Jan-2006 06:00:00");
	cur->inputBind("var11","01-Jan-2006 06:00:00");
	cur->inputBind("var12","testchar6");
	cur->inputBind("var13","testvarchar6");
	cur->inputBind("var14",1);
	cur->inputBindClob("var15","testtext6",9);
	assertTrue(cur->executeQuery());
	cur->clearBinds();
	cur->inputBind("var1",7);
	cur->inputBind("var2",7);
	cur->inputBind("var3",7);
	cur->inputBind("var4",7.7,2,1);
	cur->inputBind("var5",7.7,2,1);
	cur->inputBind("var6",7.7,2,1);
	cur->inputBind("var7",7.7,2,1);
	cur->inputBind("var8",7.00,3,2);
	cur->inputBind("var9",7.00,3,2);
	cur->inputBind("var10","01-Jan-2007 07:00:00");
	cur->inputBind("var11","01-Jan-2007 07:00:00");
	cur->inputBind("var12","testchar7");
	cur->inputBind("var13","testvarchar7");
	cur->inputBind("var14",1);
	cur->inputBindClob("var15","testtext7",9);
	assertTrue(cur->executeQuery());
	stdoutput.printf("\n");

	stdoutput.printf("BIND BY NAME WITH VALIDATION: \n");
	cur->clearBinds();
	cur->inputBind("var1",8);
	cur->inputBind("var2",8);
	cur->inputBind("var3",8);
	cur->inputBind("var4",8.8,2,1);
	cur->inputBind("var5",8.8,2,1);
	cur->inputBind("var6",8.8,2,1);
	cur->inputBind("var7",8.8,2,1);
	cur->inputBind("var8",8.00,3,2);
	cur->inputBind("var9",8.00,3,2);
	cur->inputBind("var10","01-Jan-2008 08:00:00");
	cur->inputBind("var11","01-Jan-2008 08:00:00");
	cur->inputBind("var12","testchar8");
	cur->inputBind("var13","testvarchar8");
	cur->inputBind("var14",1);
	cur->inputBindClob("var15","testtext8",9);
	cur->inputBind("var16","junkvalue");
	cur->validateBinds();
	assertTrue(cur->executeQuery());
	stdoutput.printf("\n");

	stdoutput.printf("STORED PROCEDURE: \n");
	// return multiple values
	cur->prepareQuery("exec testproc");
	cur->inputBind("in1",1);
	cur->inputBind("in2",1.1,2,1);
	cur->inputBind("in3","hello");
	cur->defineOutputBindInteger("out1");
	cur->defineOutputBindDouble("out2");
	cur->defineOutputBindString("out3",20);
	assertTrue(cur->executeQuery());
	assertEquals(cur->getOutputBindInteger("out1"),1);
	assertEquals(cur->getOutputBindDouble("out2"),1.1);
	assertEquals(cur->getOutputBindString("out3"),"hello");
	stdoutput.printf("\n");

	stdoutput.printf("SELECT: \n");
	assertTrue(cur->sendQuery("select * from testtable order by testint"));
	stdoutput.printf("\n");

	stdoutput.printf("COLUMN COUNT: \n");
	assertEquals(cur->colCount(),15);
	stdoutput.printf("\n");

	stdoutput.printf("COLUMN NAMES: \n");
	assertEquals(cur->getColumnName(0),"testint");
	assertEquals(cur->getColumnName(1),"testsmallint");
	assertEquals(cur->getColumnName(2),"testtinyint");
	assertEquals(cur->getColumnName(3),"testreal");
	assertEquals(cur->getColumnName(4),"testfloat");
	assertEquals(cur->getColumnName(5),"testdecimal");
	assertEquals(cur->getColumnName(6),"testnumeric");
	assertEquals(cur->getColumnName(7),"testmoney");
	assertEquals(cur->getColumnName(8),"testsmallmoney");
	assertEquals(cur->getColumnName(9),"testdatetime");
	assertEquals(cur->getColumnName(10),"testsmalldatetime");
	assertEquals(cur->getColumnName(11),"testchar");
	assertEquals(cur->getColumnName(12),"testvarchar");
	assertEquals(cur->getColumnName(13),"testbit");
	cols=cur->getColumnNames();
	assertEquals(cols[0],"testint");
	assertEquals(cols[1],"testsmallint");
	assertEquals(cols[2],"testtinyint");
	assertEquals(cols[3],"testreal");
	assertEquals(cols[4],"testfloat");
	assertEquals(cols[5],"testdecimal");
	assertEquals(cols[6],"testnumeric");
	assertEquals(cols[7],"testmoney");
	assertEquals(cols[8],"testsmallmoney");
	assertEquals(cols[9],"testdatetime");
	assertEquals(cols[10],"testsmalldatetime");
	assertEquals(cols[11],"testchar");
	assertEquals(cols[12],"testvarchar");
	assertEquals(cols[13],"testbit");
	stdoutput.printf("\n");

	stdoutput.printf("COLUMN TYPES: \n");
	assertEquals(cur->getColumnType((uint32_t)0),"INT");
	assertEquals(cur->getColumnType("testint"),"INT");
	assertEquals(cur->getColumnType(1),"SMALLINT");
	assertEquals(cur->getColumnType("testsmallint"),"SMALLINT");
	assertEquals(cur->getColumnType(2),"TINYINT");
	assertEquals(cur->getColumnType("testtinyint"),"TINYINT");
	assertEquals(cur->getColumnType(3),"REAL");
	assertEquals(cur->getColumnType("testreal"),"REAL");
	assertEquals(cur->getColumnType(4),"FLOAT");
	assertEquals(cur->getColumnType("testfloat"),"FLOAT");
	assertEquals(cur->getColumnType(5),"DECIMAL");
	assertEquals(cur->getColumnType("testdecimal"),"DECIMAL");
	assertEquals(cur->getColumnType(6),"NUMERIC");
	assertEquals(cur->getColumnType("testnumeric"),"NUMERIC");
	assertEquals(cur->getColumnType(7),"MONEY");
	assertEquals(cur->getColumnType("testmoney"),"MONEY");
	assertEquals(cur->getColumnType(8),"SMALLMONEY");
	assertEquals(cur->getColumnType("testsmallmoney"),"SMALLMONEY");
	assertEquals(cur->getColumnType(9),"DATETIME");
	assertEquals(cur->getColumnType("testdatetime"),"DATETIME");
	assertEquals(cur->getColumnType(10),"SMALLDATETIME");
	assertEquals(cur->getColumnType("testsmalldatetime"),"SMALLDATETIME");
	assertEquals(cur->getColumnType(11),"CHAR");
	assertEquals(cur->getColumnType("testchar"),"CHAR");
	assertEquals(cur->getColumnType(12),"CHAR");
	assertEquals(cur->getColumnType("testvarchar"),"CHAR");
	assertEquals(cur->getColumnType(13),"BIT");
	assertEquals(cur->getColumnType("testbit"),"BIT");
	stdoutput.printf("\n");

	stdoutput.printf("COLUMN LENGTH: \n");
	assertEquals(cur->getColumnLength((uint32_t)0),4);
	assertEquals(cur->getColumnLength("testint"),4);
	assertEquals(cur->getColumnLength(1),2);
	assertEquals(cur->getColumnLength("testsmallint"),2);
	assertEquals(cur->getColumnLength(2),1);
	assertEquals(cur->getColumnLength("testtinyint"),1);
	assertEquals(cur->getColumnLength(3),4);
	assertEquals(cur->getColumnLength("testreal"),4);
	assertEquals(cur->getColumnLength(4),8);
	assertEquals(cur->getColumnLength("testfloat"),8);
	assertEquals(cur->getColumnLength(5),35);
	assertEquals(cur->getColumnLength("testdecimal"),35);
	assertEquals(cur->getColumnLength(6),35);
	assertEquals(cur->getColumnLength("testnumeric"),35);
	assertEquals(cur->getColumnLength(7),8);
	assertEquals(cur->getColumnLength("testmoney"),8);
	assertEquals(cur->getColumnLength(8),4);
	assertEquals(cur->getColumnLength("testsmallmoney"),4);
	assertEquals(cur->getColumnLength(9),8);
	assertEquals(cur->getColumnLength("testdatetime"),8);
	assertEquals(cur->getColumnLength(10),4);
	assertEquals(cur->getColumnLength("testsmalldatetime"),4);
	assertEquals(cur->getColumnLength(11),40);
	assertEquals(cur->getColumnLength("testchar"),40);
	assertEquals(cur->getColumnLength(12),40);
	assertEquals(cur->getColumnLength("testvarchar"),40);
	assertEquals(cur->getColumnLength(13),1);
	assertEquals(cur->getColumnLength("testbit"),1);
	stdoutput.printf("\n");

	stdoutput.printf("LONGEST COLUMN: \n");
	assertEquals(cur->getLongest((uint32_t)0),1);
	assertEquals(cur->getLongest("testint"),1);
	assertEquals(cur->getLongest(1),1);
	assertEquals(cur->getLongest("testsmallint"),1);
	assertEquals(cur->getLongest(2),1);
	assertEquals(cur->getLongest("testtinyint"),1);
	assertEquals(cur->getLongest(3),18);
	assertEquals(cur->getLongest("testreal"),18);
	assertEquals(cur->getLongest(4),18);
	assertEquals(cur->getLongest("testfloat"),18);
	assertEquals(cur->getLongest(5),3);
	assertEquals(cur->getLongest("testdecimal"),3);
	assertEquals(cur->getLongest(6),3);
	assertEquals(cur->getLongest("testnumeric"),3);
	assertEquals(cur->getLongest(7),4);
	assertEquals(cur->getLongest("testmoney"),4);
	assertEquals(cur->getLongest(8),4);
	assertEquals(cur->getLongest("testsmallmoney"),4);
	assertEquals(cur->getLongest(9),19);
	assertEquals(cur->getLongest("testdatetime"),19);
	assertEquals(cur->getLongest(10),19);
	assertEquals(cur->getLongest("testsmalldatetime"),19);
	assertEquals(cur->getLongest(11),40);
	assertEquals(cur->getLongest("testchar"),40);
	assertEquals(cur->getLongest(12),12);
	assertEquals(cur->getLongest("testvarchar"),12);
	assertEquals(cur->getLongest(13),1);
	assertEquals(cur->getLongest("testbit"),1);
	stdoutput.printf("\n");

	stdoutput.printf("ROW COUNT: \n");
	assertEquals(cur->rowCount(),8);
	stdoutput.printf("\n");

	stdoutput.printf("TOTAL ROWS: \n");
	assertEquals(cur->totalRows(),0);
	stdoutput.printf("\n");

	stdoutput.printf("FIRST ROW INDEX: \n");
	assertEquals(cur->firstRowIndex(),0);
	stdoutput.printf("\n");

	stdoutput.printf("END OF RESULT SET: \n");
	assertTrue(cur->endOfResultSet());
	stdoutput.printf("\n");

	stdoutput.printf("FIELDS BY INDEX: \n");
	assertEquals(cur->getField(0,(uint32_t)0),"1");
	assertEquals(cur->getField(0,1),"1");
	assertEquals(cur->getField(0,2),"1");
	//assertEquals(cur->getField(0,3),"1.1");
	//assertEquals(cur->getField(0,4),"1.1");
	assertEquals(cur->getField(0,5),"1.1");
	assertEquals(cur->getField(0,6),"1.1");
	assertEquals(cur->getField(0,7),"1.00");
	assertEquals(cur->getField(0,8),"1.00");
	assertEquals(cur->getField(0,9),"Jan  1 2001  1:00AM");
	assertEquals(cur->getField(0,10),"Jan  1 2001  1:00AM");
	assertEquals(cur->getField(0,11),"testchar1                               ");
	assertEquals(cur->getField(0,12),"testvarchar1");
	assertEquals(cur->getField(0,13),"1");
	stdoutput.printf("\n");
	assertEquals(cur->getField(7,(uint32_t)0),"8");
	assertEquals(cur->getField(7,1),"8");
	assertEquals(cur->getField(7,2),"8");
	//assertEquals(cur->getField(7,3),"8.8");
	//assertEquals(cur->getField(7,4),"8.8");
	assertEquals(cur->getField(7,5),"8.8");
	assertEquals(cur->getField(7,6),"8.8");
	assertEquals(cur->getField(7,7),"8.00");
	assertEquals(cur->getField(7,8),"8.00");
	assertEquals(cur->getField(7,9),"Jan  1 2008  8:00AM");
	assertEquals(cur->getField(7,10),"Jan  1 2008  8:00AM");
	assertEquals(cur->getField(7,11),"testchar8                               ");
	assertEquals(cur->getField(7,12),"testvarchar8");
	assertEquals(cur->getField(7,13),"1");
	stdoutput.printf("\n");

	stdoutput.printf("FIELD LENGTHS BY INDEX: \n");
	assertEquals(cur->getFieldLength(0,(uint32_t)0),1);
	assertEquals(cur->getFieldLength(0,1),1);
	assertEquals(cur->getFieldLength(0,2),1);
	assertEquals(cur->getFieldLength(0,3),18);
	assertEquals(cur->getFieldLength(0,4),18);
	assertEquals(cur->getFieldLength(0,5),3);
	assertEquals(cur->getFieldLength(0,6),3);
	assertEquals(cur->getFieldLength(0,7),4);
	assertEquals(cur->getFieldLength(0,8),4);
	assertEquals(cur->getFieldLength(0,9),19);
	assertEquals(cur->getFieldLength(0,10),19);
	assertEquals(cur->getFieldLength(0,11),40);
	assertEquals(cur->getFieldLength(0,12),12);
	assertEquals(cur->getFieldLength(0,13),1);
	stdoutput.printf("\n");
	assertEquals(cur->getFieldLength(7,(uint32_t)0),1);
	assertEquals(cur->getFieldLength(7,1),1);
	assertEquals(cur->getFieldLength(7,2),1);
	assertEquals(cur->getFieldLength(7,3),18);
	assertEquals(cur->getFieldLength(7,4),18);
	assertEquals(cur->getFieldLength(7,5),3);
	assertEquals(cur->getFieldLength(7,6),3);
	assertEquals(cur->getFieldLength(7,7),4);
	assertEquals(cur->getFieldLength(7,8),4);
	assertEquals(cur->getFieldLength(7,9),19);
	assertEquals(cur->getFieldLength(7,10),19);
	assertEquals(cur->getFieldLength(7,11),40);
	assertEquals(cur->getFieldLength(7,12),12);
	assertEquals(cur->getFieldLength(7,13),1);
	stdoutput.printf("\n");

	stdoutput.printf("FIELDS BY NAME: \n");
	assertEquals(cur->getField(0,"testint"),"1");
	assertEquals(cur->getField(0,"testsmallint"),"1");
	assertEquals(cur->getField(0,"testtinyint"),"1");
	//assertEquals(cur->getField(0,"testreal"),"1.1");
	//assertEquals(cur->getField(0,"testfloat"),"1.1");
	assertEquals(cur->getField(0,"testdecimal"),"1.1");
	assertEquals(cur->getField(0,"testnumeric"),"1.1");
	assertEquals(cur->getField(0,"testmoney"),"1.00");
	assertEquals(cur->getField(0,"testsmallmoney"),"1.00");
	assertEquals(cur->getField(0,"testdatetime"),"Jan  1 2001  1:00AM");
	assertEquals(cur->getField(0,"testsmalldatetime"),"Jan  1 2001  1:00AM");
	assertEquals(cur->getField(0,"testchar"),"testchar1                               ");
	assertEquals(cur->getField(0,"testvarchar"),"testvarchar1");
	assertEquals(cur->getField(0,"testbit"),"1");
	stdoutput.printf("\n");
	assertEquals(cur->getField(7,"testint"),"8");
	assertEquals(cur->getField(7,"testsmallint"),"8");
	assertEquals(cur->getField(7,"testtinyint"),"8");
	//assertEquals(cur->getField(7,"testreal"),"8.8");
	//assertEquals(cur->getField(7,"testfloat"),"8.8");
	assertEquals(cur->getField(7,"testdecimal"),"8.8");
	assertEquals(cur->getField(7,"testnumeric"),"8.8");
	assertEquals(cur->getField(7,"testmoney"),"8.00");
	assertEquals(cur->getField(7,"testsmallmoney"),"8.00");
	assertEquals(cur->getField(7,"testdatetime"),"Jan  1 2008  8:00AM");
	assertEquals(cur->getField(7,"testsmalldatetime"),"Jan  1 2008  8:00AM");
	assertEquals(cur->getField(7,"testchar"),"testchar8                               ");
	assertEquals(cur->getField(7,"testvarchar"),"testvarchar8");
	assertEquals(cur->getField(7,"testbit"),"1");
	stdoutput.printf("\n");

	stdoutput.printf("FIELD LENGTHS BY NAME: \n");
	assertEquals(cur->getFieldLength(0,"testint"),1);
	assertEquals(cur->getFieldLength(0,"testsmallint"),1);
	assertEquals(cur->getFieldLength(0,"testtinyint"),1);
	//assertEquals(cur->getFieldLength(0,"testreal"),3);
	//assertEquals(cur->getFieldLength(0,"testfloat"),3);
	assertEquals(cur->getFieldLength(0,"testdecimal"),3);
	assertEquals(cur->getFieldLength(0,"testnumeric"),3);
	assertEquals(cur->getFieldLength(0,"testmoney"),4);
	assertEquals(cur->getFieldLength(0,"testsmallmoney"),4);
	assertEquals(cur->getFieldLength(0,"testdatetime"),19);
	assertEquals(cur->getFieldLength(0,"testsmalldatetime"),19);
	assertEquals(cur->getFieldLength(0,"testchar"),40);
	assertEquals(cur->getFieldLength(0,"testvarchar"),12);
	assertEquals(cur->getFieldLength(0,"testbit"),1);
	stdoutput.printf("\n");
	assertEquals(cur->getFieldLength(7,"testint"),1);
	assertEquals(cur->getFieldLength(7,"testsmallint"),1);
	assertEquals(cur->getFieldLength(7,"testtinyint"),1);
	//assertEquals(cur->getFieldLength(7,"testreal"),3);
	//assertEquals(cur->getFieldLength(7,"testfloat"),3);
	assertEquals(cur->getFieldLength(7,"testdecimal"),3);
	assertEquals(cur->getFieldLength(7,"testnumeric"),3);
	assertEquals(cur->getFieldLength(7,"testmoney"),4);
	assertEquals(cur->getFieldLength(7,"testsmallmoney"),4);
	assertEquals(cur->getFieldLength(7,"testdatetime"),19);
	assertEquals(cur->getFieldLength(7,"testsmalldatetime"),19);
	assertEquals(cur->getFieldLength(7,"testchar"),40);
	assertEquals(cur->getFieldLength(7,"testvarchar"),12);
	assertEquals(cur->getFieldLength(7,"testbit"),1);
	stdoutput.printf("\n");

	stdoutput.printf("FIELDS BY ARRAY: \n");
	fields=cur->getRow(0);
	assertEquals(fields[0],"1");
	assertEquals(fields[1],"1");
	assertEquals(fields[2],"1");
	//assertEquals(fields[3],"1.1");
	//assertEquals(fields[4],"1.1");
	assertEquals(fields[5],"1.1");
	assertEquals(fields[6],"1.1");
	assertEquals(fields[7],"1.00");
	assertEquals(fields[8],"1.00");
	assertEquals(fields[9],"Jan  1 2001  1:00AM");
	assertEquals(fields[10],"Jan  1 2001  1:00AM");
	assertEquals(fields[11],"testchar1                               ");
	assertEquals(fields[12],"testvarchar1");
	assertEquals(fields[13],"1");
	stdoutput.printf("\n");

	stdoutput.printf("FIELD LENGTHS BY ARRAY: \n");
	fieldlens=cur->getRowLengths(0);
	assertEquals(fieldlens[0],1);
	assertEquals(fieldlens[1],1);
	assertEquals(fieldlens[2],1);
	//assertEquals(fieldlens[3],3);
	//assertEquals(fieldlens[4],3);
	assertEquals(fieldlens[5],3);
	assertEquals(fieldlens[6],3);
	assertEquals(fieldlens[7],4);
	assertEquals(fieldlens[8],4);
	assertEquals(fieldlens[9],19);
	assertEquals(fieldlens[10],19);
	assertEquals(fieldlens[11],40);
	assertEquals(fieldlens[12],12);
	assertEquals(fieldlens[13],1);
	stdoutput.printf("\n");

	stdoutput.printf("INDIVIDUAL SUBSTITUTIONS: \n");
	cur->prepareQuery("select $(var1),'$(var2)',$(var3)");
	cur->substitution("var1",1);
	cur->substitution("var2","hello");
	cur->substitution("var3",10.5556,6,4);
	assertTrue(cur->executeQuery());
	stdoutput.printf("\n");

	stdoutput.printf("FIELDS: \n");
	assertEquals(cur->getField(0,(uint32_t)0),"1");
	assertEquals(cur->getField(0,1),"hello");
	assertEquals(cur->getField(0,2),"10.5556");
	stdoutput.printf("\n");

	stdoutput.printf("ARRAY SUBSTITUTIONS: \n");
	cur->prepareQuery("select $(var1),$(var2),$(var3)");
	cur->substitutions(subvars,subvallongs);
	assertTrue(cur->executeQuery());
	stdoutput.printf("\n");
	
	stdoutput.printf("FIELDS: \n");
	assertEquals(cur->getField(0,(uint32_t)0),"1");
	assertEquals(cur->getField(0,1),"2");
	assertEquals(cur->getField(0,2),"3");
	stdoutput.printf("\n");
	
	stdoutput.printf("ARRAY SUBSTITUTIONS: \n");
	cur->prepareQuery("select '$(var1)','$(var2)','$(var3)'");
	cur->substitutions(subvars,subvalstrings);
	assertTrue(cur->executeQuery());
	stdoutput.printf("\n");

	stdoutput.printf("FIELDS: \n");
	assertEquals(cur->getField(0,(uint32_t)0),"hi");
	assertEquals(cur->getField(0,1),"hello");
	assertEquals(cur->getField(0,2),"bye");
	stdoutput.printf("\n");

	stdoutput.printf("ARRAY SUBSTITUTIONS: \n");
	cur->prepareQuery("select $(var1),$(var2),$(var3)");
	cur->substitutions(subvars,subvaldoubles,precs,scales);
	assertTrue(cur->executeQuery());
	stdoutput.printf("\n");

	stdoutput.printf("FIELDS: \n");
	assertEquals(cur->getField(0,(uint32_t)0),"10.55");
	assertEquals(cur->getField(0,1),"10.556");
	assertEquals(cur->getField(0,2),"10.5556");
	stdoutput.printf("\n");

	stdoutput.printf("NULLS as Nulls: \n");
	cur->getNullsAsNulls();
	assertTrue(cur->sendQuery("select NULL,1,NULL"));
	assertEquals(cur->getField(0,(uint32_t)0),NULL);
	assertEquals(cur->getField(0,1),"1");
	assertEquals(cur->getField(0,2),NULL);
	cur->getNullsAsEmptyStrings();
	assertTrue(cur->sendQuery("select NULL,1,NULL"));
	assertEquals(cur->getField(0,(uint32_t)0),"");
	assertEquals(cur->getField(0,1),"1");
	assertEquals(cur->getField(0,2),"");
	cur->getNullsAsNulls();
	stdoutput.printf("\n");

	stdoutput.printf("RESULT SET BUFFER SIZE: \n");
	assertEquals(cur->getResultSetBufferSize(),0);
	cur->setResultSetBufferSize(2);
	assertTrue(cur->sendQuery("select * from testtable order by testint"));
	assertEquals(cur->getResultSetBufferSize(),2);
	stdoutput.printf("\n");
	assertEquals(cur->firstRowIndex(),0);
	assertFalse(cur->endOfResultSet());
	assertEquals(cur->rowCount(),2);
	assertEquals(cur->getField(0,(uint32_t)0),"1");
	assertEquals(cur->getField(1,(uint32_t)0),"2");
	assertEquals(cur->getField(2,(uint32_t)0),"3");
	stdoutput.printf("\n");
	assertEquals(cur->firstRowIndex(),2);
	assertFalse(cur->endOfResultSet());
	assertEquals(cur->rowCount(),4);
	assertEquals(cur->getField(6,(uint32_t)0),"7");
	assertEquals(cur->getField(7,(uint32_t)0),"8");
	stdoutput.printf("\n");
	assertEquals(cur->firstRowIndex(),6);
	assertFalse(cur->endOfResultSet());
	assertEquals(cur->rowCount(),8);
	assertEquals(cur->getField(8,(uint32_t)0),NULL);
	stdoutput.printf("\n");
	assertEquals(cur->firstRowIndex(),8);
	assertTrue(cur->endOfResultSet());
	assertEquals(cur->rowCount(),8);
	stdoutput.printf("\n");

	stdoutput.printf("DONT GET COLUMN INFO: \n");
	cur->dontGetColumnInfo();
	assertTrue(cur->sendQuery("select * from testtable order by testint"));
	assertEquals(cur->getColumnName(0),NULL);
	assertEquals(cur->getColumnLength((uint32_t)0),0);
	assertEquals(cur->getColumnType((uint32_t)0),NULL);
	cur->getColumnInfo();
	assertTrue(cur->sendQuery("select * from testtable order by testint"));
	assertEquals(cur->getColumnName(0),"testint");
	assertEquals(cur->getColumnLength((uint32_t)0),4);
	assertEquals(cur->getColumnType((uint32_t)0),"INT");
	stdoutput.printf("\n");

	stdoutput.printf("SUSPENDED SESSION: \n");
	assertTrue(cur->sendQuery("select * from testtable order by testint"));
	cur->suspendResultSet();
	assertTrue(con->suspendSession());
	port=con->getConnectionPort();
	socket=charstring::duplicate(con->getConnectionSocket());
	assertTrue(con->resumeSession(port,socket));
	stdoutput.printf("\n");
	assertEquals(cur->getField(0,(uint32_t)0),"1");
	assertEquals(cur->getField(1,(uint32_t)0),"2");
	assertEquals(cur->getField(2,(uint32_t)0),"3");
	assertEquals(cur->getField(3,(uint32_t)0),"4");
	assertEquals(cur->getField(4,(uint32_t)0),"5");
	assertEquals(cur->getField(5,(uint32_t)0),"6");
	assertEquals(cur->getField(6,(uint32_t)0),"7");
	assertEquals(cur->getField(7,(uint32_t)0),"8");
	stdoutput.printf("\n");
	assertTrue(cur->sendQuery("select * from testtable order by testint"));
	cur->suspendResultSet();
	assertTrue(con->suspendSession());
	port=con->getConnectionPort();
	socket=charstring::duplicate(con->getConnectionSocket());
	assertTrue(con->resumeSession(port,socket));
	assertEquals(cur->getField(0,(uint32_t)0),"1");
	assertEquals(cur->getField(1,(uint32_t)0),"2");
	assertEquals(cur->getField(2,(uint32_t)0),"3");
	assertEquals(cur->getField(3,(uint32_t)0),"4");
	assertEquals(cur->getField(4,(uint32_t)0),"5");
	assertEquals(cur->getField(5,(uint32_t)0),"6");
	assertEquals(cur->getField(6,(uint32_t)0),"7");
	assertEquals(cur->getField(7,(uint32_t)0),"8");
	stdoutput.printf("\n");
	assertTrue(cur->sendQuery("select * from testtable order by testint"));
	cur->suspendResultSet();
	assertTrue(con->suspendSession());
	port=con->getConnectionPort();
	socket=charstring::duplicate(con->getConnectionSocket());
	assertTrue(con->resumeSession(port,socket));
	stdoutput.printf("\n");
	assertEquals(cur->getField(0,(uint32_t)0),"1");
	assertEquals(cur->getField(1,(uint32_t)0),"2");
	assertEquals(cur->getField(2,(uint32_t)0),"3");
	assertEquals(cur->getField(3,(uint32_t)0),"4");
	assertEquals(cur->getField(4,(uint32_t)0),"5");
	assertEquals(cur->getField(5,(uint32_t)0),"6");
	assertEquals(cur->getField(6,(uint32_t)0),"7");
	assertEquals(cur->getField(7,(uint32_t)0),"8");
	stdoutput.printf("\n");

	stdoutput.printf("SUSPENDED RESULT SET: \n");
	cur->setResultSetBufferSize(2);
	assertTrue(cur->sendQuery("select * from testtable order by testint"));
	assertEquals(cur->getField(2,(uint32_t)0),"3");
	id=cur->getResultSetId();
	cur->suspendResultSet();
	assertTrue(con->suspendSession());
	port=con->getConnectionPort();
	socket=charstring::duplicate(con->getConnectionSocket());
	assertTrue(con->resumeSession(port,socket));
	assertTrue(cur->resumeResultSet(id));
	stdoutput.printf("\n");
	assertEquals(cur->firstRowIndex(),4);
	assertFalse(cur->endOfResultSet());
	assertEquals(cur->rowCount(),6);
	assertEquals(cur->getField(7,(uint32_t)0),"8");
	stdoutput.printf("\n");
	assertEquals(cur->firstRowIndex(),6);
	assertFalse(cur->endOfResultSet());
	assertEquals(cur->rowCount(),8);
	assertEquals(cur->getField(8,(uint32_t)0),NULL);
	stdoutput.printf("\n");
	assertEquals(cur->firstRowIndex(),8);
	assertTrue(cur->endOfResultSet());
	assertEquals(cur->rowCount(),8);
	cur->setResultSetBufferSize(0);
	stdoutput.printf("\n");

	stdoutput.printf("CACHED RESULT SET: \n");
	cur->cacheToFile("cachefile1");
	cur->setCacheTtl(200);
	assertTrue(cur->sendQuery("select * from testtable order by testint"));
	filename=charstring::duplicate(cur->getCacheFileName());
	assertEquals(filename,"cachefile1");
	cur->cacheOff();
	assertTrue(cur->openCachedResultSet(filename));
	assertEquals(cur->getField(7,(uint32_t)0),"8");
	delete[] filename;
	stdoutput.printf("\n");

	stdoutput.printf("COLUMN COUNT FOR CACHED RESULT SET: \n");
	assertEquals(cur->colCount(),15);
	stdoutput.printf("\n");

	stdoutput.printf("COLUMN NAMES FOR CACHED RESULT SET: \n");
	assertEquals(cur->getColumnName(0),"testint");
	assertEquals(cur->getColumnName(1),"testsmallint");
	assertEquals(cur->getColumnName(2),"testtinyint");
	assertEquals(cur->getColumnName(3),"testreal");
	assertEquals(cur->getColumnName(4),"testfloat");
	assertEquals(cur->getColumnName(5),"testdecimal");
	assertEquals(cur->getColumnName(6),"testnumeric");
	assertEquals(cur->getColumnName(7),"testmoney");
	assertEquals(cur->getColumnName(8),"testsmallmoney");
	assertEquals(cur->getColumnName(9),"testdatetime");
	assertEquals(cur->getColumnName(10),"testsmalldatetime");
	assertEquals(cur->getColumnName(11),"testchar");
	assertEquals(cur->getColumnName(12),"testvarchar");
	assertEquals(cur->getColumnName(13),"testbit");
	cols=cur->getColumnNames();
	assertEquals(cols[0],"testint");
	assertEquals(cols[1],"testsmallint");
	assertEquals(cols[2],"testtinyint");
	assertEquals(cols[3],"testreal");
	assertEquals(cols[4],"testfloat");
	assertEquals(cols[5],"testdecimal");
	assertEquals(cols[6],"testnumeric");
	assertEquals(cols[7],"testmoney");
	assertEquals(cols[8],"testsmallmoney");
	assertEquals(cols[9],"testdatetime");
	assertEquals(cols[10],"testsmalldatetime");
	assertEquals(cols[11],"testchar");
	assertEquals(cols[12],"testvarchar");
	assertEquals(cols[13],"testbit");
	stdoutput.printf("\n");

	stdoutput.printf("CACHED RESULT SET WITH RESULT SET BUFFER SIZE: \n");
	cur->setResultSetBufferSize(2);
	cur->cacheToFile("cachefile1");
	cur->setCacheTtl(200);
	assertTrue(cur->sendQuery("select * from testtable order by testint"));
	filename=charstring::duplicate(cur->getCacheFileName());
	assertEquals(filename,"cachefile1");
	cur->cacheOff();
	assertTrue(cur->openCachedResultSet(filename));
	assertEquals(cur->getField(7,(uint32_t)0),"8");
	assertEquals(cur->getField(8,(uint32_t)0),NULL);
	cur->setResultSetBufferSize(0);
	delete[] filename;
	stdoutput.printf("\n");

	stdoutput.printf("FROM ONE CACHE FILE TO ANOTHER: \n");
	cur->cacheToFile("cachefile2");
	assertTrue(cur->openCachedResultSet("cachefile1"));
	cur->cacheOff();
	assertTrue(cur->openCachedResultSet("cachefile2"));
	assertEquals(cur->getField(7,(uint32_t)0),"8");
	assertEquals(cur->getField(8,(uint32_t)0),NULL);
	stdoutput.printf("\n");

	stdoutput.printf("FROM ONE CACHE FILE TO ANOTHER WITH RESULT SET BUFFER SIZE: \n");
	cur->setResultSetBufferSize(2);
	cur->cacheToFile("cachefile2");
	assertTrue(cur->openCachedResultSet("cachefile1"));
	cur->cacheOff();
	assertTrue(cur->openCachedResultSet("cachefile2"));
	assertEquals(cur->getField(7,(uint32_t)0),"8");
	assertEquals(cur->getField(8,(uint32_t)0),NULL);
	cur->setResultSetBufferSize(0);
	stdoutput.printf("\n");

	stdoutput.printf("CACHED RESULT SET WITH SUSPEND AND RESULT SET BUFFER SIZE: \n");
	cur->setResultSetBufferSize(2);
	cur->cacheToFile("cachefile1");
	cur->setCacheTtl(200);
	assertTrue(cur->sendQuery("select * from testtable order by testint"));
	assertEquals(cur->getField(2,(uint32_t)0),"3");
	filename=charstring::duplicate(cur->getCacheFileName());
	assertEquals(filename,"cachefile1");
	id=cur->getResultSetId();
	cur->suspendResultSet();
	assertTrue(con->suspendSession());
	port=con->getConnectionPort();
	socket=charstring::duplicate(con->getConnectionSocket());
	stdoutput.printf("\n");
	assertTrue(con->resumeSession(port,socket));
	assertTrue(cur->resumeCachedResultSet(id,filename));
	stdoutput.printf("\n");
	assertEquals(cur->firstRowIndex(),4);
	assertFalse(cur->endOfResultSet());
	assertEquals(cur->rowCount(),6);
	assertEquals(cur->getField(7,(uint32_t)0),"8");
	stdoutput.printf("\n");
	assertEquals(cur->firstRowIndex(),6);
	assertFalse(cur->endOfResultSet());
	assertEquals(cur->rowCount(),8);
	assertEquals(cur->getField(8,(uint32_t)0),NULL);
	stdoutput.printf("\n");
	assertEquals(cur->firstRowIndex(),8);
	assertTrue(cur->endOfResultSet());
	assertEquals(cur->rowCount(),8);
	cur->cacheOff();
	stdoutput.printf("\n");
	assertTrue(cur->openCachedResultSet(filename));
	assertEquals(cur->getField(7,(uint32_t)0),"8");
	assertEquals(cur->getField(8,(uint32_t)0),NULL);
	cur->setResultSetBufferSize(0);
	delete[] filename;
	stdoutput.printf("\n");

	stdoutput.printf("STORED PROCEDURE WITH RESULT SET: \n");
	assertTrue(cur->sendQuery("exec testselectproc"));
	stdoutput.printf("\n");
	assertEquals(cur->getField(0,(uint32_t)0),"1");
	assertEquals(cur->getField(0,1),"1");
	assertEquals(cur->getField(0,2),"1");
	//assertEquals(cur->getField(0,3),"1.1");
	//assertEquals(cur->getField(0,4),"1.1");
	assertEquals(cur->getField(0,5),"1.1");
	assertEquals(cur->getField(0,6),"1.1");
	assertEquals(cur->getField(0,7),"1.00");
	assertEquals(cur->getField(0,8),"1.00");
	assertEquals(cur->getField(0,9),"Jan  1 2001  1:00AM");
	assertEquals(cur->getField(0,10),"Jan  1 2001  1:00AM");
	assertEquals(cur->getField(0,11),"testchar1                               ");
	assertEquals(cur->getField(0,12),"testvarchar1");
	assertEquals(cur->getField(0,13),"1");
	stdoutput.printf("\n");
	assertEquals(cur->getField(7,(uint32_t)0),"8");
	assertEquals(cur->getField(7,1),"8");
	assertEquals(cur->getField(7,2),"8");
	//assertEquals(cur->getField(7,3),"8.8");
	//assertEquals(cur->getField(7,4),"8.8");
	assertEquals(cur->getField(7,5),"8.8");
	assertEquals(cur->getField(7,6),"8.8");
	assertEquals(cur->getField(7,7),"8.00");
	assertEquals(cur->getField(7,8),"8.00");
	assertEquals(cur->getField(7,9),"Jan  1 2008  8:00AM");
	assertEquals(cur->getField(7,10),"Jan  1 2008  8:00AM");
	assertEquals(cur->getField(7,11),"testchar8                               ");
	assertEquals(cur->getField(7,12),"testvarchar8");
	assertEquals(cur->getField(7,13),"1");
	stdoutput.printf("\n");

	stdoutput.printf("DIRECT TRANSACTSQL: \n");
	assertTrue(cur->sendQuery("BEGIN declare @s varchar(20) declare @e varchar(20) set @s = 'hello' set @e = 'goodbye' select @s as s, @e as e END"));
	assertEquals(cur->getField(0,"s"),"hello");
	assertEquals(cur->getField(0,"e"),"goodbye");
	stdoutput.printf("\n");

	stdoutput.printf("NESTED SELECTS: \n");
	cur->setResultSetBufferSize(1);
	assertTrue(cur->sendQuery("select * from testtable"));
	uint32_t i=0;
	while (cur->getRow(i++)) {
		sqlrcursor	*cur2=new sqlrcursor(con);
		cur2->setResultSetBufferSize(1);
		assertTrue(cur2->sendQuery("select * from testtable"));
		delete cur2;
	}
	stdoutput.printf("\n");
	

	// drop existing table
	stdoutput.printf("COMMIT/DROP TABLE: \n");
	assertTrue(con->commit());
	assertTrue(cur->sendQuery("drop table testtable"));
	stdoutput.printf("\n");

	// temporary tables
	stdoutput.printf("TEMPORARY TABLES: \n");
	cur->sendQuery("drop table temptable\n");
	cur->sendQuery("create table #temptable (col1 int)");
	assertTrue(cur->sendQuery("insert into #temptable values (1)"));
	assertTrue(cur->sendQuery("select count(*) from #temptable"));
	assertEquals(cur->getField(0,(uint32_t)0),"1");
	con->endSession();
	stdoutput.printf("\n");
	assertFalse(cur->sendQuery("select count(*) from #temptable"));
	cur->sendQuery("drop table #temptable\n");
	stdoutput.printf("\n");

	// invalid queries...
	stdoutput.printf("INVALID QUERIES: \n");
	assertFalse(cur->sendQuery("select * from testtable order by testint"));
	assertFalse(cur->sendQuery("select * from testtable order by testint"));
	assertFalse(cur->sendQuery("select * from testtable order by testint"));
	assertFalse(cur->sendQuery("select * from testtable order by testint"));
	stdoutput.printf("\n");
	assertFalse(cur->sendQuery("insert into testtable values (1,2,3,4)"));
	assertFalse(cur->sendQuery("insert into testtable values (1,2,3,4)"));
	assertFalse(cur->sendQuery("insert into testtable values (1,2,3,4)"));
	assertFalse(cur->sendQuery("insert into testtable values (1,2,3,4)"));
	stdoutput.printf("\n");
	assertFalse(cur->sendQuery("create table testtable"));
	assertFalse(cur->sendQuery("create table testtable"));
	assertFalse(cur->sendQuery("create table testtable"));
	assertFalse(cur->sendQuery("create table testtable"));
	stdoutput.printf("\n");

	return 0;
}
