/*
 * This file was generated automatically by xsubpp version 1.9507 from the 
 * contents of Connection.xs. Do not edit this file, edit Connection.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Connection.xs"
/* Copyright (c) David Muse
   See the file COPYING for more information */

#include <config.h>

// SCO OSR6 requires this
#ifdef SQLRELAY_HAVE_SYS_VNODE_H
	#include <sys/vnode.h>
#endif

#include "../c++/sqlrelay/sqlrclient.h"

// Some verions of perl (5.38) define a "struct object" which collides with
// the rudiments object class.  Do this trickery to work around that.
#define object perlobject

#include <EXTERN.h>
#define explicit

#if defined(WIN32)

	// some versions of active perl erroneously try to
	// use __inline__ which isn't valid for MSVC
	#ifdef _MSC_VER
		#define __inline__ __inline
	#endif

	// msvc < 2013 (version 18.00) don't have stdbool.h
	// active perl 5.20 and up require either stdbool.h or this workaround
	#if _MSC_VER<1800
		#include <patchlevel.h>
		#if PERL_REVISION>5 || (PERL_REVISION==5 && PERL_VERSION>=20)
			#define PERL_BOOL_AS_CHAR
			#define __inline__ inline
		#endif
	#endif
#endif

#ifndef _SCO_DS
extern "C" {
#endif
	#include <perl.h>
#ifndef _SCO_DS
}
#endif

#include <XSUB.h>
#ifdef CLASS
	#undef CLASS
#endif

#ifdef THIS
	#undef THIS
#endif

#ifdef PERL500
	#ifndef SvUV
        	#define SvUV SvIV
	#endif
	#ifndef sv_setuv
        	#define sv_setuv sv_setiv
	#endif
	#ifndef PERLREALLYOLD
        	#undef sv_setpv
        	#define sv_setpv(a,b) Perl_sv_setpv(a,(char *)b)
        	#undef sv_setpvn
        	#define sv_setpvn(a,b,c) Perl_sv_setpvn(a,(char *)b,c)
	#else
		#define CLASS "SQLRelay::Connection"
	#endif
#endif

#ifdef WIN32
	#undef XS_EXTERNAL
	#undef XS_INTERNAL
	#define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
	#define XS_INTERNAL(name) STATIC XSPROTO(name)
#endif

/* xsubpp outputs __attribute__((noreturn)) this isn't
 * understood by gcc < 3.0. */
#ifdef __GNUC__
	#if __GNUC__ < 3
		#define __attribute__(x)
	#endif
#endif

typedef class sqlrconnection sqlrconnection;

#line 100 "Connection.c"
XS(XS_SQLRelay__Connection_new)
{
    dXSARGS;
    if (items != 8)
	croak("Usage: SQLRelay::Connection::new(CLASS, server,port,socket,user,password,retrytime,tries)");
    {
	const char *	server = (const char *)SvPV(ST(1),PL_na);
	uint16_t	port;
	const char *	socket = (const char *)SvPV(ST(3),PL_na);
	const char *	user = (const char *)SvPV(ST(4),PL_na);
	const char *	password = (const char *)SvPV(ST(5),PL_na);
	int32_t	retrytime;
	int32_t	tries;
	char *	CLASS = (char *)SvPV(ST(0),PL_na);
	sqlrconnection *	RETVAL;

	port=(uint16_t)SvUV(ST(2));

	retrytime=(int32_t)SvIV(ST(6));

	tries=(int32_t)SvIV(ST(7));
#line 102 "Connection.xs"
		RETVAL=new sqlrconnection(server,port,socket,
					user,password,retrytime,tries,true);
#line 125 "Connection.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );

    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_DESTROY)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::DESTROY(THIS)");
    {
	sqlrconnection *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	delete THIS;
    }
    XSRETURN_EMPTY;
}

XS(XS_SQLRelay__Connection_setConnectTimeout)
{
    dXSARGS;
    if (items != 3)
	croak("Usage: SQLRelay::Connection::setConnectTimeout(THIS, timeoutsec,timeoutusec)");
    {
	int32_t	timeoutsec;
	int32_t	timeoutusec;
	sqlrconnection *	THIS;

	timeoutsec=(int32_t)SvIV(ST(1));

	timeoutusec=(int32_t)SvIV(ST(2));

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::setConnectTimeout() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	THIS->setConnectTimeout(timeoutsec, timeoutusec);
    }
    XSRETURN_EMPTY;
}

XS(XS_SQLRelay__Connection_getConnectTimeoutSeconds)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getConnectTimeoutSeconds(THIS)");
    {
	sqlrconnection *	THIS;
	int32_t	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getConnectTimeoutSeconds() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getConnectTimeoutSeconds();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getConnectTimeoutMicroseconds)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getConnectTimeoutMicroseconds(THIS)");
    {
	sqlrconnection *	THIS;
	int32_t	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getConnectTimeoutMicroseconds() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getConnectTimeoutMicroseconds();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_setResponseTimeout)
{
    dXSARGS;
    if (items != 3)
	croak("Usage: SQLRelay::Connection::setResponseTimeout(THIS, timeoutsec,timeoutusec)");
    {
	int32_t	timeoutsec;
	int32_t	timeoutusec;
	sqlrconnection *	THIS;

	timeoutsec=(int32_t)SvIV(ST(1));

	timeoutusec=(int32_t)SvIV(ST(2));

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::setResponseTimeout() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	THIS->setResponseTimeout(timeoutsec, timeoutusec);
    }
    XSRETURN_EMPTY;
}

XS(XS_SQLRelay__Connection_getResponseTimeoutSeconds)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getResponseTimeoutSeconds(THIS)");
    {
	sqlrconnection *	THIS;
	int32_t	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getResponseTimeoutSeconds() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getResponseTimeoutSeconds();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getResponseTimeoutMicroseconds)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getResponseTimeoutMicroseconds(THIS)");
    {
	sqlrconnection *	THIS;
	int32_t	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getResponseTimeoutMicroseconds() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getResponseTimeoutMicroseconds();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_setBindVariableDelimiters)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: SQLRelay::Connection::setBindVariableDelimiters(THIS, delimiters)");
    {
	const char *	delimiters = (const char *)SvPV(ST(1),PL_na);
	sqlrconnection *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::setBindVariableDelimiters() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	THIS->setBindVariableDelimiters(delimiters);
    }
    XSRETURN_EMPTY;
}

XS(XS_SQLRelay__Connection_getBindVariableDelimiterQuestionMarkSupported)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getBindVariableDelimiterQuestionMarkSupported(THIS)");
    {
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getBindVariableDelimiterQuestionMarkSupported() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getBindVariableDelimiterQuestionMarkSupported();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getBindVariableDelimiterColonSupported)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getBindVariableDelimiterColonSupported(THIS)");
    {
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getBindVariableDelimiterColonSupported() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getBindVariableDelimiterColonSupported();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getBindVariableDelimiterAtSignSupported)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getBindVariableDelimiterAtSignSupported(THIS)");
    {
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getBindVariableDelimiterAtSignSupported() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getBindVariableDelimiterAtSignSupported();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getBindVariableDelimiterDollarSignSupported)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getBindVariableDelimiterDollarSignSupported(THIS)");
    {
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getBindVariableDelimiterDollarSignSupported() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getBindVariableDelimiterDollarSignSupported();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_enableKerberos)
{
    dXSARGS;
    if (items != 4)
	croak("Usage: SQLRelay::Connection::enableKerberos(THIS, service,mech,flags)");
    {
	const char *	service = (const char *)SvPV(ST(1),PL_na);
	const char *	mech = (const char *)SvPV(ST(2),PL_na);
	const char *	flags = (const char *)SvPV(ST(3),PL_na);
	sqlrconnection *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::enableKerberos() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	THIS->enableKerberos(service, mech, flags);
    }
    XSRETURN_EMPTY;
}

XS(XS_SQLRelay__Connection_enableTls)
{
    dXSARGS;
    if (items != 8)
	croak("Usage: SQLRelay::Connection::enableTls(THIS, version,cert,password,ciphers,validate,ca,depth)");
    {
	const char *	version = (const char *)SvPV(ST(1),PL_na);
	const char *	cert = (const char *)SvPV(ST(2),PL_na);
	const char *	password = (const char *)SvPV(ST(3),PL_na);
	const char *	ciphers = (const char *)SvPV(ST(4),PL_na);
	const char *	validate = (const char *)SvPV(ST(5),PL_na);
	const char *	ca = (const char *)SvPV(ST(6),PL_na);
	uint16_t	depth;
	sqlrconnection *	THIS;

	depth=(uint16_t)SvUV(ST(7));

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::enableTls() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	THIS->enableTls(version, cert, password, ciphers, validate, ca, depth);
    }
    XSRETURN_EMPTY;
}

XS(XS_SQLRelay__Connection_disableEncryption)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::disableEncryption(THIS)");
    {
	sqlrconnection *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::disableEncryption() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	THIS->disableEncryption();
    }
    XSRETURN_EMPTY;
}

XS(XS_SQLRelay__Connection_endSession)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::endSession(THIS)");
    {
	sqlrconnection *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::endSession() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	THIS->endSession();
    }
    XSRETURN_EMPTY;
}

XS(XS_SQLRelay__Connection_suspendSession)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::suspendSession(THIS)");
    {
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::suspendSession() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->suspendSession();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getConnectionPort)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getConnectionPort(THIS)");
    {
	sqlrconnection *	THIS;
	int16_t	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getConnectionPort() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getConnectionPort();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getConnectionSocket)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getConnectionSocket(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getConnectionSocket() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getConnectionSocket();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_resumeSession)
{
    dXSARGS;
    if (items != 3)
	croak("Usage: SQLRelay::Connection::resumeSession(THIS, port,socket)");
    {
	int16_t	port;
	const char *	socket = (const char *)SvPV(ST(2),PL_na);
	sqlrconnection *	THIS;
	bool	RETVAL;

	port=(int16_t)SvIV(ST(1));

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::resumeSession() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->resumeSession(port, socket);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_ping)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::ping(THIS)");
    {
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::ping() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->ping();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_selectDatabase)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: SQLRelay::Connection::selectDatabase(THIS, database)");
    {
	const char *	database = (const char *)SvPV(ST(1),PL_na);
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::selectDatabase() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->selectDatabase(database);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getCurrentDatabase)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getCurrentDatabase(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getCurrentDatabase() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getCurrentDatabase();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getDatabaseIsSchema)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getDatabaseIsSchema(THIS)");
    {
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getDatabaseIsSchema() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getDatabaseIsSchema();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_selectCatalog)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: SQLRelay::Connection::selectCatalog(THIS, catalog)");
    {
	const char *	catalog = (const char *)SvPV(ST(1),PL_na);
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::selectCatalog() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->selectCatalog(catalog);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getCurrentCatalog)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getCurrentCatalog(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getCurrentCatalog() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getCurrentCatalog();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_selectSchema)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: SQLRelay::Connection::selectSchema(THIS, schema)");
    {
	const char *	schema = (const char *)SvPV(ST(1),PL_na);
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::selectSchema() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->selectSchema(schema);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getCurrentSchema)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getCurrentSchema(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getCurrentSchema() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getCurrentSchema();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getLastInsertId)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getLastInsertId(THIS)");
    {
	sqlrconnection *	THIS;
	uint64_t	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getLastInsertId() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getLastInsertId();
	ST(0) = sv_newmortal();
	sv_setuv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_autoCommitOn)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::autoCommitOn(THIS)");
    {
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::autoCommitOn() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->autoCommitOn();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_autoCommitOff)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::autoCommitOff(THIS)");
    {
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::autoCommitOff() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->autoCommitOff();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getAutoCommit)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getAutoCommit(THIS)");
    {
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getAutoCommit() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getAutoCommit();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_begin)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::begin(THIS)");
    {
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::begin() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->begin();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_commit)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::commit(THIS)");
    {
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::commit() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->commit();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_rollback)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::rollback(THIS)");
    {
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::rollback() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->rollback();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getInTransaction)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getInTransaction(THIS)");
    {
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getInTransaction() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getInTransaction();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getDefaultTransactionModel)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getDefaultTransactionModel(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getDefaultTransactionModel() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getDefaultTransactionModel();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_setTransactionModel)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: SQLRelay::Connection::setTransactionModel(THIS, txmodel)");
    {
	const char *	txmodel = (const char *)SvPV(ST(1),PL_na);
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::setTransactionModel() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->setTransactionModel(txmodel);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getTransactionModel)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getTransactionModel(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getTransactionModel() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getTransactionModel();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_setIsolationLevel)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: SQLRelay::Connection::setIsolationLevel(THIS, isolationlevel)");
    {
	const char *	isolationlevel = (const char *)SvPV(ST(1),PL_na);
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::setIsolationLevel() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->setIsolationLevel(isolationlevel);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getIsolationLevel)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getIsolationLevel(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getIsolationLevel() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getIsolationLevel();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_getDatabaseFeature)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: SQLRelay::Connection::getDatabaseFeature(THIS, feature)");
    {
	const char *	feature = (const char *)SvPV(ST(1),PL_na);
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getDatabaseFeature() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getDatabaseFeature(feature);
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_identify)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::identify(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::identify() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->identify();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_dbVersion)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::dbVersion(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::dbVersion() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->dbVersion();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_dbHostName)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::dbHostName(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::dbHostName() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->dbHostName();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_dbIpAddress)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::dbIpAddress(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::dbIpAddress() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->dbIpAddress();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_serverVersion)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::serverVersion(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::serverVersion() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->serverVersion();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_clientVersion)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::clientVersion(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::clientVersion() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->clientVersion();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_bindFormat)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::bindFormat(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::bindFormat() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->bindFormat();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_nextvalFormat)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::nextvalFormat(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::nextvalFormat() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->nextvalFormat();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_errorMessage)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::errorMessage(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::errorMessage() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->errorMessage();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_errorNumber)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::errorNumber(THIS)");
    {
	sqlrconnection *	THIS;
	int64_t	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::errorNumber() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->errorNumber();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_errorSqlState)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::errorSqlState(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::errorSqlState() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->errorSqlState();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_debugOn)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::debugOn(THIS)");
    {
	sqlrconnection *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::debugOn() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	THIS->debugOn();
    }
    XSRETURN_EMPTY;
}

XS(XS_SQLRelay__Connection_debugOff)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::debugOff(THIS)");
    {
	sqlrconnection *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::debugOff() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	THIS->debugOff();
    }
    XSRETURN_EMPTY;
}

XS(XS_SQLRelay__Connection_getDebug)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getDebug(THIS)");
    {
	sqlrconnection *	THIS;
	bool	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getDebug() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getDebug();
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_setDebugFile)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: SQLRelay::Connection::setDebugFile(THIS, filename)");
    {
	const char *	filename = (const char *)SvPV(ST(1),PL_na);
	sqlrconnection *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::setDebugFile() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	THIS->setDebugFile(filename);
    }
    XSRETURN_EMPTY;
}

XS(XS_SQLRelay__Connection_setClientInfo)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: SQLRelay::Connection::setClientInfo(THIS, clientinfo)");
    {
	const char *	clientinfo = (const char *)SvPV(ST(1),PL_na);
	sqlrconnection *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::setClientInfo() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	THIS->setClientInfo(clientinfo);
    }
    XSRETURN_EMPTY;
}

XS(XS_SQLRelay__Connection_getClientInfo)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: SQLRelay::Connection::getClientInfo(THIS)");
    {
	sqlrconnection *	THIS;
	const char *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (sqlrconnection *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "SQLRelay::Connection::getClientInfo() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->getClientInfo();
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_isYes)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: SQLRelay::Connection::isYes(CLASS, str)");
    {
	const char *	str = (const char *)SvPV(ST(1),PL_na);
	char *	CLASS = (char *)SvPV(ST(0),PL_na);
	bool	RETVAL;

	RETVAL = sqlrconnection::isYes(str);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_SQLRelay__Connection_isNo)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: SQLRelay::Connection::isNo(CLASS, str)");
    {
	const char *	str = (const char *)SvPV(ST(1),PL_na);
	char *	CLASS = (char *)SvPV(ST(0),PL_na);
	bool	RETVAL;

	RETVAL = sqlrconnection::isNo(str);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_SQLRelay__Connection)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("SQLRelay::Connection::new", XS_SQLRelay__Connection_new, file);
        newXS("SQLRelay::Connection::DESTROY", XS_SQLRelay__Connection_DESTROY, file);
        newXS("SQLRelay::Connection::setConnectTimeout", XS_SQLRelay__Connection_setConnectTimeout, file);
        newXS("SQLRelay::Connection::getConnectTimeoutSeconds", XS_SQLRelay__Connection_getConnectTimeoutSeconds, file);
        newXS("SQLRelay::Connection::getConnectTimeoutMicroseconds", XS_SQLRelay__Connection_getConnectTimeoutMicroseconds, file);
        newXS("SQLRelay::Connection::setResponseTimeout", XS_SQLRelay__Connection_setResponseTimeout, file);
        newXS("SQLRelay::Connection::getResponseTimeoutSeconds", XS_SQLRelay__Connection_getResponseTimeoutSeconds, file);
        newXS("SQLRelay::Connection::getResponseTimeoutMicroseconds", XS_SQLRelay__Connection_getResponseTimeoutMicroseconds, file);
        newXS("SQLRelay::Connection::setBindVariableDelimiters", XS_SQLRelay__Connection_setBindVariableDelimiters, file);
        newXS("SQLRelay::Connection::getBindVariableDelimiterQuestionMarkSupported", XS_SQLRelay__Connection_getBindVariableDelimiterQuestionMarkSupported, file);
        newXS("SQLRelay::Connection::getBindVariableDelimiterColonSupported", XS_SQLRelay__Connection_getBindVariableDelimiterColonSupported, file);
        newXS("SQLRelay::Connection::getBindVariableDelimiterAtSignSupported", XS_SQLRelay__Connection_getBindVariableDelimiterAtSignSupported, file);
        newXS("SQLRelay::Connection::getBindVariableDelimiterDollarSignSupported", XS_SQLRelay__Connection_getBindVariableDelimiterDollarSignSupported, file);
        newXS("SQLRelay::Connection::enableKerberos", XS_SQLRelay__Connection_enableKerberos, file);
        newXS("SQLRelay::Connection::enableTls", XS_SQLRelay__Connection_enableTls, file);
        newXS("SQLRelay::Connection::disableEncryption", XS_SQLRelay__Connection_disableEncryption, file);
        newXS("SQLRelay::Connection::endSession", XS_SQLRelay__Connection_endSession, file);
        newXS("SQLRelay::Connection::suspendSession", XS_SQLRelay__Connection_suspendSession, file);
        newXS("SQLRelay::Connection::getConnectionPort", XS_SQLRelay__Connection_getConnectionPort, file);
        newXS("SQLRelay::Connection::getConnectionSocket", XS_SQLRelay__Connection_getConnectionSocket, file);
        newXS("SQLRelay::Connection::resumeSession", XS_SQLRelay__Connection_resumeSession, file);
        newXS("SQLRelay::Connection::ping", XS_SQLRelay__Connection_ping, file);
        newXS("SQLRelay::Connection::selectDatabase", XS_SQLRelay__Connection_selectDatabase, file);
        newXS("SQLRelay::Connection::getCurrentDatabase", XS_SQLRelay__Connection_getCurrentDatabase, file);
        newXS("SQLRelay::Connection::getDatabaseIsSchema", XS_SQLRelay__Connection_getDatabaseIsSchema, file);
        newXS("SQLRelay::Connection::selectCatalog", XS_SQLRelay__Connection_selectCatalog, file);
        newXS("SQLRelay::Connection::getCurrentCatalog", XS_SQLRelay__Connection_getCurrentCatalog, file);
        newXS("SQLRelay::Connection::selectSchema", XS_SQLRelay__Connection_selectSchema, file);
        newXS("SQLRelay::Connection::getCurrentSchema", XS_SQLRelay__Connection_getCurrentSchema, file);
        newXS("SQLRelay::Connection::getLastInsertId", XS_SQLRelay__Connection_getLastInsertId, file);
        newXS("SQLRelay::Connection::autoCommitOn", XS_SQLRelay__Connection_autoCommitOn, file);
        newXS("SQLRelay::Connection::autoCommitOff", XS_SQLRelay__Connection_autoCommitOff, file);
        newXS("SQLRelay::Connection::getAutoCommit", XS_SQLRelay__Connection_getAutoCommit, file);
        newXS("SQLRelay::Connection::begin", XS_SQLRelay__Connection_begin, file);
        newXS("SQLRelay::Connection::commit", XS_SQLRelay__Connection_commit, file);
        newXS("SQLRelay::Connection::rollback", XS_SQLRelay__Connection_rollback, file);
        newXS("SQLRelay::Connection::getInTransaction", XS_SQLRelay__Connection_getInTransaction, file);
        newXS("SQLRelay::Connection::getDefaultTransactionModel", XS_SQLRelay__Connection_getDefaultTransactionModel, file);
        newXS("SQLRelay::Connection::setTransactionModel", XS_SQLRelay__Connection_setTransactionModel, file);
        newXS("SQLRelay::Connection::getTransactionModel", XS_SQLRelay__Connection_getTransactionModel, file);
        newXS("SQLRelay::Connection::setIsolationLevel", XS_SQLRelay__Connection_setIsolationLevel, file);
        newXS("SQLRelay::Connection::getIsolationLevel", XS_SQLRelay__Connection_getIsolationLevel, file);
        newXS("SQLRelay::Connection::getDatabaseFeature", XS_SQLRelay__Connection_getDatabaseFeature, file);
        newXS("SQLRelay::Connection::identify", XS_SQLRelay__Connection_identify, file);
        newXS("SQLRelay::Connection::dbVersion", XS_SQLRelay__Connection_dbVersion, file);
        newXS("SQLRelay::Connection::dbHostName", XS_SQLRelay__Connection_dbHostName, file);
        newXS("SQLRelay::Connection::dbIpAddress", XS_SQLRelay__Connection_dbIpAddress, file);
        newXS("SQLRelay::Connection::serverVersion", XS_SQLRelay__Connection_serverVersion, file);
        newXS("SQLRelay::Connection::clientVersion", XS_SQLRelay__Connection_clientVersion, file);
        newXS("SQLRelay::Connection::bindFormat", XS_SQLRelay__Connection_bindFormat, file);
        newXS("SQLRelay::Connection::nextvalFormat", XS_SQLRelay__Connection_nextvalFormat, file);
        newXS("SQLRelay::Connection::errorMessage", XS_SQLRelay__Connection_errorMessage, file);
        newXS("SQLRelay::Connection::errorNumber", XS_SQLRelay__Connection_errorNumber, file);
        newXS("SQLRelay::Connection::errorSqlState", XS_SQLRelay__Connection_errorSqlState, file);
        newXS("SQLRelay::Connection::debugOn", XS_SQLRelay__Connection_debugOn, file);
        newXS("SQLRelay::Connection::debugOff", XS_SQLRelay__Connection_debugOff, file);
        newXS("SQLRelay::Connection::getDebug", XS_SQLRelay__Connection_getDebug, file);
        newXS("SQLRelay::Connection::setDebugFile", XS_SQLRelay__Connection_setDebugFile, file);
        newXS("SQLRelay::Connection::setClientInfo", XS_SQLRelay__Connection_setClientInfo, file);
        newXS("SQLRelay::Connection::getClientInfo", XS_SQLRelay__Connection_getClientInfo, file);
        newXS("SQLRelay::Connection::isYes", XS_SQLRelay__Connection_isYes, file);
        newXS("SQLRelay::Connection::isNo", XS_SQLRelay__Connection_isNo, file);
    XSRETURN_YES;
}

