#!/bin/sh

if ( test -z "$2" )
then
	export CLASSPATH=$CLASSPATH:/usr/local/firstworks/java/sqlrelay.jar:/usr/local/firstworks/java/sqlrelayjdbc.jar
	export LD_LIBRARY_PATH="/usr/local/firstworks/java/com/firstworks/sqlrelay:/usr/local/firstworks/lib"
else
	if ( test "$2" = "native" )
	then
		jar=""
		case "$1" in
			db2)
				jar=/opt/ibm/db2/V10.5/java/db2jcc4.jar
				;;
			firebird)
				;;
			freetds)
				;;
			informix)
				jar=/opt/informix/jdbc/lib/ifxjdbc.jar
				;;
			mysql)
				jar=mysql-connector-j-9.6.0.jar
				;;
			oracle)
				jar=ojdbc17.jar
				;;
			postgresql)
				jar=postgresql-42.7.10.jar
				;;
			sap)
				;;
			sqlite)
				jar=sqlite-jdbc-3.51.2.0.jar
				;;
		esac
	else
		export CLASSPATH=$CLASSPATH:$2
	fi
fi

java $1
