#!/bin/sh

if ( test -z "$2" )
then
	export CLASSPATH=$CLASSPATH:/usr/local/firstworks/java/sqlrelay.jar:/usr/local/firstworks/java/sqlrelayjdbc.jar
	export LD_LIBRARY_PATH="/usr/local/firstworks/java/com/firstworks/sqlrelay:/usr/local/firstworks/lib"
else
	export CLASSPATH=$CLASSPATH:$2
fi

java $1 $2
