#!/bin/sh

if ( test -z "$2" )
then
	export CLASSPATH=$CLASSPATH:/usr/local/firstworks/java/sqlrelay.jar:/usr/local/firstworks/java/sqlrelayjdbc.jar
	export LD_LIBRARY_PATH="/usr/local/firstworks/java/com/firstworks/sqlrelay:/usr/local/firstworks/lib"
else
	if ( test "$2" = "native" )
	then
		jar=""
		case "$1" in
			db2)
				jar=`ls /opt/ibm/db2/*/java/db2jcc4.jar | tail -1`
				;;
			firebird)
				;;
			freetds)
				jar=`ls drivers/jtds*.jar | tail -1`
				;;
			informix)
				jar=/opt/informix/jdbc/lib/ifxjdbc.jar
				;;
			mysql)
				jar=`ls drivers/mysql-connector-j-*.jar | tail -1`
				;;
			oracle)
				jar=`ls drivers/ojdbc*.jar | tail -1`
				;;
			postgresql)
				jar=`ls drivers/postgresql-*.jar | tail -1`
				;;
			sap)
				jar=`ls /opt/sap/jConnect-*/classes/jconn*.jar | tail -1`
				;;
			sqlite)
				jar=`ls drivers/sqlite-jdbc-*.jar | tail -1`
				;;
		esac
		export CLASSPATH=$CLASSPATH:$jar
	else
		export CLASSPATH=$CLASSPATH:$2
	fi
fi

java $1
