#!/bin/sh

CLASSPATH=$CLASSPATH:/usr/local/firstworks/java/sqlrelay.jar
export CLASSPATH

JAVALIBPATH="/usr/local/firstworks/java/com/firstworks/sqlrelay"
if ( test -n "$LD_LIBRARY_PATH" )
then
	JAVALIBPATH="$LD_LIBRARY_PATH:$JAVALIBPATH"
fi

java -Djava.library.path="$JAVALIBPATH" $1
