top_builddir = ..

include ../config.mk

all:
	cd sqlrelay $(AND) $(MAKE)

install:
	$(MKINSTALLDIRS) $(docdir)
	$(CP) *.html $(docdir)
	$(CHMOD) 755 $(docdir)/*.html
	$(MKINSTALLDIRS) $(docdir)/css
	$(CP) css/* $(docdir)/css
	$(CHMOD) 644 $(docdir)/css/*
	$(MKINSTALLDIRS) $(docdir)/images
	$(CP) images/* $(docdir)/images
	$(CHMOD) 644 $(docdir)/images/*
	$(MKINSTALLDIRS) $(docdir)/js
	$(CP) js/* $(docdir)/js
	$(CHMOD) 644 $(docdir)/js/*
	$(MKINSTALLDIRS) $(docdir)/licenses
	$(CP) licenses/* $(docdir)/licenses
	$(CHMOD) 644 $(docdir)/licenses/*
	$(MKINSTALLDIRS) $(docdir)/presentation
	$(CP) presentation/* $(docdir)/presentation
	$(CHMOD) 755 $(docdir)/presentation/*
	$(MKINSTALLDIRS) $(docdir)/slides
	$(CP) slides/* $(docdir)/slides
	$(CHMOD) 755 $(docdir)/slides/*
	$(MKINSTALLDIRS) $(docdir)/sqlrelay
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/admin
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/ado.net/html
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/c/html
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/c++/html
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/cs/html
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/perl
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/php/media
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/php/sql_relay
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/python
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/ruby/doc/css
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/ruby/doc/fonts
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/ruby/doc/images
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/ruby/doc/js
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/java
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/java/com/firstworks/sqlrelay
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/java/jquery/external/jquery
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/java/jquery/images
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/java/jquery/jszip/dist
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/java/jquery/jszip-utils/dist
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/java/resources
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/tcl
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/erlang/html
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/api/nodejs/html
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/features
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/images
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/js
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/css
	$(MKINSTALLDIRS) $(docdir)/sqlrelay/programming
	$(CP) sqlrelay/*.html $(docdir)/sqlrelay
	$(CHMOD) 644 $(docdir)/sqlrelay/*.html
	$(CP) sqlrelay/admin/*.html $(docdir)/sqlrelay/admin
	$(CHMOD) 644 $(docdir)/sqlrelay/admin/*.html
	$(CP) sqlrelay/css/*.css $(docdir)/sqlrelay/css
	$(CHMOD) 644 $(docdir)/sqlrelay/css/*.css
	$(CP) sqlrelay/api/ado.net/html/*.html $(docdir)/sqlrelay/api/ado.net/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/ado.net/html/*.html
	$(CP) sqlrelay/api/ado.net/html/*.css $(docdir)/sqlrelay/api/ado.net/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/ado.net/html/*.css
	$(CP) sqlrelay/api/ado.net/html/*.png $(docdir)/sqlrelay/api/ado.net/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/ado.net/html/*.png
	$(CP) sqlrelay/api/ado.net/html/*.svg $(docdir)/sqlrelay/api/ado.net/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/ado.net/html/*.svg
	$(CP) sqlrelay/api/ado.net/html/*.js $(docdir)/sqlrelay/api/ado.net/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/ado.net/html/*.js
	$(CP) sqlrelay/api/c/html/*.html $(docdir)/sqlrelay/api/c/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/c/html/*.html
	$(CP) sqlrelay/api/c/html/*.css $(docdir)/sqlrelay/api/c/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/c/html/*.css
	$(CP) sqlrelay/api/c/html/*.png $(docdir)/sqlrelay/api/c/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/c/html/*.png
	$(CP) sqlrelay/api/c/html/*.svg $(docdir)/sqlrelay/api/c/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/c/html/*.svg
	$(CP) sqlrelay/api/c/html/*.js $(docdir)/sqlrelay/api/c/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/c/html/*.js
	$(CP) sqlrelay/api/c++/html/*.html $(docdir)/sqlrelay/api/c++/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/c++/html/*.html
	$(CP) sqlrelay/api/c++/html/*.css $(docdir)/sqlrelay/api/c++/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/c++/html/*.css
	$(CP) sqlrelay/api/c++/html/*.png $(docdir)/sqlrelay/api/c++/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/c++/html/*.png
	$(CP) sqlrelay/api/c++/html/*.svg $(docdir)/sqlrelay/api/c++/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/c++/html/*.svg
	$(CP) sqlrelay/api/c++/html/*.js $(docdir)/sqlrelay/api/c++/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/c++/html/*.js
	$(CP) sqlrelay/api/cs/html/*.html $(docdir)/sqlrelay/api/cs/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/cs/html/*.html
	$(CP) sqlrelay/api/cs/html/*.css $(docdir)/sqlrelay/api/cs/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/cs/html/*.css
	$(CP) sqlrelay/api/cs/html/*.png $(docdir)/sqlrelay/api/cs/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/cs/html/*.png
	$(CP) sqlrelay/api/cs/html/*.svg $(docdir)/sqlrelay/api/cs/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/cs/html/*.svg
	$(CP) sqlrelay/api/cs/html/*.js $(docdir)/sqlrelay/api/cs/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/cs/html/*.js
	$(CP) sqlrelay/api/perl/perl.html $(docdir)/sqlrelay/api/perl
	$(CHMOD) 644 $(docdir)/sqlrelay/api/perl/perl.html
	$(CP) sqlrelay/api/perl/Connection.html $(docdir)/sqlrelay/api/perl
	$(CHMOD) 644 $(docdir)/sqlrelay/api/perl/Connection.html
	$(CP) sqlrelay/api/perl/Cursor.html $(docdir)/sqlrelay/api/perl
	$(CHMOD) 644 $(docdir)/sqlrelay/api/perl/Cursor.html
	$(CP) sqlrelay/api/perl/SQLRelay.html $(docdir)/sqlrelay/api/perl
	$(CHMOD) 644 $(docdir)/sqlrelay/api/perl/SQLRelay.html
	$(CP) sqlrelay/api/php/*.html $(docdir)/sqlrelay/api/php
	$(CHMOD) 644 $(docdir)/sqlrelay/api/php/*.html
	$(CP) sqlrelay/api/php/media/*.css $(docdir)/sqlrelay/api/php/media
	$(CHMOD) 644 $(docdir)/sqlrelay/api/php/media/*.css
	$(CP) sqlrelay/api/php/sql_relay/*.html $(docdir)/sqlrelay/api/php/sql_relay
	$(CHMOD) 644 $(docdir)/sqlrelay/api/php/sql_relay/*.html
	$(CP) sqlrelay/api/python/*.html $(docdir)/sqlrelay/api/python
	$(CHMOD) 644 $(docdir)/sqlrelay/api/python/*.html
	$(CP) sqlrelay/api/ruby/doc/*.html $(docdir)/sqlrelay/api/ruby/doc
	$(CHMOD) 644 $(docdir)/sqlrelay/api/ruby/doc/*.html
	$(CP) sqlrelay/api/ruby/doc/*.rid $(docdir)/sqlrelay/api/ruby/doc
	$(CHMOD) 644 $(docdir)/sqlrelay/api/ruby/doc/*.rid
	$(CP) sqlrelay/api/ruby/doc/css/*.css $(docdir)/sqlrelay/api/ruby/doc/css
	$(CHMOD) 644 $(docdir)/sqlrelay/api/ruby/doc/css/*.css
	$(CP) sqlrelay/api/ruby/doc/images/*.png $(docdir)/sqlrelay/api/ruby/doc/images
	$(CHMOD) 644 $(docdir)/sqlrelay/api/ruby/doc/images/*.png
	$(CP) sqlrelay/api/ruby/doc/images/*.gif $(docdir)/sqlrelay/api/ruby/doc/images
	$(CHMOD) 644 $(docdir)/sqlrelay/api/ruby/doc/images/*.gif
	$(CP) sqlrelay/api/ruby/doc/js/*.js $(docdir)/sqlrelay/api/ruby/doc/js
	$(CHMOD) 644 $(docdir)/sqlrelay/api/ruby/doc/js/*.js
	$(CP) sqlrelay/api/ruby/doc/js/*.js.gz $(docdir)/sqlrelay/api/ruby/doc/js
	$(CHMOD) 644 $(docdir)/sqlrelay/api/ruby/doc/js/*.js.gz
	$(CP) sqlrelay/api/java/*.html $(docdir)/sqlrelay/api/java
	$(CHMOD) 644 $(docdir)/sqlrelay/api/java/*.html
	$(CP) sqlrelay/api/java/*.js $(docdir)/sqlrelay/api/java
	$(CHMOD) 644 $(docdir)/sqlrelay/api/java/*.js
	$(CP) sqlrelay/api/java/*.zip $(docdir)/sqlrelay/api/java
	$(CHMOD) 644 $(docdir)/sqlrelay/api/java/*.zip
	$(CP) sqlrelay/api/java/*.js $(docdir)/sqlrelay/api/java
	$(CHMOD) 644 $(docdir)/sqlrelay/api/java/*.js
	$(CP) sqlrelay/api/java/*.css $(docdir)/sqlrelay/api/java
	$(CHMOD) 644 $(docdir)/sqlrelay/api/java/*.css
	$(CP) sqlrelay/api/java/element-list $(docdir)/sqlrelay/api/java
	$(CHMOD) 644 $(docdir)/sqlrelay/api/java/element-list
	$(CP) sqlrelay/api/java/com/firstworks/sqlrelay/*.html $(docdir)/sqlrelay/api/java/com/firstworks/sqlrelay
	$(CHMOD) 644 $(docdir)/sqlrelay/api/java/com/firstworks/sqlrelay/*.html
	$(CP) sqlrelay/api/java/resources/*.gif $(docdir)/sqlrelay/api/java/resources
	$(CHMOD) 644 $(docdir)/sqlrelay/api/java/resources/*.gif
	$(CP) sqlrelay/api/java/resources/*.png $(docdir)/sqlrelay/api/java/resources
	$(CHMOD) 644 $(docdir)/sqlrelay/api/java/resources/*.png
	$(CP) sqlrelay/api/java/jquery/*.js $(docdir)/sqlrelay/api/java/jquery
	$(CHMOD) 644 $(docdir)/sqlrelay/api/java/jquery/*.js
	$(CP) sqlrelay/api/java/jquery/*.css $(docdir)/sqlrelay/api/java/jquery
	$(CHMOD) 644 $(docdir)/sqlrelay/api/java/jquery/*.css
	$(CP) sqlrelay/api/java/jquery/external/jquery/*.js $(docdir)/sqlrelay/api/java/jquery/external/jquery
	$(CHMOD) 644 $(docdir)/sqlrelay/api/java/jquery/external/jquery/*.js
	$(CP) sqlrelay/api/java/jquery/images/*.png $(docdir)/sqlrelay/api/java/jquery/images
	$(CHMOD) 644 $(docdir)/sqlrelay/api/java/jquery/images/*.png
	$(CP) sqlrelay/api/java/jquery/jszip/dist/*.js $(docdir)/sqlrelay/api/java/jquery/jszip/dist
	$(CHMOD) 644 $(docdir)/sqlrelay/api/java/jquery/jszip/dist/*.js
	$(CP) sqlrelay/api/java/jquery/jszip-utils/dist/*.js $(docdir)/sqlrelay/api/java/jquery/jszip-utils/dist
	$(CHMOD) 644 $(docdir)/sqlrelay/api/java/jquery/jszip-utils/dist/*.js
	$(CP) sqlrelay/api/tcl/*.html $(docdir)/sqlrelay/api/tcl
	$(CHMOD) 644 $(docdir)/sqlrelay/api/tcl/*.html
	$(CP) sqlrelay/api/tcl/*.txt $(docdir)/sqlrelay/api/tcl
	$(CHMOD) 644 $(docdir)/sqlrelay/api/tcl/*.txt
	$(CP) sqlrelay/api/erlang/html/edoc-info $(docdir)/sqlrelay/api/erlang/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/erlang/html/edoc-info
	$(CP) sqlrelay/api/erlang/html/*.png $(docdir)/sqlrelay/api/erlang/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/erlang/html/*.png
	$(CP) sqlrelay/api/erlang/html/*.html $(docdir)/sqlrelay/api/erlang/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/erlang/html/*.html
	$(CP) sqlrelay/api/erlang/html/*.css $(docdir)/sqlrelay/api/erlang/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/erlang/html/*.css
	$(CP) sqlrelay/api/nodejs/html/*.html $(docdir)/sqlrelay/api/nodejs/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/nodejs/html/*.html
	$(CP) sqlrelay/api/nodejs/html/*.css $(docdir)/sqlrelay/api/nodejs/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/nodejs/html/*.css
	$(CP) sqlrelay/api/nodejs/html/*.png $(docdir)/sqlrelay/api/nodejs/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/nodejs/html/*.png
	$(CP) sqlrelay/api/nodejs/html/*.svg $(docdir)/sqlrelay/api/nodejs/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/nodejs/html/*.svg
	$(CP) sqlrelay/api/nodejs/html/*.js $(docdir)/sqlrelay/api/nodejs/html
	$(CHMOD) 644 $(docdir)/sqlrelay/api/nodejs/html/*.js
	$(CP) sqlrelay/features/*.html $(docdir)/sqlrelay/features
	$(CHMOD) 644 $(docdir)/sqlrelay/features/*.html
	$(CP) sqlrelay/images/*.png $(docdir)/sqlrelay/images
	$(CHMOD) 644 $(docdir)/sqlrelay/images/*.png
	$(CP) sqlrelay/images/*.PNG $(docdir)/sqlrelay/images
	$(CHMOD) 644 $(docdir)/sqlrelay/images/*.PNG
	$(CP) sqlrelay/js/*.js $(docdir)/sqlrelay/js
	$(CHMOD) 644 $(docdir)/sqlrelay/js/*.js
	$(CP) sqlrelay/programming/*.html $(docdir)/sqlrelay/programming
	$(CHMOD) 644 $(docdir)/sqlrelay/programming/*.html
	$(MKINSTALLDIRS) $(docdir)/support
	$(CP) support/* $(docdir)/support
	$(CHMOD) 644 $(docdir)/support/*

uninstall:
	$(RMTREE) $(docdir)

clean:
	cd sqlrelay $(AND) $(MAKE) clean
