#! /usr/bin/env perl

# Copyright (c) David Muse
# See the file COPYING for more information.


use SQLRelay::Connection;
use SQLRelay::Cursor;
require "./assert.pl";





# instantiation
$con=SQLRelay::Connection->new("sqlrelay",9000,"/tmp/test.socket",
						"testuser","testpassword",0,1);
$cur=SQLRelay::Cursor->new($con);

# get database type
print("IDENTIFY: \n");
assertEqualString($con->identify(),"firebird");
print("\n");

# ping
print("PING: \n");
assertTrue($con->ping());
print("\n");

# isolation levels
print("ISOLATION LEVELS: \n");
# though firebird does support a "set transaction ..." statement to
# set the isolation level, it looks like, in firebird, you can really
# only set it through the TPB at the start of a transaction, so
# attempts to set it should fail
assertFalse($con->setIsolationLevel("read committed"));
assertEqualString($con->getIsolationLevel(),"read committed");
print("\n");

# clear table
$cur->sendQuery("delete from testtable");
$con->commit();

print("INSERT: \n");
assertTrue($cur->sendQuery("insert into testtable values (1,1,1.1,1.1,1.1,1.1,'01-JAN-2001','01:00:00','testchar1','testvarchar1',NULL,NULL)"));
print("\n");


print("BIND BY POSITION: \n");
$cur->prepareQuery("insert into testtable values (?,?,?,?,?,?,?,?,?,?,?,NULL)");
assertEqual($cur->countBindVariables(),11);
$cur->inputBind("1",2);
$cur->inputBind("2",2);
$cur->inputBind("3",2.2,2,1);
$cur->inputBind("4",2.2,2,1);
$cur->inputBind("5",2.2,2,1);
$cur->inputBind("6",2.2,2,1);
$cur->inputBind("7","01-JAN-2002");
$cur->inputBind("8","02:00:00");
$cur->inputBind("9","testchar2");
$cur->inputBind("10","testvarchar2");
$cur->inputBind("11",undef);
assertTrue($cur->executeQuery());
$cur->clearBinds();
$cur->inputBind("1",3);
$cur->inputBind("2",3);
$cur->inputBind("3",3.3,2,1);
$cur->inputBind("4",3.3,2,1);
$cur->inputBind("5",3.3,2,1);
$cur->inputBind("6",3.3,2,1);
$cur->inputBind("7","01-JAN-2003");
$cur->inputBind("8","03:00:00");
$cur->inputBind("9","testchar3");
$cur->inputBind("10","testvarchar3");
$cur->inputBind("11",undef);
assertTrue($cur->executeQuery());
print("\n");

print("ARRAY OF BINDS BY POSITION: \n");
$cur->clearBinds();
@vars=("1","2","3","4","5","6","7","8","9","10","11");
@vals=(4,4,4.4,4.4,4.4,4.4,"01-JAN-2004","04:00:00",
		"testchar4","testvarchar4",undef);
@precs=(0,0,2,2,2,2,0,0,0,0,0);
@scales=(0,0,1,1,1,1,0,0,0,0,0);
$cur->inputBinds(\@vars,\@vals,\@precs,\@scales);
assertTrue($cur->executeQuery());
print("\n");

print("INSERT: \n");
assertTrue($cur->sendQuery("insert into testtable values (5,5,5.5,5.5,5.5,5.5,'01-JAN-2005','05:00:00','testchar5','testvarchar5',NULL,NULL)"));
assertTrue($cur->sendQuery("insert into testtable values (6,6,6.6,6.6,6.6,6.6,'01-JAN-2006','06:00:00','testchar6','testvarchar6',NULL,NULL)"));
assertTrue($cur->sendQuery("insert into testtable values (7,7,7.7,7.7,7.7,7.7,'01-JAN-2007','07:00:00','testchar7','testvarchar7',NULL,NULL)"));
assertTrue($cur->sendQuery("insert into testtable values (8,8,8.8,8.8,8.8,8.8,'01-JAN-2008','08:00:00','testchar8','testvarchar8',NULL,NULL)"));
print("\n");

print("AFFECTED ROWS: \n");
assertEqual($cur->affectedRows(),0);
print("\n");

print("STORED PROCEDURE: \n");
$cur->prepareQuery("select * from testproc(?,?,?,NULL)");
$cur->inputBind("1",1);
$cur->inputBind("2",1.1,2,1);
$cur->inputBind("3","hello");
assertTrue($cur->executeQuery());
assertEqual($cur->getField(0,0),"1");
assertEqual($cur->getField(0,1),"1.1000");
assertEqual($cur->getField(0,2),"hello");
$cur->prepareQuery("execute procedure testproc ?, ?, ?, NULL");
$cur->inputBind("1",1);
$cur->inputBind("2",1.1,2,1);
$cur->inputBind("3","hello");
$cur->defineOutputBindInteger("1");
$cur->defineOutputBindDouble("2");
$cur->defineOutputBindString("3",20);
$cur->defineOutputBindBlob("4");
assertTrue($cur->executeQuery());
$numvar=$cur->getOutputBindInteger("1");
$floatvar=$cur->getOutputBindDouble("2");
$stringvar=$cur->getOutputBindString("3");
assertEqual($numvar,1);
#assertEqual($floatvar,1.1);
assertEqual($stringvar,"hello               ");
print("\n");

print("SELECT: \n");
assertTrue($cur->sendQuery("select * from testtable order by testinteger"));
print("\n");

print("COLUMN COUNT: \n");
assertEqual($cur->colCount(),12);
print("\n");

print("COLUMN NAMES: \n");
assertEqualString($cur->getColumnName(0),"TESTINTEGER");
assertEqualString($cur->getColumnName(1),"TESTSMALLINT");
assertEqualString($cur->getColumnName(2),"TESTDECIMAL");
assertEqualString($cur->getColumnName(3),"TESTNUMERIC");
assertEqualString($cur->getColumnName(4),"TESTFLOAT");
assertEqualString($cur->getColumnName(5),"TESTDOUBLE");
assertEqualString($cur->getColumnName(6),"TESTDATE");
assertEqualString($cur->getColumnName(7),"TESTTIME");
assertEqualString($cur->getColumnName(8),"TESTCHAR");
assertEqualString($cur->getColumnName(9),"TESTVARCHAR");
assertEqualString($cur->getColumnName(10),"TESTTIMESTAMP");
@cols=$cur->getColumnNames();
assertEqualString($cols[0],"TESTINTEGER");
assertEqualString($cols[1],"TESTSMALLINT");
assertEqualString($cols[2],"TESTDECIMAL");
assertEqualString($cols[3],"TESTNUMERIC");
assertEqualString($cols[4],"TESTFLOAT");
assertEqualString($cols[5],"TESTDOUBLE");
assertEqualString($cols[6],"TESTDATE");
assertEqualString($cols[7],"TESTTIME");
assertEqualString($cols[8],"TESTCHAR");
assertEqualString($cols[9],"TESTVARCHAR");
assertEqualString($cols[10],"TESTTIMESTAMP");
print("\n");

print("COLUMN TYPES: \n");
assertEqualString($cur->getColumnType(0),"INTEGER");
assertEqualString($cur->getColumnType('TESTINTEGER'),"INTEGER");
assertEqualString($cur->getColumnType(1),"SMALLINT");
assertEqualString($cur->getColumnType('TESTSMALLINT'),"SMALLINT");
assertEqualString($cur->getColumnType(2),"DECIMAL");
assertEqualString($cur->getColumnType('TESTDECIMAL'),"DECIMAL");
assertEqualString($cur->getColumnType(3),"NUMERIC");
assertEqualString($cur->getColumnType('TESTNUMERIC'),"NUMERIC");
assertEqualString($cur->getColumnType(4),"FLOAT");
assertEqualString($cur->getColumnType('TESTFLOAT'),"FLOAT");
assertEqualString($cur->getColumnType(5),"DOUBLE PRECISION");
assertEqualString($cur->getColumnType('TESTDOUBLE'),"DOUBLE PRECISION");
assertEqualString($cur->getColumnType(6),"DATE");
assertEqualString($cur->getColumnType('TESTDATE'),"DATE");
assertEqualString($cur->getColumnType(7),"TIME");
assertEqualString($cur->getColumnType('TESTTIME'),"TIME");
assertEqualString($cur->getColumnType(8),"CHAR");
assertEqualString($cur->getColumnType('TESTCHAR'),"CHAR");
assertEqualString($cur->getColumnType(9),"VARCHAR");
assertEqualString($cur->getColumnType('TESTVARCHAR'),"VARCHAR");
assertEqualString($cur->getColumnType(10),"TIMESTAMP");
assertEqualString($cur->getColumnType('TESTTIMESTAMP'),"TIMESTAMP");
print("\n");

print("COLUMN LENGTH: \n");
assertEqual($cur->getColumnLength(0),4);
assertEqual($cur->getColumnLength('TESTINTEGER'),4);
assertEqual($cur->getColumnLength(1),2);
assertEqual($cur->getColumnLength('TESTSMALLINT'),2);
assertEqual($cur->getColumnLength(2),8);
assertEqual($cur->getColumnLength('TESTDECIMAL'),8);
assertEqual($cur->getColumnLength(3),8);
assertEqual($cur->getColumnLength('TESTNUMERIC'),8);
assertEqual($cur->getColumnLength(4),4);
assertEqual($cur->getColumnLength('TESTFLOAT'),4);
assertEqual($cur->getColumnLength(5),8);
assertEqual($cur->getColumnLength('TESTDOUBLE'),8);
assertEqual($cur->getColumnLength(6),4);
assertEqual($cur->getColumnLength('TESTDATE'),4);
assertEqual($cur->getColumnLength(7),4);
assertEqual($cur->getColumnLength('TESTTIME'),4);
assertEqual($cur->getColumnLength(8),50);
assertEqual($cur->getColumnLength('TESTCHAR'),50);
assertEqual($cur->getColumnLength(9),50);
assertEqual($cur->getColumnLength('TESTVARCHAR'),50);
assertEqual($cur->getColumnLength(10),8);
assertEqual($cur->getColumnLength('TESTTIMESTAMP'),8);
print("\n");

print("LONGEST COLUMN: \n");
assertEqual($cur->getLongest(0),1);
assertEqual($cur->getLongest('TESTINTEGER'),1);
assertEqual($cur->getLongest(1),1);
assertEqual($cur->getLongest('TESTSMALLINT'),1);
assertEqual($cur->getLongest(2),4);
assertEqual($cur->getLongest('TESTDECIMAL'),4);
assertEqual($cur->getLongest(3),4);
assertEqual($cur->getLongest('TESTNUMERIC'),4);
assertEqual($cur->getLongest(4),6);
assertEqual($cur->getLongest('TESTFLOAT'),6);
assertEqual($cur->getLongest(5),6);
assertEqual($cur->getLongest('TESTDOUBLE'),6);
assertEqual($cur->getLongest(6),10);
assertEqual($cur->getLongest('TESTDATE'),10);
assertEqual($cur->getLongest(7),8);
assertEqual($cur->getLongest('TESTTIME'),8);
assertEqual($cur->getLongest(8),50);
assertEqual($cur->getLongest('TESTCHAR'),50);
assertEqual($cur->getLongest(9),12);
assertEqual($cur->getLongest('TESTVARCHAR'),12);
assertEqual($cur->getLongest(10),0);
assertEqual($cur->getLongest('TESTTIMESTAMP'),0);
print("\n");

print("ROW COUNT: \n");
assertEqual($cur->rowCount(),8);
print("\n");

print("TOTAL ROWS: \n");
assertEqual($cur->totalRows(),0);
print("\n");

print("FIRST ROW INDEX: \n");
assertEqual($cur->firstRowIndex(),0);
print("\n");

print("END OF RESULT SET: \n");
assertTrue($cur->endOfResultSet());
print("\n");

print("FIELDS BY INDEX: \n");
assertEqualString($cur->getField(0,0),"1");
assertEqualString($cur->getField(0,1),"1");
assertEqualString($cur->getField(0,2),"1.10");
assertEqualString($cur->getField(0,3),"1.10");
assertEqualString($cur->getField(0,4),"1.1000");
assertEqualString($cur->getField(0,5),"1.1000");
assertEqualString($cur->getField(0,6),"2001:01:01");
assertEqualString($cur->getField(0,7),"01:00:00");
assertEqualString($cur->getField(0,8),"testchar1                                         ");
assertEqualString($cur->getField(0,9),"testvarchar1");
print("\n");
assertEqualString($cur->getField(7,0),"8");
assertEqualString($cur->getField(7,1),"8");
assertEqualString($cur->getField(7,2),"8.80");
assertEqualString($cur->getField(7,3),"8.80");
assertEqualString($cur->getField(7,4),"8.8000");
assertEqualString($cur->getField(7,5),"8.8000");
assertEqualString($cur->getField(7,6),"2008:01:01");
assertEqualString($cur->getField(7,7),"08:00:00");
assertEqualString($cur->getField(7,8),"testchar8                                         ");
assertEqualString($cur->getField(7,9),"testvarchar8");
print("\n");

print("FIELD LENGTHS BY INDEX: \n");
assertEqual($cur->getFieldLength(0,0),1);
assertEqual($cur->getFieldLength(0,1),1);
assertEqual($cur->getFieldLength(0,2),4);
assertEqual($cur->getFieldLength(0,3),4);
assertEqual($cur->getFieldLength(0,4),6);
assertEqual($cur->getFieldLength(0,5),6);
assertEqual($cur->getFieldLength(0,6),10);
assertEqual($cur->getFieldLength(0,7),8);
assertEqual($cur->getFieldLength(0,8),50);
assertEqual($cur->getFieldLength(0,9),12);
print("\n");
assertEqual($cur->getFieldLength(7,0),1);
assertEqual($cur->getFieldLength(7,1),1);
assertEqual($cur->getFieldLength(7,2),4);
assertEqual($cur->getFieldLength(7,3),4);
assertEqual($cur->getFieldLength(7,4),6);
assertEqual($cur->getFieldLength(7,5),6);
assertEqual($cur->getFieldLength(7,6),10);
assertEqual($cur->getFieldLength(7,7),8);
assertEqual($cur->getFieldLength(7,8),50);
assertEqual($cur->getFieldLength(7,9),12);
print("\n");

print("FIELDS BY NAME: \n");
assertEqualString($cur->getField(0,"TESTINTEGER"),"1");
assertEqualString($cur->getField(0,"TESTSMALLINT"),"1");
assertEqualString($cur->getField(0,"TESTDECIMAL"),"1.10");
assertEqualString($cur->getField(0,"TESTNUMERIC"),"1.10");
assertEqualString($cur->getField(0,"TESTFLOAT"),"1.1000");
assertEqualString($cur->getField(0,"TESTDOUBLE"),"1.1000");
assertEqualString($cur->getField(0,"TESTDATE"),"2001:01:01");
assertEqualString($cur->getField(0,"TESTTIME"),"01:00:00");
assertEqualString($cur->getField(0,"TESTCHAR"),"testchar1                                         ");
assertEqualString($cur->getField(0,"TESTVARCHAR"),"testvarchar1");
print("\n");
assertEqualString($cur->getField(7,"TESTINTEGER"),"8");
assertEqualString($cur->getField(7,"TESTSMALLINT"),"8");
assertEqualString($cur->getField(7,"TESTDECIMAL"),"8.80");
assertEqualString($cur->getField(7,"TESTNUMERIC"),"8.80");
assertEqualString($cur->getField(7,"TESTFLOAT"),"8.8000");
assertEqualString($cur->getField(7,"TESTDOUBLE"),"8.8000");
assertEqualString($cur->getField(7,"TESTDATE"),"2008:01:01");
assertEqualString($cur->getField(7,"TESTTIME"),"08:00:00");
assertEqualString($cur->getField(7,"TESTCHAR"),"testchar8                                         ");
assertEqualString($cur->getField(7,"TESTVARCHAR"),"testvarchar8");
print("\n");

print("FIELD LENGTHS BY NAME: \n");
assertEqual($cur->getFieldLength(0,"TESTINTEGER"),1);
assertEqual($cur->getFieldLength(0,"TESTSMALLINT"),1);
assertEqual($cur->getFieldLength(0,"TESTDECIMAL"),4);
assertEqual($cur->getFieldLength(0,"TESTNUMERIC"),4);
assertEqual($cur->getFieldLength(0,"TESTFLOAT"),6);
assertEqual($cur->getFieldLength(0,"TESTDOUBLE"),6);
assertEqual($cur->getFieldLength(0,"TESTDATE"),10);
assertEqual($cur->getFieldLength(0,"TESTTIME"),8);
assertEqual($cur->getFieldLength(0,"TESTCHAR"),50);
assertEqual($cur->getFieldLength(0,"TESTVARCHAR"),12);
print("\n");
assertEqual($cur->getFieldLength(7,"TESTINTEGER"),1);
assertEqual($cur->getFieldLength(7,"TESTSMALLINT"),1);
assertEqual($cur->getFieldLength(7,"TESTDECIMAL"),4);
assertEqual($cur->getFieldLength(7,"TESTNUMERIC"),4);
assertEqual($cur->getFieldLength(7,"TESTFLOAT"),6);
assertEqual($cur->getFieldLength(7,"TESTDOUBLE"),6);
assertEqual($cur->getFieldLength(7,"TESTDATE"),10);
assertEqual($cur->getFieldLength(7,"TESTTIME"),8);
assertEqual($cur->getFieldLength(7,"TESTCHAR"),50);
assertEqual($cur->getFieldLength(7,"TESTVARCHAR"),12);
print("\n");

print("FIELDS BY ARRAY: \n");
@fields=$cur->getRow(0);
assertEqual($fields[0],1);
assertEqual($fields[1],1);
assertEqual($fields[2],1.1);
assertEqual($fields[3],1.1);
assertEqual($fields[4],1.1);
assertEqual($fields[5],1.1);
assertEqualString($fields[6],"2001:01:01");
assertEqualString($fields[7],"01:00:00");
assertEqualString($fields[8],"testchar1                                         ");
assertEqualString($fields[9],"testvarchar1");
print("\n");

print("FIELD LENGTHS BY ARRAY: \n");
@fieldlens=$cur->getRowLengths(0);
assertEqual($fieldlens[0],1);
assertEqual($fieldlens[1],1);
assertEqual($fieldlens[2],4);
assertEqual($fieldlens[3],4);
assertEqual($fieldlens[4],6);
assertEqual($fieldlens[5],6);
assertEqual($fieldlens[6],10);
assertEqual($fieldlens[7],8);
assertEqual($fieldlens[8],50);
assertEqual($fieldlens[9],12);
print("\n");

print("FIELDS BY HASH: \n");
%fields=$cur->getRowHash(0);
assertEqual($fields{"TESTINTEGER"},1);
assertEqual($fields{"TESTSMALLINT"},1);
assertEqual($fields{"TESTDECIMAL"},1.1);
assertEqual($fields{"TESTNUMERIC"},1.1);
assertEqual($fields{"TESTFLOAT"},1.1);
assertEqual($fields{"TESTDOUBLE"},1.1);
assertEqualString($fields{"TESTDATE"},"2001:01:01");
assertEqualString($fields{"TESTTIME"},"01:00:00");
assertEqualString($fields{"TESTCHAR"},"testchar1                                         ");
assertEqualString($fields{"TESTVARCHAR"},"testvarchar1");
print("\n");
%fields=$cur->getRowHash(7);
assertEqual($fields{"TESTINTEGER"},8);
assertEqual($fields{"TESTSMALLINT"},8);
assertEqual($fields{"TESTDECIMAL"},8.8);
assertEqual($fields{"TESTNUMERIC"},8.8);
assertEqual($fields{"TESTFLOAT"},8.8);
assertEqual($fields{"TESTDOUBLE"},8.8);
assertEqualString($fields{"TESTDATE"},"2008:01:01");
assertEqualString($fields{"TESTTIME"},"08:00:00");
assertEqualString($fields{"TESTCHAR"},"testchar8                                         ");
assertEqualString($fields{"TESTVARCHAR"},"testvarchar8");
print("\n");

print("FIELD LENGTHS BY HASH: \n");
%fieldlengths=$cur->getRowLengthsHash(0);
assertEqual($fieldlengths{"TESTINTEGER"},1);
assertEqual($fieldlengths{"TESTSMALLINT"},1);
assertEqual($fieldlengths{"TESTDECIMAL"},4);
assertEqual($fieldlengths{"TESTNUMERIC"},4);
assertEqual($fieldlengths{"TESTFLOAT"},6);
assertEqual($fieldlengths{"TESTDOUBLE"},6);
assertEqual($fieldlengths{"TESTDATE"},10);
assertEqual($fieldlengths{"TESTTIME"},8);
assertEqual($fieldlengths{"TESTCHAR"},50);
assertEqual($fieldlengths{"TESTVARCHAR"},12);
print("\n");
%fieldlengths=$cur->getRowLengthsHash(7);
assertEqual($fieldlengths{"TESTINTEGER"},1);
assertEqual($fieldlengths{"TESTSMALLINT"},1);
assertEqual($fieldlengths{"TESTDECIMAL"},4);
assertEqual($fieldlengths{"TESTNUMERIC"},4);
assertEqual($fieldlengths{"TESTFLOAT"},6);
assertEqual($fieldlengths{"TESTDOUBLE"},6);
assertEqual($fieldlengths{"TESTDATE"},10);
assertEqual($fieldlengths{"TESTTIME"},8);
assertEqual($fieldlengths{"TESTCHAR"},50);
assertEqual($fieldlengths{"TESTVARCHAR"},12);
print("\n");

print("INDIVIDUAL SUBSTITUTIONS: \n");
$cur->prepareQuery("select \$(var1),'\$(var2)','\$(var3)' from rdb\$database");
$cur->substitution("var1",1);
$cur->substitution("var2","hello");
$cur->substitution("var3",10.5556,6,4);
assertTrue($cur->executeQuery());
print("\n");

print("FIELDS: \n");
assertEqualString($cur->getField(0,0),"1");
assertEqualString($cur->getField(0,1),"hello");
assertEqualString($cur->getField(0,2),"10.5556");
print("\n");

print("ARRAY SUBSTITUTIONS: \n");
$cur->prepareQuery("select \$(var1),'\$(var2)','\$(var3)' from rdb\$database");
@vars=("var1","var2","var3");
@vals=(1,"hello",10.5556);
@precs=(0,0,6);
@scales=(0,0,4);
$cur->substitutions(\@vars,\@vals,\@precs,\@scales);
assertTrue($cur->executeQuery());
print("\n");

print("FIELDS: \n");
assertEqualString($cur->getField(0,0),"1");
assertEqualString($cur->getField(0,1),"hello");
assertEqualString($cur->getField(0,2),"10.5556");
print("\n");

print("NULLS as Undef: \n");
$cur->getNullsAsUndefined();
assertTrue($cur->sendQuery("select 1,NULL,NULL from rdb\$database"));
assertEqualString($cur->getField(0,0),"1");
assertUndef($cur->getField(0,1));
assertUndef($cur->getField(0,2));
$cur->getNullsAsEmptyStrings();
assertTrue($cur->sendQuery("select 1,NULL,NULL from rdb\$database"));
assertEqualString($cur->getField(0,0),"1");
assertEqualString($cur->getField(0,1),"");
assertEqualString($cur->getField(0,2),"");
$cur->getNullsAsUndefined();
print("\n");

print("RESULT SET BUFFER SIZE: \n");
assertEqual($cur->getResultSetBufferSize(),0);
$cur->setResultSetBufferSize(2);
assertTrue($cur->sendQuery("select * from testtable order by testinteger"));
assertEqual($cur->getResultSetBufferSize(),2);
print("\n");
assertEqual($cur->firstRowIndex(),0);
assertFalse($cur->endOfResultSet());
assertEqual($cur->rowCount(),2);
assertEqualString($cur->getField(0,0),"1");
assertEqualString($cur->getField(1,0),"2");
assertEqualString($cur->getField(2,0),"3");
print("\n");
assertEqual($cur->firstRowIndex(),2);
assertFalse($cur->endOfResultSet());
assertEqual($cur->rowCount(),4);
assertEqualString($cur->getField(6,0),"7");
assertEqualString($cur->getField(7,0),"8");
print("\n");
assertEqual($cur->firstRowIndex(),6);
assertFalse($cur->endOfResultSet());
assertEqual($cur->rowCount(),8);
assertUndef($cur->getField(8,0));
print("\n");
assertEqual($cur->firstRowIndex(),8);
assertTrue($cur->endOfResultSet());
assertEqual($cur->rowCount(),8);
print("\n");

print("DONT GET COLUMN INFO: \n");
$cur->dontGetColumnInfo();
assertTrue($cur->sendQuery("select * from testtable order by testinteger"));
assertUndef($cur->getColumnName(0));
assertEqual($cur->getColumnLength(0),0);
assertUndef($cur->getColumnType(0));
$cur->getColumnInfo();
assertTrue($cur->sendQuery("select * from testtable order by testinteger"));
assertEqualString($cur->getColumnName(0),"TESTINTEGER");
assertEqual($cur->getColumnLength(0),4);
assertEqualString($cur->getColumnType(0),"INTEGER");
print("\n");

print("SUSPENDED SESSION: \n");
assertTrue($cur->sendQuery("select * from testtable order by testinteger"));
$cur->suspendResultSet();
assertTrue($con->suspendSession());
$port=$con->getConnectionPort();
$socket=$con->getConnectionSocket();
assertTrue($con->resumeSession($port,$socket));
print("\n");
assertEqualString($cur->getField(0,0),"1");
assertEqualString($cur->getField(1,0),"2");
assertEqualString($cur->getField(2,0),"3");
assertEqualString($cur->getField(3,0),"4");
assertEqualString($cur->getField(4,0),"5");
assertEqualString($cur->getField(5,0),"6");
assertEqualString($cur->getField(6,0),"7");
assertEqualString($cur->getField(7,0),"8");
print("\n");
assertTrue($cur->sendQuery("select * from testtable order by testinteger"));
$cur->suspendResultSet();
assertTrue($con->suspendSession());
$port=$con->getConnectionPort();
$socket=$con->getConnectionSocket();
assertTrue($con->resumeSession($port,$socket));
print("\n");
assertEqualString($cur->getField(0,0),"1");
assertEqualString($cur->getField(1,0),"2");
assertEqualString($cur->getField(2,0),"3");
assertEqualString($cur->getField(3,0),"4");
assertEqualString($cur->getField(4,0),"5");
assertEqualString($cur->getField(5,0),"6");
assertEqualString($cur->getField(6,0),"7");
assertEqualString($cur->getField(7,0),"8");
print("\n");
assertTrue($cur->sendQuery("select * from testtable order by testinteger"));
$cur->suspendResultSet();
assertTrue($con->suspendSession());
$port=$con->getConnectionPort();
$socket=$con->getConnectionSocket();
assertTrue($con->resumeSession($port,$socket));
print("\n");
assertEqualString($cur->getField(0,0),"1");
assertEqualString($cur->getField(1,0),"2");
assertEqualString($cur->getField(2,0),"3");
assertEqualString($cur->getField(3,0),"4");
assertEqualString($cur->getField(4,0),"5");
assertEqualString($cur->getField(5,0),"6");
assertEqualString($cur->getField(6,0),"7");
assertEqualString($cur->getField(7,0),"8");
print("\n");

print("SUSPENDED RESULT SET: \n");
$cur->setResultSetBufferSize(2);
assertTrue($cur->sendQuery("select * from testtable order by testinteger"));
assertEqualString($cur->getField(2,0),"3");
$id=$cur->getResultSetId();
$cur->suspendResultSet();
assertTrue($con->suspendSession());
$port=$con->getConnectionPort();
$socket=$con->getConnectionSocket();
assertTrue($con->resumeSession($port,$socket));
assertTrue($cur->resumeResultSet($id));
print("\n");
assertEqual($cur->firstRowIndex(),4);
assertFalse($cur->endOfResultSet());
assertEqual($cur->rowCount(),6);
assertEqualString($cur->getField(7,0),"8");
print("\n");
assertEqual($cur->firstRowIndex(),6);
assertFalse($cur->endOfResultSet());
assertEqual($cur->rowCount(),8);
assertUndef($cur->getField(8,0));
print("\n");
assertEqual($cur->firstRowIndex(),8);
assertTrue($cur->endOfResultSet());
assertEqual($cur->rowCount(),8);
$cur->setResultSetBufferSize(0);
print("\n");

print("CACHED RESULT SET: \n");
$cur->cacheToFile("cachefile1");
$cur->setCacheTtl(200);
assertTrue($cur->sendQuery("select * from testtable order by testinteger"));
$filename=$cur->getCacheFileName();
assertEqualString($filename,"cachefile1");
$cur->cacheOff();
assertTrue($cur->openCachedResultSet($filename));
assertEqualString($cur->getField(7,0),"8");
print("\n");

print("COLUMN COUNT FOR CACHED RESULT SET: \n");
assertEqual($cur->colCount(),12);
print("\n");

print("COLUMN NAMES FOR CACHED RESULT SET: \n");
assertEqualString($cur->getColumnName(0),"TESTINTEGER");
assertEqualString($cur->getColumnName(1),"TESTSMALLINT");
assertEqualString($cur->getColumnName(2),"TESTDECIMAL");
assertEqualString($cur->getColumnName(3),"TESTNUMERIC");
assertEqualString($cur->getColumnName(4),"TESTFLOAT");
assertEqualString($cur->getColumnName(5),"TESTDOUBLE");
assertEqualString($cur->getColumnName(6),"TESTDATE");
assertEqualString($cur->getColumnName(7),"TESTTIME");
assertEqualString($cur->getColumnName(8),"TESTCHAR");
assertEqualString($cur->getColumnName(9),"TESTVARCHAR");
assertEqualString($cur->getColumnName(10),"TESTTIMESTAMP");
@cols=$cur->getColumnNames();
assertEqualString($cols[0],"TESTINTEGER");
assertEqualString($cols[1],"TESTSMALLINT");
assertEqualString($cols[2],"TESTDECIMAL");
assertEqualString($cols[3],"TESTNUMERIC");
assertEqualString($cols[4],"TESTFLOAT");
assertEqualString($cols[5],"TESTDOUBLE");
assertEqualString($cols[6],"TESTDATE");
assertEqualString($cols[7],"TESTTIME");
assertEqualString($cols[8],"TESTCHAR");
assertEqualString($cols[9],"TESTVARCHAR");
assertEqualString($cols[10],"TESTTIMESTAMP");
print("\n");

print("CACHED RESULT SET WITH RESULT SET BUFFER SIZE: \n");
$cur->setResultSetBufferSize(2);
$cur->cacheToFile("cachefile1");
$cur->setCacheTtl(200);
assertTrue($cur->sendQuery("select * from testtable order by testinteger"));
$filename=$cur->getCacheFileName();
assertEqualString($filename,"cachefile1");
$cur->cacheOff();
assertTrue($cur->openCachedResultSet($filename));
assertEqualString($cur->getField(7,0),"8");
assertUndef($cur->getField(8,0));
$cur->setResultSetBufferSize(0);
print("\n");

print("FROM ONE CACHE FILE TO ANOTHER: \n");
$cur->cacheToFile("cachefile2");
assertTrue($cur->openCachedResultSet("cachefile1"));
$cur->cacheOff();
assertTrue($cur->openCachedResultSet("cachefile2"));
assertEqualString($cur->getField(7,0),"8");
assertUndef($cur->getField(8,0));
print("\n");

print("FROM ONE CACHE FILE TO ANOTHER WITH RESULT SET BUFFER SIZE: \n");
$cur->setResultSetBufferSize(2);
$cur->cacheToFile("cachefile2");
assertTrue($cur->openCachedResultSet("cachefile1"));
$cur->cacheOff();
assertTrue($cur->openCachedResultSet("cachefile2"));
assertEqualString($cur->getField(7,0),"8");
assertUndef($cur->getField(8,0));
$cur->setResultSetBufferSize(0);
print("\n");

print("CACHED RESULT SET WITH SUSPEND AND RESULT SET BUFFER SIZE: \n");
$cur->setResultSetBufferSize(2);
$cur->cacheToFile("cachefile1");
$cur->setCacheTtl(200);
assertTrue($cur->sendQuery("select * from testtable order by testinteger"));
assertEqualString($cur->getField(2,0),"3");
$filename=$cur->getCacheFileName();
assertEqualString($filename,"cachefile1");
$id=$cur->getResultSetId();
$cur->suspendResultSet();
assertTrue($con->suspendSession());
$port=$con->getConnectionPort();
$socket=$con->getConnectionSocket();
print("\n");
assertTrue($con->resumeSession($port,$socket));
assertTrue($cur->resumeCachedResultSet($id,$filename));
print("\n");
assertEqual($cur->firstRowIndex(),4);
assertFalse($cur->endOfResultSet());
assertEqual($cur->rowCount(),6);
assertEqualString($cur->getField(7,0),"8");
print("\n");
assertEqual($cur->firstRowIndex(),6);
assertFalse($cur->endOfResultSet());
assertEqual($cur->rowCount(),8);
assertUndef($cur->getField(8,0));
print("\n");
assertEqual($cur->firstRowIndex(),8);
assertTrue($cur->endOfResultSet());
assertEqual($cur->rowCount(),8);
$cur->cacheOff();
print("\n");
assertTrue($cur->openCachedResultSet($filename));
assertEqualString($cur->getField(7,0),"8");
assertUndef($cur->getField(8,0));
$cur->setResultSetBufferSize(0);
print("\n");

#print("COMMIT AND ROLLBACK: \n");
$secondcon=SQLRelay::Connection->new("sqlrelay",9000,"/tmp/test.socket",
						"testuser","testpassword",0,1);
$secondcur=SQLRelay::Cursor->new($secondcon);
assertTrue($secondcur->sendQuery("select count(*) from testtable"));
assertEqualString($secondcur->getField(0,0),"0");
assertTrue($con->commit());
assertTrue($secondcur->sendQuery("select count(*) from testtable"));
assertEqualString($secondcur->getField(0,0),"8");
assertTrue($con->autoCommitOn());
assertTrue($cur->sendQuery("insert into testtable values (10,10,10.1,10.1,10.1,10.1,'01-JAN-2010','10:00:00','testchar10','testvarchar10',NULL,NULL)"));
assertTrue($secondcur->sendQuery("select count(*) from testtable"));
assertEqualString($secondcur->getField(0,0),"9");
assertTrue($con->autoCommitOff());
print("\n");

print("FINISHED SUSPENDED SESSION: \n");
assertTrue($cur->sendQuery("select * from testtable order by testinteger"));
assertEqualString($cur->getField(4,0),"5");
assertEqualString($cur->getField(5,0),"6");
assertEqualString($cur->getField(6,0),"7");
assertEqualString($cur->getField(7,0),"8");
$id=$cur->getResultSetId();
$cur->suspendResultSet();
assertTrue($con->suspendSession());
$port=$con->getConnectionPort();
$socket=$con->getConnectionSocket();
assertTrue($con->resumeSession($port,$socket));
assertTrue($cur->resumeResultSet($id));
assertUndef($cur->getField(4,0));
assertUndef($cur->getField(5,0));
assertUndef($cur->getField(6,0));
assertUndef($cur->getField(7,0));
print("\n");

# drop existing table
$con->commit();
$cur->sendQuery("delete from testtable");
$con->commit();
print("\n");

# invalid queries...
print("INVALID QUERIES: \n");
assertFalse($cur->sendQuery("select * from testtable1 order by testinteger"));
assertFalse($cur->sendQuery("select * from testtable1 order by testinteger"));
assertFalse($cur->sendQuery("select * from testtable1 order by testinteger"));
assertFalse($cur->sendQuery("select * from testtable1 order by testinteger"));
print("\n");
assertFalse($cur->sendQuery("insert into testtable1 values (1,2,3,4)"));
assertFalse($cur->sendQuery("insert into testtable1 values (1,2,3,4)"));
assertFalse($cur->sendQuery("insert into testtable1 values (1,2,3,4)"));
assertFalse($cur->sendQuery("insert into testtable1 values (1,2,3,4)"));
print("\n");
assertFalse($cur->sendQuery("create table testtable"));
assertFalse($cur->sendQuery("create table testtable"));
assertFalse($cur->sendQuery("create table testtable"));
assertFalse($cur->sendQuery("create table testtable"));
print("\n");

exit(0);
