#! /usr/bin/env python

# Copyright (c) David Muse
# See the file COPYING for more information.

from SQLRelay import PySQLRClient
from decimal import *
import sys
from asserts import *
import string


def main():

	PySQLRClient.getNumericFieldsAsNumbers()

	# instantiation
	con=PySQLRClient.sqlrconnection("sqlrelay",9000,"/tmp/test.socket",
								"testuser","testpassword")
	cur=PySQLRClient.sqlrcursor(con)

	# get database type


	# identify
	print("IDENTIFY: ")
	assertEqual(con.identify(),"firebird")
	print()


	# ping
	print("PING: ")
	assertTrue(con.ping())
	print()


	# isolation levels
	print("ISOLATION LEVELS: ")
	# though firebird does support a "set transaction ..." statement to
	# set the isolation level, it looks like, in firebird, you can really
	# only set it through the TPB at the start of a transaction, so
	# attempts to set it should fail
	assertFalse(con.setIsolationLevel("read committed"))
	assertEqual(con.getIsolationLevel(),"read committed")
	print()

	# clear table
	cur.sendQuery("delete from testtable")
	con.commit()


	# insert
	print("INSERT: ")
	assertTrue(cur.sendQuery("insert into testtable values (1,1,1.1,1.1,1.1,1.1,'01-JAN-2001','01:00:00','testchar1','testvarchar1',NULL,NULL)"))
	print()


	# bind by position
	print("BIND BY POSITION: ")
	cur.prepareQuery("insert into testtable values (?,?,?,?,?,?,?,?,?,?,?,NULL)")
	assertEqual(cur.countBindVariables(),11)
	cur.inputBind("1",2)
	cur.inputBind("2",2)
	cur.inputBind("3",2.2,2,1)
	cur.inputBind("4",2.2,2,1)
	cur.inputBind("5",2.2,2,1)
	cur.inputBind("6",2.2,2,1)
	cur.inputBind("7","01-JAN-2002")
	cur.inputBind("8","02:00:00")
	cur.inputBind("9","testchar2")
	cur.inputBind("10","testvarchar2")
	cur.inputBind("11",None)
	assertTrue(cur.executeQuery())
	cur.clearBinds()
	cur.inputBind("1",3)
	cur.inputBind("2",3)
	cur.inputBind("3",3.3,2,1)
	cur.inputBind("4",3.3,2,1)
	cur.inputBind("5",3.3,2,1)
	cur.inputBind("6",3.3,2,1)
	cur.inputBind("7","01-JAN-2003")
	cur.inputBind("8","03:00:00")
	cur.inputBind("9","testchar3")
	cur.inputBind("10","testvarchar3")
	cur.inputBind("11",None)
	assertTrue(cur.executeQuery())
	print()


	# array of binds by position
	print("ARRAY OF BINDS BY POSITION: ")
	cur.clearBinds()
	cur.inputBinds(["1","2","3","4","5","6",
			"7","8","9","10","11"],
		[4,4,4.4,4.4,4.4,4.4,"01-JAN-2004","04:00:00",
			"testchar4","testvarchar4",None],
		[0,0,2,2,2,2,0,0,0,0,0],
		[0,0,1,1,1,1,0,0,0,0,0])
	assertTrue(cur.executeQuery())
	print()


	# insert
	print("INSERT: ")
	assertTrue(cur.sendQuery("insert into testtable values (5,5,5.5,5.5,5.5,5.5,'01-JAN-2005','05:00:00','testchar5','testvarchar5',NULL,NULL)"))
	assertTrue(cur.sendQuery("insert into testtable values (6,6,6.6,6.6,6.6,6.6,'01-JAN-2006','06:00:00','testchar6','testvarchar6',NULL,NULL)"))
	assertTrue(cur.sendQuery("insert into testtable values (7,7,7.7,7.7,7.7,7.7,'01-JAN-2007','07:00:00','testchar7','testvarchar7',NULL,NULL)"))
	assertTrue(cur.sendQuery("insert into testtable values (8,8,8.8,8.8,8.8,8.8,'01-JAN-2008','08:00:00','testchar8','testvarchar8',NULL,NULL)"))
	print()


	# affected rows
	print("AFFECTED ROWS: ")
	assertEqual(cur.affectedRows(),0)
	print()


	# stored procedure
	print("STORED PROCEDURE: ")
	cur.prepareQuery("select * from testproc(?,?,?,NULL)")
	cur.inputBind("1",1)
	cur.inputBind("2",1.1,2,1)
	cur.inputBind("3","hello")
	assertTrue(cur.executeQuery())
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(0,1),Decimal(Decimal("1.1000")))
	assertEqual(cur.getField(0,2),"hello")
	cur.prepareQuery("execute procedure testproc ?, ?, ?, NULL")
	cur.inputBind("1",1)
	cur.inputBind("2",1.1,2,1)
	cur.inputBind("3","hello")
	cur.defineOutputBindInteger("1")
	cur.defineOutputBindDouble("2")
	cur.defineOutputBindString("3",20)
	cur.defineOutputBindBlob("4")
	assertTrue(cur.executeQuery())
	assertEqual(cur.getOutputBindInteger("1"),1)
	#assertEqual(cur.getOutputBindDouble("2"),1.1)
	assertEqual(cur.getOutputBindString("3"),"hello               ")
	print()


	# select
	print("SELECT: ")
	assertTrue(cur.sendQuery("select * from testtable order by testinteger"))
	print()


	# column count
	print("COLUMN COUNT: ")
	assertEqual(cur.colCount(),12)
	print()


	# column names
	print("COLUMN NAMES: ")
	assertEqual(cur.getColumnName(0),"TESTINTEGER")
	assertEqual(cur.getColumnName(1),"TESTSMALLINT")
	assertEqual(cur.getColumnName(2),"TESTDECIMAL")
	assertEqual(cur.getColumnName(3),"TESTNUMERIC")
	assertEqual(cur.getColumnName(4),"TESTFLOAT")
	assertEqual(cur.getColumnName(5),"TESTDOUBLE")
	assertEqual(cur.getColumnName(6),"TESTDATE")
	assertEqual(cur.getColumnName(7),"TESTTIME")
	assertEqual(cur.getColumnName(8),"TESTCHAR")
	assertEqual(cur.getColumnName(9),"TESTVARCHAR")
	assertEqual(cur.getColumnName(10),"TESTTIMESTAMP")
	cols=cur.getColumnNames()
	assertEqual(cols[0],"TESTINTEGER")
	assertEqual(cols[1],"TESTSMALLINT")
	assertEqual(cols[2],"TESTDECIMAL")
	assertEqual(cols[3],"TESTNUMERIC")
	assertEqual(cols[4],"TESTFLOAT")
	assertEqual(cols[5],"TESTDOUBLE")
	assertEqual(cols[6],"TESTDATE")
	assertEqual(cols[7],"TESTTIME")
	assertEqual(cols[8],"TESTCHAR")
	assertEqual(cols[9],"TESTVARCHAR")
	assertEqual(cols[10],"TESTTIMESTAMP")
	print()


	# column types
	print("COLUMN TYPES: ")
	assertEqual(cur.getColumnType(0),"INTEGER")
	assertEqual(cur.getColumnType('TESTINTEGER'),"INTEGER")
	assertEqual(cur.getColumnType(1),"SMALLINT")
	assertEqual(cur.getColumnType('TESTSMALLINT'),"SMALLINT")
	assertEqual(cur.getColumnType(2),"DECIMAL")
	assertEqual(cur.getColumnType('TESTDECIMAL'),"DECIMAL")
	assertEqual(cur.getColumnType(3),"NUMERIC")
	assertEqual(cur.getColumnType('TESTNUMERIC'),"NUMERIC")
	assertEqual(cur.getColumnType(4),"FLOAT")
	assertEqual(cur.getColumnType('TESTFLOAT'),"FLOAT")
	assertEqual(cur.getColumnType(5),"DOUBLE PRECISION")
	assertEqual(cur.getColumnType('TESTDOUBLE'),"DOUBLE PRECISION")
	assertEqual(cur.getColumnType(6),"DATE")
	assertEqual(cur.getColumnType('TESTDATE'),"DATE")
	assertEqual(cur.getColumnType(7),"TIME")
	assertEqual(cur.getColumnType('TESTTIME'),"TIME")
	assertEqual(cur.getColumnType(8),"CHAR")
	assertEqual(cur.getColumnType('TESTCHAR'),"CHAR")
	assertEqual(cur.getColumnType(9),"VARCHAR")
	assertEqual(cur.getColumnType('TESTVARCHAR'),"VARCHAR")
	assertEqual(cur.getColumnType(10),"TIMESTAMP")
	assertEqual(cur.getColumnType('TESTTIMESTAMP'),"TIMESTAMP")
	print()


	# column length
	print("COLUMN LENGTH: ")
	assertEqual(cur.getColumnLength(0),4)
	assertEqual(cur.getColumnLength('TESTINTEGER'),4)
	assertEqual(cur.getColumnLength(1),2)
	assertEqual(cur.getColumnLength('TESTSMALLINT'),2)
	assertEqual(cur.getColumnLength(2),8)
	assertEqual(cur.getColumnLength('TESTDECIMAL'),8)
	assertEqual(cur.getColumnLength(3),8)
	assertEqual(cur.getColumnLength('TESTNUMERIC'),8)
	assertEqual(cur.getColumnLength(4),4)
	assertEqual(cur.getColumnLength('TESTFLOAT'),4)
	assertEqual(cur.getColumnLength(5),8)
	assertEqual(cur.getColumnLength('TESTDOUBLE'),8)
	assertEqual(cur.getColumnLength(6),4)
	assertEqual(cur.getColumnLength('TESTDATE'),4)
	assertEqual(cur.getColumnLength(7),4)
	assertEqual(cur.getColumnLength('TESTTIME'),4)
	assertEqual(cur.getColumnLength(8),50)
	assertEqual(cur.getColumnLength('TESTCHAR'),50)
	assertEqual(cur.getColumnLength(9),50)
	assertEqual(cur.getColumnLength('TESTVARCHAR'),50)
	assertEqual(cur.getColumnLength(10),8)
	assertEqual(cur.getColumnLength('TESTTIMESTAMP'),8)
	print()


	# longest column
	print("LONGEST COLUMN: ")
	assertEqual(cur.getLongest(0),1)
	assertEqual(cur.getLongest('TESTINTEGER'),1)
	assertEqual(cur.getLongest(1),1)
	assertEqual(cur.getLongest('TESTSMALLINT'),1)
	assertEqual(cur.getLongest(2),4)
	assertEqual(cur.getLongest('TESTDECIMAL'),4)
	assertEqual(cur.getLongest(3),4)
	assertEqual(cur.getLongest('TESTNUMERIC'),4)
	assertEqual(cur.getLongest(4),6)
	assertEqual(cur.getLongest('TESTFLOAT'),6)
	assertEqual(cur.getLongest(5),6)
	assertEqual(cur.getLongest('TESTDOUBLE'),6)
	assertEqual(cur.getLongest(6),10)
	assertEqual(cur.getLongest('TESTDATE'),10)
	assertEqual(cur.getLongest(7),8)
	assertEqual(cur.getLongest('TESTTIME'),8)
	assertEqual(cur.getLongest(8),50)
	assertEqual(cur.getLongest('TESTCHAR'),50)
	assertEqual(cur.getLongest(9),12)
	assertEqual(cur.getLongest('TESTVARCHAR'),12)
	assertEqual(cur.getLongest(10),0)
	assertEqual(cur.getLongest('TESTTIMESTAMP'),0)
	print()


	# row count
	print("ROW COUNT: ")
	assertEqual(cur.rowCount(),8)
	print()


	# total rows
	print("TOTAL ROWS: ")
	assertEqual(cur.totalRows(),0)
	print()


	# first row index
	print("FIRST ROW INDEX: ")
	assertEqual(cur.firstRowIndex(),0)
	print()


	# end of result set
	print("END OF RESULT SET: ")
	assertTrue(cur.endOfResultSet())
	print()


	# fields by index
	print("FIELDS BY INDEX: ")
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(0,1),1)
	assertEqual(cur.getField(0,2),Decimal(Decimal("1.10")))
	assertEqual(cur.getField(0,3),Decimal(Decimal("1.10")))
	assertEqual(cur.getField(0,4),Decimal(Decimal("1.1000")))
	assertEqual(cur.getField(0,5),Decimal(Decimal("1.1000")))
	assertEqual(cur.getField(0,6),"2001:01:01")
	assertEqual(cur.getField(0,7),"01:00:00")
	assertEqual(cur.getField(0,8),"testchar1                                         ")
	assertEqual(cur.getField(0,9),"testvarchar1")
	print()
	assertEqual(cur.getField(7,0),8)
	assertEqual(cur.getField(7,1),8)
	assertEqual(cur.getField(7,2),Decimal("8.80"))
	assertEqual(cur.getField(7,3),Decimal("8.80"))
	assertEqual(cur.getField(7,4),Decimal("8.8000"))
	assertEqual(cur.getField(7,5),Decimal("8.8000"))
	assertEqual(cur.getField(7,6),"2008:01:01")
	assertEqual(cur.getField(7,7),"08:00:00")
	assertEqual(cur.getField(7,8),"testchar8                                         ")
	assertEqual(cur.getField(7,9),"testvarchar8")
	print()


	# field lengths by index
	print("FIELD LENGTHS BY INDEX: ")
	assertEqual(cur.getFieldLength(0,0),1)
	assertEqual(cur.getFieldLength(0,1),1)
	assertEqual(cur.getFieldLength(0,2),4)
	assertEqual(cur.getFieldLength(0,3),4)
	assertEqual(cur.getFieldLength(0,4),6)
	assertEqual(cur.getFieldLength(0,5),6)
	assertEqual(cur.getFieldLength(0,6),10)
	assertEqual(cur.getFieldLength(0,7),8)
	assertEqual(cur.getFieldLength(0,8),50)
	assertEqual(cur.getFieldLength(0,9),12)
	print()
	assertEqual(cur.getFieldLength(7,0),1)
	assertEqual(cur.getFieldLength(7,1),1)
	assertEqual(cur.getFieldLength(7,2),4)
	assertEqual(cur.getFieldLength(7,3),4)
	assertEqual(cur.getFieldLength(7,4),6)
	assertEqual(cur.getFieldLength(7,5),6)
	assertEqual(cur.getFieldLength(7,6),10)
	assertEqual(cur.getFieldLength(7,7),8)
	assertEqual(cur.getFieldLength(7,8),50)
	assertEqual(cur.getFieldLength(7,9),12)
	print()


	# fields by name
	print("FIELDS BY NAME: ")
	assertEqual(cur.getField(0,"TESTINTEGER"),1)
	assertEqual(cur.getField(0,"TESTSMALLINT"),1)
	assertEqual(cur.getField(0,"TESTDECIMAL"),Decimal("1.10"))
	assertEqual(cur.getField(0,"TESTNUMERIC"),Decimal("1.10"))
	assertEqual(cur.getField(0,"TESTFLOAT"),Decimal("1.1000"))
	assertEqual(cur.getField(0,"TESTDOUBLE"),Decimal("1.1000"))
	assertEqual(cur.getField(0,"TESTDATE"),"2001:01:01")
	assertEqual(cur.getField(0,"TESTTIME"),"01:00:00")
	assertEqual(cur.getField(0,"TESTCHAR"),"testchar1                                         ")
	assertEqual(cur.getField(0,"TESTVARCHAR"),"testvarchar1")
	print()
	assertEqual(cur.getField(7,"TESTINTEGER"),8)
	assertEqual(cur.getField(7,"TESTSMALLINT"),8)
	assertEqual(cur.getField(7,"TESTDECIMAL"),Decimal("8.80"))
	assertEqual(cur.getField(7,"TESTNUMERIC"),Decimal("8.80"))
	assertEqual(cur.getField(7,"TESTFLOAT"),Decimal("8.8000"))
	assertEqual(cur.getField(7,"TESTDOUBLE"),Decimal("8.8000"))
	assertEqual(cur.getField(7,"TESTDATE"),"2008:01:01")
	assertEqual(cur.getField(7,"TESTTIME"),"08:00:00")
	assertEqual(cur.getField(7,"TESTCHAR"),"testchar8                                         ")
	assertEqual(cur.getField(7,"TESTVARCHAR"),"testvarchar8")
	print()


	# field lengths by name
	print("FIELD LENGTHS BY NAME: ")
	assertEqual(cur.getFieldLength(0,"TESTINTEGER"),1)
	assertEqual(cur.getFieldLength(0,"TESTSMALLINT"),1)
	assertEqual(cur.getFieldLength(0,"TESTDECIMAL"),4)
	assertEqual(cur.getFieldLength(0,"TESTNUMERIC"),4)
	assertEqual(cur.getFieldLength(0,"TESTFLOAT"),6)
	assertEqual(cur.getFieldLength(0,"TESTDOUBLE"),6)
	assertEqual(cur.getFieldLength(0,"TESTDATE"),10)
	assertEqual(cur.getFieldLength(0,"TESTTIME"),8)
	assertEqual(cur.getFieldLength(0,"TESTCHAR"),50)
	assertEqual(cur.getFieldLength(0,"TESTVARCHAR"),12)
	print()
	assertEqual(cur.getFieldLength(7,"TESTINTEGER"),1)
	assertEqual(cur.getFieldLength(7,"TESTSMALLINT"),1)
	assertEqual(cur.getFieldLength(7,"TESTDECIMAL"),4)
	assertEqual(cur.getFieldLength(7,"TESTNUMERIC"),4)
	assertEqual(cur.getFieldLength(7,"TESTFLOAT"),6)
	assertEqual(cur.getFieldLength(7,"TESTDOUBLE"),6)
	assertEqual(cur.getFieldLength(7,"TESTDATE"),10)
	assertEqual(cur.getFieldLength(7,"TESTTIME"),8)
	assertEqual(cur.getFieldLength(7,"TESTCHAR"),50)
	assertEqual(cur.getFieldLength(7,"TESTVARCHAR"),12)
	print()


	# fields by array
	print("FIELDS BY ARRAY: ")
	fields=cur.getRow(0)
	assertEqual(fields[0],1)
	assertEqual(fields[1],1)
	assertEqual(fields[2],Decimal("1.1"))
	assertEqual(fields[3],Decimal("1.1"))
	assertEqual(fields[4],Decimal("1.1"))
	assertEqual(fields[5],Decimal("1.1"))
	assertEqual(fields[6],"2001:01:01")
	assertEqual(fields[7],"01:00:00")
	assertEqual(fields[8],"testchar1                                         ")
	assertEqual(fields[9],"testvarchar1")
	print()


	# field lengths by array
	print("FIELD LENGTHS BY ARRAY: ")
	fieldlens=cur.getRowLengths(0)
	assertEqual(fieldlens[0],1)
	assertEqual(fieldlens[1],1)
	assertEqual(fieldlens[2],4)
	assertEqual(fieldlens[3],4)
	assertEqual(fieldlens[4],6)
	assertEqual(fieldlens[5],6)
	assertEqual(fieldlens[6],10)
	assertEqual(fieldlens[7],8)
	assertEqual(fieldlens[8],50)
	assertEqual(fieldlens[9],12)
	print()


	# fields by dictionary
	print("FIELDS BY DICTIONARY: ")
	fields=cur.getRowDictionary(0)
	assertEqual(fields["TESTINTEGER"],1)
	assertEqual(fields["TESTSMALLINT"],1)
	assertEqual(fields["TESTDECIMAL"],Decimal("1.1"))
	assertEqual(fields["TESTNUMERIC"],Decimal("1.1"))
	assertEqual(fields["TESTFLOAT"],Decimal("1.1"))
	assertEqual(fields["TESTDOUBLE"],Decimal("1.1"))
	assertEqual(fields["TESTDATE"],"2001:01:01")
	assertEqual(fields["TESTTIME"],"01:00:00")
	assertEqual(fields["TESTCHAR"],"testchar1                                         ")
	assertEqual(fields["TESTVARCHAR"],"testvarchar1")
	print()
	fields=cur.getRowDictionary(7)
	assertEqual(fields["TESTINTEGER"],8)
	assertEqual(fields["TESTSMALLINT"],8)
	assertEqual(fields["TESTDECIMAL"],Decimal("8.8"))
	assertEqual(fields["TESTNUMERIC"],Decimal("8.8"))
	assertEqual(fields["TESTFLOAT"],Decimal("8.8"))
	assertEqual(fields["TESTDOUBLE"],Decimal("8.8"))
	assertEqual(fields["TESTDATE"],"2008:01:01")
	assertEqual(fields["TESTTIME"],"08:00:00")
	assertEqual(fields["TESTCHAR"],"testchar8                                         ")
	assertEqual(fields["TESTVARCHAR"],"testvarchar8")
	print()


	# field lengths by dictionary
	print("FIELD LENGTHS BY DICTIONARY: ")
	fieldlengths=cur.getRowLengthsDictionary(0)
	assertEqual(fieldlengths["TESTINTEGER"],1)
	assertEqual(fieldlengths["TESTSMALLINT"],1)
	assertEqual(fieldlengths["TESTDECIMAL"],4)
	assertEqual(fieldlengths["TESTNUMERIC"],4)
	assertEqual(fieldlengths["TESTFLOAT"],6)
	assertEqual(fieldlengths["TESTDOUBLE"],6)
	assertEqual(fieldlengths["TESTDATE"],10)
	assertEqual(fieldlengths["TESTTIME"],8)
	assertEqual(fieldlengths["TESTCHAR"],50)
	assertEqual(fieldlengths["TESTVARCHAR"],12)
	print()
	fieldlengths=cur.getRowLengthsDictionary(7)
	assertEqual(fieldlengths["TESTINTEGER"],1)
	assertEqual(fieldlengths["TESTSMALLINT"],1)
	assertEqual(fieldlengths["TESTDECIMAL"],4)
	assertEqual(fieldlengths["TESTNUMERIC"],4)
	assertEqual(fieldlengths["TESTFLOAT"],6)
	assertEqual(fieldlengths["TESTDOUBLE"],6)
	assertEqual(fieldlengths["TESTDATE"],10)
	assertEqual(fieldlengths["TESTTIME"],8)
	assertEqual(fieldlengths["TESTCHAR"],50)
	assertEqual(fieldlengths["TESTVARCHAR"],12)
	print()


	# individual substitutions
	print("INDIVIDUAL SUBSTITUTIONS: ")
	cur.prepareQuery("select $(var1),'$(var2)','$(var3)' from rdb$database")
	cur.substitution("var1",1)
	cur.substitution("var2","hello")
	cur.substitution("var3",10.5556,6,4)
	assertTrue(cur.executeQuery())
	print()


	# fields
	print("FIELDS: ")
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(0,1),"hello")
	assertEqual(cur.getField(0,2),"10.5556")
	print()


	# array substitutions
	print("ARRAY SUBSTITUTIONS: ")
	cur.prepareQuery("select $(var1),'$(var2)','$(var3)' from rdb$database")
	cur.substitutions(["var1","var2","var3"],
				[1,"hello",10.5556],[0,0,6],[0,0,4])
	assertTrue(cur.executeQuery())
	print()


	# fields
	print("FIELDS: ")
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(0,1),"hello")
	assertEqual(cur.getField(0,2),"10.5556")
	print()


	# nulls as nones
	print("NULLS as Nones: ")
	cur.getNullsAsNone()
	assertTrue(cur.sendQuery("select 1,NULL,NULL from rdb$database"))
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(0,1),None)
	assertEqual(cur.getField(0,2),None)
	cur.getNullsAsEmptyStrings()
	assertTrue(cur.sendQuery("select 1,NULL,NULL from rdb$database"))
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(0,1),"")
	assertEqual(cur.getField(0,2),"")
	cur.getNullsAsNone()
	print()


	# result set buffer size
	print("RESULT SET BUFFER SIZE: ")
	assertEqual(cur.getResultSetBufferSize(),0)
	cur.setResultSetBufferSize(2)
	assertTrue(cur.sendQuery("select * from testtable order by testinteger"))
	assertEqual(cur.getResultSetBufferSize(),2)
	print()
	assertEqual(cur.firstRowIndex(),0)
	assertFalse(cur.endOfResultSet())
	assertEqual(cur.rowCount(),2)
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(1,0),2)
	assertEqual(cur.getField(2,0),3)
	print()
	assertEqual(cur.firstRowIndex(),2)
	assertFalse(cur.endOfResultSet())
	assertEqual(cur.rowCount(),4)
	assertEqual(cur.getField(6,0),7)
	assertEqual(cur.getField(7,0),8)
	print()
	assertEqual(cur.firstRowIndex(),6)
	assertFalse(cur.endOfResultSet())
	assertEqual(cur.rowCount(),8)
	assertEqual(cur.getField(8,0),None)
	print()
	assertEqual(cur.firstRowIndex(),8)
	assertTrue(cur.endOfResultSet())
	assertEqual(cur.rowCount(),8)
	print()


	# dont get column info
	print("DONT GET COLUMN INFO: ")
	cur.dontGetColumnInfo()
	assertTrue(cur.sendQuery("select * from testtable order by testinteger"))
	assertEqual(cur.getColumnName(0),None)
	assertEqual(cur.getColumnLength(0),0)
	assertEqual(cur.getColumnType(0),None)
	cur.getColumnInfo()
	assertTrue(cur.sendQuery("select * from testtable order by testinteger"))
	assertEqual(cur.getColumnName(0),"TESTINTEGER")
	assertEqual(cur.getColumnLength(0),4)
	assertEqual(cur.getColumnType(0),"INTEGER")
	print()


	# suspended session
	print("SUSPENDED SESSION: ")
	assertTrue(cur.sendQuery("select * from testtable order by testinteger"))
	cur.suspendResultSet()
	assertTrue(con.suspendSession())
	port=con.getConnectionPort()
	socket=con.getConnectionSocket()
	assertTrue(con.resumeSession(port,socket))
	print()
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(1,0),2)
	assertEqual(cur.getField(2,0),3)
	assertEqual(cur.getField(3,0),4)
	assertEqual(cur.getField(4,0),5)
	assertEqual(cur.getField(5,0),6)
	assertEqual(cur.getField(6,0),7)
	assertEqual(cur.getField(7,0),8)
	print()
	assertTrue(cur.sendQuery("select * from testtable order by testinteger"))
	cur.suspendResultSet()
	assertTrue(con.suspendSession())
	port=con.getConnectionPort()
	socket=con.getConnectionSocket()
	assertTrue(con.resumeSession(port,socket))
	print()
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(1,0),2)
	assertEqual(cur.getField(2,0),3)
	assertEqual(cur.getField(3,0),4)
	assertEqual(cur.getField(4,0),5)
	assertEqual(cur.getField(5,0),6)
	assertEqual(cur.getField(6,0),7)
	assertEqual(cur.getField(7,0),8)
	print()
	assertTrue(cur.sendQuery("select * from testtable order by testinteger"))
	cur.suspendResultSet()
	assertTrue(con.suspendSession())
	port=con.getConnectionPort()
	socket=con.getConnectionSocket()
	assertTrue(con.resumeSession(port,socket))
	print()
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(1,0),2)
	assertEqual(cur.getField(2,0),3)
	assertEqual(cur.getField(3,0),4)
	assertEqual(cur.getField(4,0),5)
	assertEqual(cur.getField(5,0),6)
	assertEqual(cur.getField(6,0),7)
	assertEqual(cur.getField(7,0),8)
	print()


	# suspended result set
	print("SUSPENDED RESULT SET: ")
	cur.setResultSetBufferSize(2)
	assertTrue(cur.sendQuery("select * from testtable order by testinteger"))
	assertEqual(cur.getField(2,0),3)
	id=cur.getResultSetId()
	cur.suspendResultSet()
	assertTrue(con.suspendSession())
	port=con.getConnectionPort()
	socket=con.getConnectionSocket()
	assertTrue(con.resumeSession(port,socket))
	assertTrue(cur.resumeResultSet(id))
	print()
	assertEqual(cur.firstRowIndex(),4)
	assertFalse(cur.endOfResultSet())
	assertEqual(cur.rowCount(),6)
	assertEqual(cur.getField(7,0),8)
	print()
	assertEqual(cur.firstRowIndex(),6)
	assertFalse(cur.endOfResultSet())
	assertEqual(cur.rowCount(),8)
	assertEqual(cur.getField(8,0),None)
	print()
	assertEqual(cur.firstRowIndex(),8)
	assertTrue(cur.endOfResultSet())
	assertEqual(cur.rowCount(),8)
	cur.setResultSetBufferSize(0)
	print()


	# cached result set
	print("CACHED RESULT SET: ")
	cur.cacheToFile("cachefile1")
	cur.setCacheTtl(200)
	assertTrue(cur.sendQuery("select * from testtable order by testinteger"))
	filename=cur.getCacheFileName()
	assertEqual(filename,"cachefile1")
	cur.cacheOff()
	assertTrue(cur.openCachedResultSet(filename))
	assertEqual(cur.getField(7,0),8)
	print()


	# column count for cached result set
	print("COLUMN COUNT FOR CACHED RESULT SET: ")
	assertEqual(cur.colCount(),12)
	print()


	# column names for cached result set
	print("COLUMN NAMES FOR CACHED RESULT SET: ")
	assertEqual(cur.getColumnName(0),"TESTINTEGER")
	assertEqual(cur.getColumnName(1),"TESTSMALLINT")
	assertEqual(cur.getColumnName(2),"TESTDECIMAL")
	assertEqual(cur.getColumnName(3),"TESTNUMERIC")
	assertEqual(cur.getColumnName(4),"TESTFLOAT")
	assertEqual(cur.getColumnName(5),"TESTDOUBLE")
	assertEqual(cur.getColumnName(6),"TESTDATE")
	assertEqual(cur.getColumnName(7),"TESTTIME")
	assertEqual(cur.getColumnName(8),"TESTCHAR")
	assertEqual(cur.getColumnName(9),"TESTVARCHAR")
	assertEqual(cur.getColumnName(10),"TESTTIMESTAMP")
	cols=cur.getColumnNames()
	assertEqual(cols[0],"TESTINTEGER")
	assertEqual(cols[1],"TESTSMALLINT")
	assertEqual(cols[2],"TESTDECIMAL")
	assertEqual(cols[3],"TESTNUMERIC")
	assertEqual(cols[4],"TESTFLOAT")
	assertEqual(cols[5],"TESTDOUBLE")
	assertEqual(cols[6],"TESTDATE")
	assertEqual(cols[7],"TESTTIME")
	assertEqual(cols[8],"TESTCHAR")
	assertEqual(cols[9],"TESTVARCHAR")
	assertEqual(cols[10],"TESTTIMESTAMP")
	print()


	# cached result set with result set buffer size
	print("CACHED RESULT SET WITH RESULT SET BUFFER SIZE: ")
	cur.setResultSetBufferSize(2)
	cur.cacheToFile("cachefile1")
	cur.setCacheTtl(200)
	assertTrue(cur.sendQuery("select * from testtable order by testinteger"))
	filename=cur.getCacheFileName()
	assertEqual(filename,"cachefile1")
	cur.cacheOff()
	assertTrue(cur.openCachedResultSet(filename))
	assertEqual(cur.getField(7,0),8)
	assertEqual(cur.getField(8,0),None)
	cur.setResultSetBufferSize(0)
	print()


	# from one cache file to another
	print("FROM ONE CACHE FILE TO ANOTHER: ")
	cur.cacheToFile("cachefile2")
	assertTrue(cur.openCachedResultSet("cachefile1"))
	cur.cacheOff()
	assertTrue(cur.openCachedResultSet("cachefile2"))
	assertEqual(cur.getField(7,0),8)
	assertEqual(cur.getField(8,0),None)
	print()


	# from one cache file to another with result set buffer size
	print("FROM ONE CACHE FILE TO ANOTHER WITH RESULT SET BUFFER SIZE: ")
	cur.setResultSetBufferSize(2)
	cur.cacheToFile("cachefile2")
	assertTrue(cur.openCachedResultSet("cachefile1"))
	cur.cacheOff()
	assertTrue(cur.openCachedResultSet("cachefile2"))
	assertEqual(cur.getField(7,0),8)
	assertEqual(cur.getField(8,0),None)
	cur.setResultSetBufferSize(0)
	print()


	# cached result set with suspend and result set buffer size
	print("CACHED RESULT SET WITH SUSPEND AND RESULT SET BUFFER SIZE: ")
	cur.setResultSetBufferSize(2)
	cur.cacheToFile("cachefile1")
	cur.setCacheTtl(200)
	assertTrue(cur.sendQuery("select * from testtable order by testinteger"))
	assertEqual(cur.getField(2,0),3)
	filename=cur.getCacheFileName()
	assertEqual(filename,"cachefile1")
	id=cur.getResultSetId()
	cur.suspendResultSet()
	assertTrue(con.suspendSession())
	port=con.getConnectionPort()
	socket=con.getConnectionSocket()
	print()
	assertTrue(con.resumeSession(port,socket))
	assertTrue(cur.resumeCachedResultSet(id,filename))
	print()
	assertEqual(cur.firstRowIndex(),4)
	assertFalse(cur.endOfResultSet())
	assertEqual(cur.rowCount(),6)
	assertEqual(cur.getField(7,0),8)
	print()
	assertEqual(cur.firstRowIndex(),6)
	assertFalse(cur.endOfResultSet())
	assertEqual(cur.rowCount(),8)
	assertEqual(cur.getField(8,0),None)
	print()
	assertEqual(cur.firstRowIndex(),8)
	assertTrue(cur.endOfResultSet())
	assertEqual(cur.rowCount(),8)
	cur.cacheOff()
	print()
	assertTrue(cur.openCachedResultSet(filename))
	assertEqual(cur.getField(7,0),8)
	assertEqual(cur.getField(8,0),None)
	cur.setResultSetBufferSize(0)
	print()

	#print("COMMIT AND ROLLBACK: ")
	secondcon=PySQLRClient.sqlrconnection("sqlrelay",9000,
							"/tmp/test.socket",
							"testuser","testpassword")
	secondcur=PySQLRClient.sqlrcursor(secondcon)
	assertTrue(secondcur.sendQuery("select count(*) from testtable"))
	assertEqual(secondcur.getField(0,0),0)
	assertTrue(con.commit())
	assertTrue(secondcur.sendQuery("select count(*) from testtable"))
	assertEqual(secondcur.getField(0,0),8)
	assertTrue(con.autoCommitOn())
	assertTrue(cur.sendQuery("insert into testtable values (10,10,10.1,10.1,10.1,10.1,'01-JAN-2010','10:00:00','testchar10','testvarchar10',NULL,NULL)"))
	assertTrue(secondcur.sendQuery("select count(*) from testtable"))
	assertEqual(secondcur.getField(0,0),9)
	assertTrue(con.autoCommitOff())
	print()


	# row range
	print("ROW RANGE:")
	assertTrue(cur.sendQuery("select * from testtable order by testinteger"))
	print()
	rows=cur.getRowRange(0,5)
	assertEqual(rows[0][0],1)
	assertEqual(rows[0][1],1)
	assertEqual(rows[0][2],Decimal("1.1"))
	assertEqual(rows[0][3],Decimal("1.1"))
	assertEqual(rows[0][4],Decimal("1.1"))
	assertEqual(rows[0][5],Decimal("1.1"))
	assertEqual(rows[0][6],"2001:01:01")
	assertEqual(rows[0][7],"01:00:00")
	assertEqual(rows[0][8],"testchar1                                         ")
	assertEqual(rows[0][9],"testvarchar1")
	print()
	assertEqual(rows[1][0],2)
	assertEqual(rows[1][1],2)
	assertEqual(rows[1][2],Decimal("2.2"))
	assertEqual(rows[1][3],Decimal("2.2"))
	assertEqual(rows[1][4],Decimal("2.2"))
	assertEqual(rows[1][5],Decimal("2.2"))
	assertEqual(rows[1][6],"2002:01:01")
	assertEqual(rows[1][7],"02:00:00")
	assertEqual(rows[1][8],"testchar2                                         ")
	assertEqual(rows[1][9],"testvarchar2")
	print()
	assertEqual(rows[2][0],3)
	assertEqual(rows[2][1],3)
	assertEqual(rows[2][2],Decimal("3.3"))
	assertEqual(rows[2][3],Decimal("3.3"))
	assertEqual(rows[2][4],Decimal("3.3"))
	assertEqual(rows[2][5],Decimal("3.3"))
	assertEqual(rows[2][6],"2003:01:01")
	assertEqual(rows[2][7],"03:00:00")
	assertEqual(rows[2][8],"testchar3                                         ")
	assertEqual(rows[2][9],"testvarchar3")
	print()
	assertEqual(rows[3][0],4)
	assertEqual(rows[3][1],4)
	assertEqual(rows[3][2],Decimal("4.4"))
	assertEqual(rows[3][3],Decimal("4.4"))
	assertEqual(rows[3][4],Decimal("4.4"))
	assertEqual(rows[3][5],Decimal("4.4"))
	assertEqual(rows[3][6],"2004:01:01")
	assertEqual(rows[3][7],"04:00:00")
	assertEqual(rows[3][8],"testchar4                                         ")
	assertEqual(rows[3][9],"testvarchar4")
	print()
	assertEqual(rows[4][0],5)
	assertEqual(rows[4][1],5)
	assertEqual(rows[4][2],Decimal("5.5"))
	assertEqual(rows[4][3],Decimal("5.5"))
	assertEqual(rows[4][4],Decimal("5.5"))
	assertEqual(rows[4][5],Decimal("5.5"))
	assertEqual(rows[4][6],"2005:01:01")
	assertEqual(rows[4][7],"05:00:00")
	assertEqual(rows[4][8],"testchar5                                         ")
	assertEqual(rows[4][9],"testvarchar5")
	print()
	assertEqual(rows[5][0],6)
	assertEqual(rows[5][1],6)
	assertEqual(rows[5][2],Decimal("6.6"))
	assertEqual(rows[5][3],Decimal("6.6"))
	assertEqual(rows[5][4],Decimal("6.6"))
	assertEqual(rows[5][5],Decimal("6.6"))
	assertEqual(rows[5][6],"2006:01:01")
	assertEqual(rows[5][7],"06:00:00")
	assertEqual(rows[5][8],"testchar6                                         ")
	assertEqual(rows[5][9],"testvarchar6")
	print()


	# finished suspended session
	print("FINISHED SUSPENDED SESSION: ")
	assertTrue(cur.sendQuery("select * from testtable order by testinteger"))
	assertEqual(cur.getField(4,0),5)
	assertEqual(cur.getField(5,0),6)
	assertEqual(cur.getField(6,0),7)
	assertEqual(cur.getField(7,0),8)
	id=cur.getResultSetId()
	cur.suspendResultSet()
	assertTrue(con.suspendSession())
	port=con.getConnectionPort()
	socket=con.getConnectionSocket()
	assertTrue(con.resumeSession(port,socket))
	assertTrue(cur.resumeResultSet(id))
	assertEqual(cur.getField(4,0),None)
	assertEqual(cur.getField(5,0),None)
	assertEqual(cur.getField(6,0),None)
	assertEqual(cur.getField(7,0),None)
	print()

	# drop existing table
	con.commit()
	cur.sendQuery("delete from testtable")
	con.commit()
	print()

	# invalid queries...


	# invalid queries
	print("INVALID QUERIES: ")
	assertFalse(cur.sendQuery("select * from testtable1 order by testinteger"))
	assertFalse(cur.sendQuery("select * from testtable1 order by testinteger"))
	assertFalse(cur.sendQuery("select * from testtable1 order by testinteger"))
	assertFalse(cur.sendQuery("select * from testtable1 order by testinteger"))
	print()
	assertFalse(cur.sendQuery("insert into testtable1 values (1,2,3,4)"))
	assertFalse(cur.sendQuery("insert into testtable1 values (1,2,3,4)"))
	assertFalse(cur.sendQuery("insert into testtable1 values (1,2,3,4)"))
	assertFalse(cur.sendQuery("insert into testtable1 values (1,2,3,4)"))
	print()
	assertFalse(cur.sendQuery("create table testtable"))
	assertFalse(cur.sendQuery("create table testtable"))
	assertFalse(cur.sendQuery("create table testtable"))
	assertFalse(cur.sendQuery("create table testtable"))
	print()

if __name__ == "__main__":
	main()
	reportTestStatus()
	sys.exit(status)
