#! /usr/bin/env python

# Copyright (c) David Muse
# See the file COPYING for more information.

from SQLRelay import PySQLRClient
import sys
from assert import *
import string
from decimal import Decimal


def main():

	PySQLRClient.getNumericFieldsAsNumbers()

	# instantiation
	con=PySQLRClient.sqlrconnection("sqlrelay",9000,
						"/tmp/test.socket",
						"testuser","testpassword")
	cur=PySQLRClient.sqlrcursor(con)

	# get database type
	print("IDENTIFY: ")
	assertEqual(con.identify(),"sqlite")
	print()

	# ping
	print("PING: ")
	assertTrue(con.ping())
	print()

	# drop existing table
	cur.sendQuery("begin transaction")
	cur.sendQuery("drop table testtable")
	con.commit()

	# create a new table
	print("CREATE TEMPTABLE: ")
	cur.sendQuery("begin transaction")
	assertTrue(cur.sendQuery("create table testtable (testint int, testfloat float, testchar char(40), testvarchar varchar(40))"))
	con.commit()
	print()

	print("INSERT: ")
	cur.sendQuery("begin transaction")
	assertTrue(cur.sendQuery("insert into testtable values (1,1.1,'testchar1','testvarchar1')"))
	assertTrue(cur.sendQuery("insert into testtable values (2,2.2,'testchar2','testvarchar2')"))
	assertTrue(cur.sendQuery("insert into testtable values (3,3.3,'testchar3','testvarchar3')"))
	assertTrue(cur.sendQuery("insert into testtable values (4,4.4,'testchar4','testvarchar4')"))
	print()

	print("AFFECTED ROWS: ")
	assertEqual(cur.affectedRows(),0)
	print()

	print("BIND BY NAME: ")
	cur.prepareQuery("insert into testtable values (:var1,:var2,:var3,:var4)")
	assertEqual(cur.countBindVariables(),4)
	cur.inputBind("var1",5)
	cur.inputBind("var2",Decimal("5.5"),4,1)
	cur.inputBind("var3","testchar5")
	cur.inputBind("var4","testvarchar5")
	assertTrue(cur.executeQuery())
	cur.clearBinds()
	cur.inputBind("var1",6)
	cur.inputBind("var2",Decimal("6.6"),4,1)
	cur.inputBind("var3","testchar6")
	cur.inputBind("var4","testvarchar6")
	assertTrue(cur.executeQuery())
	print()

	print("ARRAY OF BINDS BY NAME: ")
	cur.clearBinds()
	cur.inputBinds(["var1","var2","var3","var4"],
			[7,7.7,"testchar7","testvarchar7"],[0,4,0,0],[0,1,0,0])
	assertTrue(cur.executeQuery())
	print()

	print("BIND BY NAME WITH VALIDATION: ")
	cur.clearBinds()
	cur.inputBind("var1",8)
	cur.inputBind("var2",8.8,4,1)
	cur.inputBind("var3","testchar8")
	cur.inputBind("var4","testvarchar8")
	cur.validateBinds()
	assertTrue(cur.executeQuery())
	print()

	print("SELECT: ")
	assertTrue(cur.sendQuery("select * from testtable order by testint"))
	print()

	print("COLUMN COUNT: ")
	assertEqual(cur.colCount(),4)
	print()

	print("COLUMN NAMES: ")
	assertEqual(cur.getColumnName(0),"testint")
	assertEqual(cur.getColumnName(1),"testfloat")
	assertEqual(cur.getColumnName(2),"testchar")
	assertEqual(cur.getColumnName(3),"testvarchar")
	cols=cur.getColumnNames()
	assertEqual(cols[0],"testint")
	assertEqual(cols[1],"testfloat")
	assertEqual(cols[2],"testchar")
	assertEqual(cols[3],"testvarchar")
	print()

	print("COLUMN TYPES: ")
	assertEqual(cur.getColumnType(0),"INTEGER")
	assertEqual(cur.getColumnType('testint'),"INTEGER")
	assertEqual(cur.getColumnType(1),"FLOAT")
	assertEqual(cur.getColumnType('testfloat'),"FLOAT")
	assertEqual(cur.getColumnType(2),"STRING")
	assertEqual(cur.getColumnType('testchar'),"STRING")
	assertEqual(cur.getColumnType(3),"STRING")
	assertEqual(cur.getColumnType('testvarchar'),"STRING")
	print()

	print("COLUMN LENGTH: ")
	assertEqual(cur.getColumnLength(0),0)
	assertEqual(cur.getColumnLength('testint'),0)
	assertEqual(cur.getColumnLength(1),0)
	assertEqual(cur.getColumnLength('testfloat'),0)
	assertEqual(cur.getColumnLength(2),0)
	assertEqual(cur.getColumnLength('testchar'),0)
	assertEqual(cur.getColumnLength(3),0)
	assertEqual(cur.getColumnLength('testvarchar'),0)
	print()

	print("LONGEST COLUMN: ")
	assertEqual(cur.getLongest(0),1)
	assertEqual(cur.getLongest('testint'),1)
	assertEqual(cur.getLongest(1),3)
	assertEqual(cur.getLongest('testfloat'),3)
	assertEqual(cur.getLongest(2),9)
	assertEqual(cur.getLongest('testchar'),9)
	assertEqual(cur.getLongest(3),12)
	assertEqual(cur.getLongest('testvarchar'),12)
	print()

	print("ROW COUNT: ")
	assertEqual(cur.rowCount(),8)
	print()

	print("TOTAL ROWS: ")
	assertEqual(cur.totalRows(),0)
	print()

	print("FIRST ROW INDEX: ")
	assertEqual(cur.firstRowIndex(),0)
	print()

	print("END OF RESULT SET: ")
	assertTrue(cur.endOfResultSet())
	print()

	print("FIELDS BY INDEX: ")
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(0,1),Decimal("1.1"))
	assertEqual(cur.getField(0,2),"testchar1")
	assertEqual(cur.getField(0,3),"testvarchar1")
	print()
	assertEqual(cur.getField(7,0),8)
	assertEqual(cur.getField(7,1),Decimal("8.8"))
	assertEqual(cur.getField(7,2),"testchar8")
	assertEqual(cur.getField(7,3),"testvarchar8")
	print()

	print("FIELD LENGTHS BY INDEX: ")
	assertEqual(cur.getFieldLength(0,0),1)
	assertEqual(cur.getFieldLength(0,1),3)
	assertEqual(cur.getFieldLength(0,2),9)
	assertEqual(cur.getFieldLength(0,3),12)
	print()
	assertEqual(cur.getFieldLength(7,0),1)
	assertEqual(cur.getFieldLength(7,1),3)
	assertEqual(cur.getFieldLength(7,2),9)
	assertEqual(cur.getFieldLength(7,3),12)
	print()

	print("FIELDS BY NAME: ")
	assertEqual(cur.getField(0,"testint"),1)
	assertEqual(cur.getField(0,"testfloat"),Decimal("1.1"))
	assertEqual(cur.getField(0,"testchar"),"testchar1")
	assertEqual(cur.getField(0,"testvarchar"),"testvarchar1")
	print()
	assertEqual(cur.getField(7,"testint"),8)
	assertEqual(cur.getField(7,"testfloat"),Decimal("8.8"))
	assertEqual(cur.getField(7,"testchar"),"testchar8")
	assertEqual(cur.getField(7,"testvarchar"),"testvarchar8")
	print()

	print("FIELD LENGTHS BY NAME: ")
	assertEqual(cur.getFieldLength(0,"testint"),1)
	assertEqual(cur.getFieldLength(0,"testfloat"),3)
	assertEqual(cur.getFieldLength(0,"testchar"),9)
	assertEqual(cur.getFieldLength(0,"testvarchar"),12)
	print()
	assertEqual(cur.getFieldLength(7,"testint"),1)
	assertEqual(cur.getFieldLength(7,"testfloat"),3)
	assertEqual(cur.getFieldLength(7,"testchar"),9)
	assertEqual(cur.getFieldLength(7,"testvarchar"),12)
	print()

	print("FIELDS BY ARRAY: ")
	fields=cur.getRow(0)
	assertEqual(fields[0],1)
	assertEqual(fields[1],Decimal("1.1"))
	assertEqual(fields[2],"testchar1")
	assertEqual(fields[3],"testvarchar1")
	print()

	print("FIELD LENGTHS BY ARRAY: ")
	fieldlens=cur.getRowLengths(0)
	assertEqual(fieldlens[0],1)
	assertEqual(fieldlens[1],3)
	assertEqual(fieldlens[2],9)
	assertEqual(fieldlens[3],12)
	print()

	print("FIELDS BY DICTIONARY: ")
	fields=cur.getRowDictionary(0)
	assertEqual(fields["testint"],1)
	assertEqual(fields["testfloat"],Decimal("1.1"))
	assertEqual(fields["testchar"],"testchar1")
	assertEqual(fields["testvarchar"],"testvarchar1")
	print()
	fields=cur.getRowDictionary(7)
	assertEqual(fields["testint"],8)
	assertEqual(fields["testfloat"],Decimal("8.8"))
	assertEqual(fields["testchar"],"testchar8")
	assertEqual(fields["testvarchar"],"testvarchar8")
	print()

	print("FIELD LENGTHS BY DICTIONARY: ")
	fieldlengths=cur.getRowLengthsDictionary(0)
	assertEqual(fieldlengths["testint"],1)
	assertEqual(fieldlengths["testfloat"],3)
	assertEqual(fieldlengths["testchar"],9)
	assertEqual(fieldlengths["testvarchar"],12)
	print()
	fieldlengths=cur.getRowLengthsDictionary(7)
	assertEqual(fieldlengths["testint"],1)
	assertEqual(fieldlengths["testfloat"],3)
	assertEqual(fieldlengths["testchar"],9)
	assertEqual(fieldlengths["testvarchar"],12)
	print()
		
	print("INDIVIDUAL SUBSTITUTIONS: ")
	cur.sendQuery("drop table testtable1")
	assertTrue(cur.sendQuery("create table testtable1 (col1 int, col2 char, col3 float)"))
	cur.prepareQuery("insert into testtable1 values ($(var1),'$(var2)',$(var3))")
	cur.substitution("var1",1)
	cur.substitution("var2","hello")
	cur.substitution("var3",10.5556,6,4)
	assertTrue(cur.executeQuery())
	print()

	print("FIELDS: ")
	assertTrue(cur.sendQuery("select * from testtable1"))
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(0,1),"hello")
	assertEqual(cur.getField(0,2),Decimal("10.5556"))
	assertTrue(cur.sendQuery("delete from testtable1"))
	print()

	print("ARRAY SUBSTITUTIONS: ")
	cur.prepareQuery("insert into testtable1 values ($(var1),'$(var2)',$(var3))")
	cur.substitutions(["var1","var2","var3"],
				[1,"hello",10.5556],[0,0,6],[0,0,4])
	assertTrue(cur.executeQuery())
	print()

	print("FIELDS: ")
	assertTrue(cur.sendQuery("select * from testtable1"))
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(0,1),"hello")
	assertEqual(cur.getField(0,2),Decimal("10.5556"))
	assertTrue(cur.sendQuery("delete from testtable1"))
	print()

	print("NULLS as Nones: ")
	cur.getNullsAsNone()
	assertTrue(cur.sendQuery("insert into testtable1 values (1,NULL,NULL)"))
	assertTrue(cur.sendQuery("select * from testtable1"))
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(0,1),None)
	assertEqual(cur.getField(0,2),None)
	cur.getNullsAsEmptyStrings()
	assertTrue(cur.sendQuery("select * from testtable1"))
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(0,1),"")
	assertEqual(cur.getField(0,2),"")
	cur.getNullsAsNone()
	print()

	print("RESULT SET BUFFER SIZE: ")
	assertEqual(cur.getResultSetBufferSize(),0)
	cur.setResultSetBufferSize(2)
	assertTrue(cur.sendQuery("select * from testtable order by testint"))
	assertEqual(cur.getResultSetBufferSize(),2)
	print()
	assertEqual(cur.firstRowIndex(),0)
	assertFalse(cur.endOfResultSet())
	assertEqual(cur.rowCount(),2)
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(1,0),2)
	assertEqual(cur.getField(2,0),3)
	print()
	assertEqual(cur.firstRowIndex(),2)
	assertFalse(cur.endOfResultSet())
	assertEqual(cur.rowCount(),4)
	assertEqual(cur.getField(6,0),7)
	assertEqual(cur.getField(7,0),8)
	print()
	assertEqual(cur.firstRowIndex(),6)
	assertFalse(cur.endOfResultSet())
	assertEqual(cur.rowCount(),8)
	assertEqual(cur.getField(8,0),None)
	print()
	assertEqual(cur.firstRowIndex(),8)
	assertTrue(cur.endOfResultSet())
	assertEqual(cur.rowCount(),8)
	print()

	print("DONT GET COLUMN INFO: ")
	cur.dontGetColumnInfo()
	assertTrue(cur.sendQuery("select * from testtable order by testint"))
	assertEqual(cur.getColumnName(0),None)
	assertEqual(cur.getColumnLength(0),0)
	assertEqual(cur.getColumnType(0),None)
	cur.getColumnInfo()
	assertTrue(cur.sendQuery("select * from testtable order by testint"))
	assertEqual(cur.getColumnName(0),"testint")
	assertEqual(cur.getColumnLength(0),0)
	assertEqual(cur.getColumnType(0),"INTEGER")
	print()

	print("SUSPENDED SESSION: ")
	assertTrue(cur.sendQuery("select * from testtable order by testint"))
	cur.suspendResultSet()
	assertTrue(con.suspendSession())
	port=con.getConnectionPort()
	socket=con.getConnectionSocket()
	assertTrue(con.resumeSession(port,socket))
	print()
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(1,0),2)
	assertEqual(cur.getField(2,0),3)
	assertEqual(cur.getField(3,0),4)
	assertEqual(cur.getField(4,0),5)
	assertEqual(cur.getField(5,0),6)
	assertEqual(cur.getField(6,0),7)
	assertEqual(cur.getField(7,0),8)
	print()
	assertTrue(cur.sendQuery("select * from testtable order by testint"))
	cur.suspendResultSet()
	assertTrue(con.suspendSession())
	port=con.getConnectionPort()
	socket=con.getConnectionSocket()
	assertTrue(con.resumeSession(port,socket))
	print()
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(1,0),2)
	assertEqual(cur.getField(2,0),3)
	assertEqual(cur.getField(3,0),4)
	assertEqual(cur.getField(4,0),5)
	assertEqual(cur.getField(5,0),6)
	assertEqual(cur.getField(6,0),7)
	assertEqual(cur.getField(7,0),8)
	print()
	assertTrue(cur.sendQuery("select * from testtable order by testint"))
	cur.suspendResultSet()
	assertTrue(con.suspendSession())
	port=con.getConnectionPort()
	socket=con.getConnectionSocket()
	assertTrue(con.resumeSession(port,socket))
	print()
	assertEqual(cur.getField(0,0),1)
	assertEqual(cur.getField(1,0),2)
	assertEqual(cur.getField(2,0),3)
	assertEqual(cur.getField(3,0),4)
	assertEqual(cur.getField(4,0),5)
	assertEqual(cur.getField(5,0),6)
	assertEqual(cur.getField(6,0),7)
	assertEqual(cur.getField(7,0),8)
	print()

	print("SUSPENDED RESULT SET: ")
	cur.setResultSetBufferSize(2)
	assertTrue(cur.sendQuery("select * from testtable order by testint"))
	assertEqual(cur.getField(2,0),3)
	id=cur.getResultSetId()
	cur.suspendResultSet()
	assertTrue(con.suspendSession())
	port=con.getConnectionPort()
	socket=con.getConnectionSocket()
	assertTrue(con.resumeSession(port,socket))
	assertTrue(cur.resumeResultSet(id))
	print()
	assertEqual(cur.firstRowIndex(),4)
	assertFalse(cur.endOfResultSet())
	assertEqual(cur.rowCount(),6)
	assertEqual(cur.getField(7,0),8)
	print()
	assertEqual(cur.firstRowIndex(),6)
	assertFalse(cur.endOfResultSet())
	assertEqual(cur.rowCount(),8)
	assertEqual(cur.getField(8,0),None)
	print()
	assertEqual(cur.firstRowIndex(),8)
	assertTrue(cur.endOfResultSet())
	assertEqual(cur.rowCount(),8)
	cur.setResultSetBufferSize(0)
	print()

	print("CACHED RESULT SET: ")
	cur.cacheToFile("cachefile1")
	cur.setCacheTtl(200)
	assertTrue(cur.sendQuery("select * from testtable order by testint"))
	filename=cur.getCacheFileName()
	assertEqual(filename,"cachefile1")
	cur.cacheOff()
	assertTrue(cur.openCachedResultSet(filename))
	assertEqual(cur.getField(7,0),8)
	print()

	print("COLUMN COUNT FOR CACHED RESULT SET: ")
	assertEqual(cur.colCount(),4)
	print()

	print("COLUMN NAMES FOR CACHED RESULT SET: ")
	assertEqual(cur.getColumnName(0),"testint")
	assertEqual(cur.getColumnName(1),"testfloat")
	assertEqual(cur.getColumnName(2),"testchar")
	assertEqual(cur.getColumnName(3),"testvarchar")
	cols=cur.getColumnNames()
	assertEqual(cols[0],"testint")
	assertEqual(cols[1],"testfloat")
	assertEqual(cols[2],"testchar")
	assertEqual(cols[3],"testvarchar")
	print()

	print("CACHED RESULT SET WITH RESULT SET BUFFER SIZE: ")
	cur.setResultSetBufferSize(2)
	cur.cacheToFile("cachefile1")
	cur.setCacheTtl(200)
	assertTrue(cur.sendQuery("select * from testtable order by testint"))
	filename=cur.getCacheFileName()
	assertEqual(filename,"cachefile1")
	cur.cacheOff()
	assertTrue(cur.openCachedResultSet(filename))
	assertEqual(cur.getField(7,0),8)
	assertEqual(cur.getField(8,0),None)
	cur.setResultSetBufferSize(0)
	print()

	print("FROM ONE CACHE FILE TO ANOTHER: ")
	cur.cacheToFile("cachefile2")
	assertTrue(cur.openCachedResultSet("cachefile1"))
	cur.cacheOff()
	assertTrue(cur.openCachedResultSet("cachefile2"))
	assertEqual(cur.getField(7,0),8)
	assertEqual(cur.getField(8,0),None)
	print()

	print("FROM ONE CACHE FILE TO ANOTHER WITH RESULT SET BUFFER SIZE: ")
	cur.setResultSetBufferSize(2)
	cur.cacheToFile("cachefile2")
	assertTrue(cur.openCachedResultSet("cachefile1"))
	cur.cacheOff()
	assertTrue(cur.openCachedResultSet("cachefile2"))
	assertEqual(cur.getField(7,0),8)
	assertEqual(cur.getField(8,0),None)
	cur.setResultSetBufferSize(0)
	print()

	print("CACHED RESULT SET WITH SUSPEND AND RESULT SET BUFFER SIZE: ")
	cur.setResultSetBufferSize(2)
	cur.cacheToFile("cachefile1")
	cur.setCacheTtl(200)
	assertTrue(cur.sendQuery("select * from testtable order by testint"))
	assertEqual(cur.getField(2,0),3)
	filename=cur.getCacheFileName()
	assertEqual(filename,"cachefile1")
	id=cur.getResultSetId()
	cur.suspendResultSet()
	assertTrue(con.suspendSession())
	port=con.getConnectionPort()
	socket=con.getConnectionSocket()
	print()
	assertTrue(con.resumeSession(port,socket))
	assertTrue(cur.resumeCachedResultSet(id,filename))
	print()
	assertEqual(cur.firstRowIndex(),4)
	assertFalse(cur.endOfResultSet())
	assertEqual(cur.rowCount(),6)
	assertEqual(cur.getField(7,0),8)
	print()
	assertEqual(cur.firstRowIndex(),6)
	assertFalse(cur.endOfResultSet())
	assertEqual(cur.rowCount(),8)
	assertEqual(cur.getField(8,0),None)
	print()
	assertEqual(cur.firstRowIndex(),8)
	assertTrue(cur.endOfResultSet())
	assertEqual(cur.rowCount(),8)
	cur.cacheOff()
	print()
	assertTrue(cur.openCachedResultSet(filename))
	assertEqual(cur.getField(7,0),8)
	assertEqual(cur.getField(8,0),None)
	cur.setResultSetBufferSize(0)
	print()

	print("ROW RANGE:")
	assertTrue(cur.sendQuery("select * from testtable order by testint"))
	print()
	rows=cur.getRowRange(0,5)
	assertEqual(rows[0][0],1)
	assertEqual(rows[0][1],Decimal("1.1"))
	assertEqual(rows[0][2],"testchar1")
	assertEqual(rows[0][3],"testvarchar1")
	print()
	assertEqual(rows[1][0],2)
	assertEqual(rows[1][1],Decimal("2.2"))
	assertEqual(rows[1][2],"testchar2")
	assertEqual(rows[1][3],"testvarchar2")
	print()
	assertEqual(rows[2][0],3)
	assertEqual(rows[2][1],Decimal("3.3"))
	assertEqual(rows[2][2],"testchar3")
	assertEqual(rows[2][3],"testvarchar3")
	print()
	assertEqual(rows[3][0],4)
	assertEqual(rows[3][1],Decimal("4.4"))
	assertEqual(rows[3][2],"testchar4")
	assertEqual(rows[3][3],"testvarchar4")
	print()
	assertEqual(rows[4][0],5)
	assertEqual(rows[4][1],Decimal("5.5"))
	assertEqual(rows[4][2],"testchar5")
	assertEqual(rows[4][3],"testvarchar5")
	print()
	assertEqual(rows[5][0],6)
	assertEqual(rows[5][1],Decimal("6.6"))
	assertEqual(rows[5][2],"testchar6")
	assertEqual(rows[5][3],"testvarchar6")
	print()

	print("COMMIT AND ROLLBACK: ")
	secondcon=PySQLRClient.sqlrconnection("sqlrelay",9000,
						"/tmp/test.socket",
						"testuser","testpassword")
	secondcur=PySQLRClient.sqlrcursor(secondcon)
	assertTrue(secondcur.sendQuery("select count(*) from testtable"))
	assertEqual(secondcur.getField(0,0),0)
	assertTrue(con.commit())
	assertTrue(secondcur.sendQuery("select count(*) from testtable"))
	assertEqual(secondcur.getField(0,0),8)
	assertTrue(cur.sendQuery("insert into testtable values (10,10.1,'testchar10','testvarchar10')"))
	assertTrue(secondcur.sendQuery("select count(*) from testtable"))
	assertEqual(secondcur.getField(0,0),9)
	print()

	print("FINISHED SUSPENDED SESSION: ")
	assertTrue(cur.sendQuery("select * from testtable order by testint"))
	assertEqual(cur.getField(4,0),5)
	assertEqual(cur.getField(5,0),6)
	assertEqual(cur.getField(6,0),7)
	assertEqual(cur.getField(7,0),8)
	id=cur.getResultSetId()
	cur.suspendResultSet()
	assertTrue(con.suspendSession())
	port=con.getConnectionPort()
	socket=con.getConnectionSocket()
	assertTrue(con.resumeSession(port,socket))
	assertTrue(cur.resumeResultSet(id))
	assertEqual(cur.getField(4,0),None)
	assertEqual(cur.getField(5,0),None)
	assertEqual(cur.getField(6,0),None)
	assertEqual(cur.getField(7,0),None)
	print()

	# drop existing table
	cur.sendQuery("drop table testtable")

	# invalid queries...
	print("INVALID QUERIES: ")
	assertFalse(cur.sendQuery("select * from testtable"))
	assertFalse(cur.sendQuery("select * from testtable"))
	assertFalse(cur.sendQuery("select * from testtable"))
	assertFalse(cur.sendQuery("select * from testtable"))
	print()
	assertFalse(cur.sendQuery("insert into testtable values (1,2,3,4)"))
	assertFalse(cur.sendQuery("insert into testtable values (1,2,3,4)"))
	assertFalse(cur.sendQuery("insert into testtable values (1,2,3,4)"))
	assertFalse(cur.sendQuery("insert into testtable values (1,2,3,4)"))
	print()
	assertFalse(cur.sendQuery("create table testtable"))
	assertFalse(cur.sendQuery("create table testtable"))
	assertFalse(cur.sendQuery("create table testtable"))
	assertFalse(cur.sendQuery("create table testtable"))
	print()

if __name__ == "__main__":
	main()
	sys.exit(0)
