/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_firstworks_sqlrelay_SQLRConnection */

#ifndef _Included_com_firstworks_sqlrelay_SQLRConnection
#define _Included_com_firstworks_sqlrelay_SQLRConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_delete
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    setConnectTimeout
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_setConnectTimeout
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    setResponseTimeout
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_setResponseTimeout
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getConnectTimeoutSeconds
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getConnectTimeoutSeconds
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getConnectTimeoutMicroseconds
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getConnectTimeoutMicroseconds
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getResponseTimeoutSeconds
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getResponseTimeoutSeconds
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getResponseTimeoutMicroseconds
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getResponseTimeoutMicroseconds
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    endSession
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_endSession
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    suspendSession
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_suspendSession
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getConnectionPort
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getConnectionPort
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getConnectionSocket
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getConnectionSocket
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    resumeSession
 * Signature: (SLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_resumeSession
  (JNIEnv *, jobject, jshort, jstring);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    ping
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_ping
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    identify
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_identify
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    dbVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_dbVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    serverVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_serverVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    clientVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_clientVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    bindFormat
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_bindFormat
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    nextvalFormat
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_nextvalFormat
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    selectDatabase
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_selectDatabase (JNIEnv *env, jobject self, jstring database);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getCurrentDatabase
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getCurrentDatabase
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getDatabaseIsSchema
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getDatabaseIsSchema
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    selectCatalog
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_selectCatalog
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getCurrentCatalog
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getCurrentCatalog
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    selectSchema
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_selectSchema
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getCurrentSchema
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getCurrentSchema
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getCurrentUser
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getCurrentUser
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getLastInsertId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getLastinsertId
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    autoCommitOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_autoCommitOn
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    autoCommitOff
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_autoCommitOff
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getAutoCommit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getAutoCommit
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    begin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_begin
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    commit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_commit
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    rollback
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_rollback
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getDefaultIsolationLevel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getDefaultIsolationLevel__
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getDefaultIsolationLevel
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getDefaultIsolationLevel__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    setIsolationLevel
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_setIsolationLevel__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getIsolationLevel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getIsolationLevel__
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    setIsolationLevel
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_setIsolationLevel__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getIsolationLevel
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getIsolationLevel__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getDefaultTransactionModel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getDefaultTransactionModel
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    setTransactionModel
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_setTransactionModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getTransactionModel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getTransactionModel
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getDatabaseFeature
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    errorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_errorMessage
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    debugOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_debugOn
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    debugOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_debugOff
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getDebug
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getDebug
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    setDebugFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_setDebugFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    setClientInfo
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_setClientInfo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    getClientInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_getClientInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_firstworks_sqlrelay_SQLRConnection
 * Method:    alloc
 * Signature: (Ljava/lang/String;SLjava/lang/String;Ljava/lang/String;Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_com_firstworks_sqlrelay_SQLRConnection_alloc
  (JNIEnv *, jobject, jstring, jshort, jstring, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
