package com.firstworks.sql;

import java.sql.*;
import java.util.List;
import java.util.ArrayList;

import com.firstworks.sqlrelay.*;

public class SQLRelayStatement implements Statement {

	private Connection		connection;
	private SQLRConnection		sqlrcon;
	protected SQLRCursor		sqlrcur;
	private List<String>		batch;
	private boolean			closeoncompletion;
	protected SQLRelayResultSet	resultset;
	private int			fetchdirection;
	private int			maxfieldsize;
	private int			maxrows;
	private boolean			poolable;
	protected int			updatecount;
	private boolean			escapeprocessing;
	protected SQLRelayDriver	driver;

	public SQLRelayStatement(SQLRelayDriver driver) {
		this.driver=driver;
		driver.debugFunction(this);
		reset();
		driver.debugEnd();
	}

	private void reset() {
		driver.debugFunction(this);
		connection=null;
		sqlrcon=null;
		sqlrcur=null;
		batch=new ArrayList<String>();
		closeoncompletion=false;
		resultset=null;
		fetchdirection=ResultSet.FETCH_FORWARD;
		maxfieldsize=0;
		maxrows=0;
		poolable=false;
		updatecount=-1;
		escapeprocessing=true;
		driver.debugEnd();
	}

	public synchronized
	void setConnection(Connection connection) {
		this.connection=connection;
	}

	public synchronized
	void setSQLRConnection(SQLRConnection sqlrcon) {
		this.sqlrcon=sqlrcon;
	}

	public synchronized
	void setSQLRCursor(SQLRCursor sqlrcur) {
		this.sqlrcur=sqlrcur;
	}

	public synchronized
	void addBatch(String sql) throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		batch.add(sql);
		driver.debugEnd();
	}

	public synchronized
	void cancel() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		// FIXME: maybe we can support this somehow?
		driver.debugEnd();
	}

	public synchronized
	void clearBatch() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		batch.clear();
		driver.debugEnd();
	}

	public synchronized
	void clearWarnings() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		driver.debugEnd();
	}

	public synchronized
	void close() throws SQLException {
		driver.debugFunction(this);
		if (resultset!=null) {
			resultset.close();
		}
		reset();
		driver.debugEnd();
	}

	public synchronized
	void closeOnCompletion() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		closeoncompletion=true;
		driver.debugEnd();
	}

	public synchronized
	boolean execute(String sql) throws SQLException {
		driver.debugFunction(this);
		driver.debugPrintln("sql: ",sql);

		throwExceptionIfClosed();

		// FIXME: handle timeout
		resultset=null;
		updatecount=-1;

		boolean	result=sqlrcur.sendQuery(sql);

		driver.debugPrintln("result: ",result);

		if (result) {

			updatecount=(int)sqlrcur.affectedRows();

			driver.debugPrintln("updatecount: ",updatecount);
			driver.debugPrintln("colcount: ",sqlrcur.colCount());

			if (sqlrcur.colCount()>0) {
				resultset=new SQLRelayResultSet(driver);
				resultset.setStatement(this);
				resultset.setSQLRCursor(sqlrcur);
			}
		} else {
			throwErrorMessageException();
		}
		driver.debugEnd();
		return result;
	}

	public synchronized
	boolean execute(String sql, int autoGeneratedKeys)
						throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		driver.debugEnd();
		return false;
	}

	public synchronized
	boolean execute(String sql, int[] columnIndexes)
						throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		driver.debugEnd();
		return false;
	}

	public synchronized
	boolean execute(String sql, String[] columnNames)
						throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		driver.debugEnd();
		return false;
	}

	public synchronized
	int[] executeBatch() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		// FIXME: handle timeout
		int[]	results=new int[batch.size()];
		int	count=0;
		for (String sql: batch) {
			results[count++]=executeUpdate(sql);
		}
		driver.debugEnd();
		return results;
	}

	public synchronized
	ResultSet executeQuery(String sql) throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		// FIXME: handle timeout
		resultset=null;
		updatecount=-1;
		if (sqlrcur.sendQuery(sql)) {
			resultset=new SQLRelayResultSet(driver);
			resultset.setStatement(this);
			resultset.setSQLRCursor(sqlrcur);
		} else {
			throw new SQLException(sqlrcur.errorMessage());
		}
		driver.debugEnd();
		return resultset;
	}

	public synchronized
	int executeUpdate(String sql) throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		// FIXME: handle timeout
		resultset=null;
		updatecount=-1;
		if (sqlrcur.sendQuery(sql)) {
			updatecount=(int)sqlrcur.affectedRows();
		} else {
			throwErrorMessageException();
		}
		driver.debugEnd();
		return updatecount;
	}

	public synchronized
	int executeUpdate(String sql, int autoGeneratedKeys)
						throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		driver.debugEnd();
		return 0;
	}

	public synchronized
	int executeUpdate(String sql, int[] columnIndexes)
						throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		driver.debugEnd();
		return 0;
	}

	public synchronized
	int executeUpdate(String sql, String[] columnNames)
						throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		driver.debugEnd();
		return 0;
	}

	public synchronized
	Connection getConnection() throws SQLException {
		//driver.debugFunction(this);
		throwExceptionIfClosed();
		//driver.debugEnd();
		return connection;
	}

	public synchronized
	int getFetchDirection() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		driver.debugEnd();
		return fetchdirection;
	}

	public synchronized
	int getFetchSize() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		int	rsbs=(int)sqlrcur.getResultSetBufferSize();
		driver.debugEnd();
		return rsbs;
	}

	public synchronized
	ResultSet getGeneratedKeys() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		// FIXME: maybe we can support this somehow?
		driver.debugEnd();
		return null;
	}

	public synchronized
	int getMaxFieldSize() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		driver.debugEnd();
		return maxfieldsize;
	}

	public synchronized
	int getMaxRows() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		driver.debugEnd();
		return maxrows;
	}

	public synchronized
	boolean getMoreResults() throws SQLException {
		driver.debugFunction(this);
		boolean	gmr=getMoreResults(Statement.CLOSE_CURRENT_RESULT);
		driver.debugEnd();
		return gmr;
	}

	public synchronized
	boolean getMoreResults(int current) throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		switch (current) {
			case Statement.CLOSE_CURRENT_RESULT:
				if (resultset!=null) {
					resultset.close();
					resultset=null;
					updatecount=-1;
				}
				// FIXME: we could support this...
				driver.debugEnd();
				return false;
			case Statement.KEEP_CURRENT_RESULT:
				throwFeatureNotSupportedException();
				driver.debugEnd();
				return false;
			case Statement.CLOSE_ALL_RESULTS:
				throwFeatureNotSupportedException();
				driver.debugEnd();
				return false;
			default:
				throwFeatureNotSupportedException();
				driver.debugEnd();
				return false;
		}
	}

	public synchronized
	int getQueryTimeout() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		// FIXME: this can be supported
		//return sqlrcon.getResponseTimeout();
		driver.debugEnd();
		return 0;
	}

	public synchronized
	ResultSet getResultSet() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		driver.debugEnd();
		return resultset;
	}

	public synchronized
	int getResultSetConcurrency() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		// FIXME: is this correct?
		driver.debugEnd();
		return ResultSet.CONCUR_READ_ONLY;
	}

	public synchronized
	int getResultSetHoldability() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		// FIXME: is this correct?
		driver.debugEnd();
		return ResultSet.CLOSE_CURSORS_AT_COMMIT;
	}

	public synchronized
	int getResultSetType() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		driver.debugEnd();
		return ResultSet.TYPE_FORWARD_ONLY;
	}

	public synchronized
	int getUpdateCount() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		driver.debugPrintln("updatecount=",updatecount);
		driver.debugEnd();
		return updatecount;
	}

	public synchronized
	SQLWarning getWarnings() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		driver.debugEnd();
		return null;
	}

	public synchronized
	boolean isClosed() throws SQLException {
		driver.debugFunction(this);
		boolean	closed=(sqlrcur==null);
		driver.debugEnd();
		return closed;
	}

	public synchronized
	boolean isCloseOnCompletion() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		driver.debugEnd();
		return false;
	}

	public synchronized
	boolean isPoolable() throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		driver.debugEnd();
		return poolable;
	}

	public synchronized
	void setCursorName(String name) throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		driver.debugEnd();
	}

	public synchronized
	void setEscapeProcessing(boolean enable) throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		escapeprocessing=enable;
		// FIXME: do something with this...
		driver.debugEnd();
	}

	public synchronized
	void setFetchDirection(int direction) throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		fetchdirection=direction;
		driver.debugEnd();
	}

	public synchronized
	void setFetchSize(int rows) throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		sqlrcur.setResultSetBufferSize(rows);
		driver.debugEnd();
	}

	public synchronized
	void setMaxFieldSize(int max) throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		maxfieldsize=max;
		driver.debugEnd();
	}

	public synchronized
	void setMaxRows(int max) throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		maxrows=max;
		driver.debugEnd();
	}

	public synchronized
	void setPoolable(boolean poolable) throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		this.poolable=poolable;
		driver.debugEnd();
	}

	public synchronized
	void setQueryTimeout(int seconds) throws SQLException {
		driver.debugFunction(this);
		throwExceptionIfClosed();
		// FIXME: hmm... this is at the connection level
		sqlrcon.setResponseTimeout(seconds,0);
		driver.debugEnd();
	}

	public synchronized
	boolean isWrapperFor(Class<?> iface) throws SQLException {
		driver.debugFunction(this);
		driver.debugEnd();
		return (iface==SQLRCursor.class);
	}

	@SuppressWarnings({"unchecked"})
	public synchronized
	<T> T unwrap(Class<T> iface) throws SQLException {
		driver.debugFunction(this);
		driver.debugEnd();
		return (T)((iface==SQLRCursor.class)?sqlrcur:null);
	}

	protected void throwExceptionIfClosed() throws SQLException {
		if (sqlrcur==null) {
			throwException("statement is closed");
		}
	}

	protected void throwErrorMessageException() throws SQLException {
		throwException(sqlrcur.errorMessage());
	}

	protected void throwFeatureNotSupportedException() throws SQLException {
		driver.debugZeroIndent();
		throw new SQLFeatureNotSupportedException();
	}

	protected void throwException(String reason) throws SQLException {
		driver.debugZeroIndent();
		throw new SQLException(reason);
	}

	public synchronized
	SQLRCursor getSQLRCursor() {
		return sqlrcur;
	}

	public synchronized
	SQLRConnection getSQLRConnection() {
		return sqlrcon;
	}
};
