// Copyright (c) David Muse
// See the file COPYING for more information.
package com.firstworks.sql;

import java.sql.*;
import java.util.List;
import java.util.ArrayList;

import com.firstworks.sqlrelay.*;

public class SQLRelayStatement implements Statement {

	protected Object		networklock;

	protected SQLRelayDriver	drv;
	protected SQLRelayConnection	conn;
	protected SQLRelayResultSet	resultset;

	private SQLRConnection		sqlrcon;
	protected SQLRCursor		sqlrcur;

	private List<String>		batch;
	private boolean			closeoncompletion;
	private int			fetchdirection;
	private int			maxfieldsize;
	private int			maxrows;
	private boolean			poolable;
	protected int			updatecount;
	private boolean			escapeprocessing;
	private String			cursorname;


	public
	SQLRelayStatement(SQLRelayDriver driver) {
		this.drv=driver;
		drv.debugFunction(this);
		reset();
		drv.debugEnd();
	}

	private
	void reset() {
		drv.debugFunction(this);
		conn=null;
		networklock=null;
		sqlrcon=null;
		sqlrcur=null;
		batch=new ArrayList<String>();
		closeoncompletion=false;
		resultset=null;
		fetchdirection=ResultSet.FETCH_FORWARD;
		maxfieldsize=0;
		maxrows=0;
		poolable=false;
		updatecount=-1;
		escapeprocessing=true;
		cursorname=null;
		drv.debugEnd();
	}

	void setConnection(SQLRelayConnection connection) {
		this.conn=connection;
	}

	void setNetworkLock(Object networklock) {
		this.networklock=networklock;
	}

	void setSQLRConnection(SQLRConnection sqlrcon) {
		this.sqlrcon=sqlrcon;
	}

	void setSQLRCursor(SQLRCursor sqlrcur) {
		this.sqlrcur=sqlrcur;
	}

	SQLRCursor getSQLRCursor() {
		return sqlrcur;
	}

	SQLRConnection getSQLRConnection() {
		return sqlrcon;
	}

	public
	void addBatch(String sql) throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugPrintln("sql: "+sql);
		batch.add(sql);
		drv.debugEnd();
	}

	public
	void cancel() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		conn.throwFeatureNotSupportedException();
		drv.debugEnd();
	}

	public
	void clearBatch() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		batch.clear();
		drv.debugEnd();
	}

	public
	void clearWarnings() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugEnd();
	}

	public
	void close() throws SQLException {
		drv.debugFunction(this);
		if (resultset!=null) {
			resultset.close();
		} else {
			if (sqlrcur!=null) {
				synchronized (networklock) {
					sqlrcur.closeResultSet();
				}
			}
		}
		reset();
		drv.debugEnd();
	}

	public
	void closeOnCompletion() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		// I don't see how this can be used.  If it's set true then the
		// last ResultSet's close() should close the Statement.
		//
		// However, we can't know if a ResultSet is the last result set
		// until getMoreResults() returns false.  There's no guarantee
		// that an app will call that, and even if it does, it's likely
		// to call close() on the current ResultSet first.
		closeoncompletion=true;
		drv.debugEnd();
	}

	public
	boolean execute(String sql) throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();

		// debug
		drv.debugPrintln("sql: "+sql);

		// initialize results
		resultset=null;
		updatecount=-1;

		// process jdbc escape sequences
		if (escapeprocessing) {
			sql=conn.nativeSQL(sql);
		}

		// send the query
		boolean	result=false;
		synchronized (networklock) {
			result=sqlrcur.sendQuery(sql);
		}

		drv.debugPrintln("result: "+result);

		// handle results
		if (result) {

			updatecount=(int)sqlrcur.affectedRows();

			drv.debugPrintln("update count: "+updatecount);
			drv.debugPrintln("column count: "+sqlrcur.colCount());

			if (sqlrcur.colCount()>0) {
				createResultSet();
			}
		} else {
			conn.throwException(sqlrcur.errorMessage());
		}

		drv.debugEnd();
		return resultset!=null;
	}

	private
	void createResultSet() {
		resultset=new SQLRelayResultSet(drv);
		resultset.setNetworkLock(networklock);
		resultset.setStatement(this);
		resultset.setConnection(conn);
		resultset.setSQLRCursor(sqlrcur);
		resultset.setMaxFieldSize(maxfieldsize);
		resultset.setMaxRows(maxrows);
	}

	public
	boolean execute(String sql, int autogeneratedkeys)
						throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();

		conn.debugAutoGeneratedKeys(autogeneratedkeys);

		// catch unsupported options
		// we only support Statement.NO_GENERATED_KEYS,
		// but we can support this call if autogeneratedkeys isn't
		// Statement.RETURN_GENERATED_KEYS
		conn.throwAutoGeneratedKeysNotSupportedException(
							autogeneratedkeys);

		// execute
		boolean	retval=execute(sql);

		drv.debugEnd();
		return retval;
	}

	public
	boolean execute(String sql, int[] columnindexes)
						throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();

		// catch unsupported options
		// we only support Statement.NO_GENERATED_KEYS,
		// but we can support this call if there are no columnindexes
		if (columnindexes!=null && columnindexes.length>0) {
			conn.throwAutoGeneratedKeysNotSupportedException(
					Statement.RETURN_GENERATED_KEYS);
		}

		// execute
		boolean	retval=execute(sql);

		drv.debugEnd();
		return retval;
	}

	public
	boolean execute(String sql, String[] columnnames)
						throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();

		// catch unsupported options
		// we only support Statement.NO_GENERATED_KEYS,
		// but we can support this call if there are no columnnames
		if (columnnames!=null && columnnames.length>0) {
			conn.throwAutoGeneratedKeysNotSupportedException(
					Statement.RETURN_GENERATED_KEYS);
		}

		// execute
		boolean	retval=execute(sql);

		drv.debugEnd();
		return retval;
	}

	public
	int[] executeBatch() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();

		// debug
		drv.debugPrintln("batch size: "+batch.size());

		// execute each query in the batch
		int[]	retvals=new int[batch.size()];
		int	count=0;

		for (String sql: batch) {
			retvals[count++]=executeUpdate(sql);
		}

		drv.debugEnd();
		return retvals;
	}

	public
	ResultSet executeQuery(String sql) throws SQLException {
		drv.debugFunction(this);

		// execute
		execute(sql);

		drv.debugEnd();
		return resultset;
	}

	public
	int executeUpdate(String sql) throws SQLException {
		drv.debugFunction(this);

		// execute
		execute(sql);

		drv.debugEnd();
		return updatecount;
	}

	public
	int executeUpdate(String sql, int autogeneratedkeys)
						throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();

		conn.debugAutoGeneratedKeys(autogeneratedkeys);

		// catch unsupported options
		// we only support Statement.NO_GENERATED_KEYS,
		// but we can support this call if autogeneratedkeys isn't
		// Statement.RETURN_GENERATED_KEYS
		conn.throwAutoGeneratedKeysNotSupportedException(
							autogeneratedkeys);

		int	retval=executeUpdate(sql);

		drv.debugEnd();
		return retval;
	}

	public
	int executeUpdate(String sql, int[] columnindexes)
						throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();

		// catch unsupported options
		// we only support Statement.NO_GENERATED_KEYS,
		// but we can support this call if there are no columnindexes
		if (columnindexes!=null && columnindexes.length>0) {
			conn.throwAutoGeneratedKeysNotSupportedException(
					Statement.RETURN_GENERATED_KEYS);
		}

		// execute
		int	retval=executeUpdate(sql);

		drv.debugEnd();
		return retval;
	}

	public
	int executeUpdate(String sql, String[] columnnames)
						throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();

		// catch unsupported options
		// we only support Statement.NO_GENERATED_KEYS,
		// but we can support this call if there are no columnnames
		if (columnnames!=null && columnnames.length>0) {
			conn.throwAutoGeneratedKeysNotSupportedException(
					Statement.RETURN_GENERATED_KEYS);
		}

		// execute
		int	retval=executeUpdate(sql);

		drv.debugEnd();
		return retval;
	}

	public
	SQLRelayConnection getConnection() throws SQLException {
		return conn;
	}

	public
	int getFetchDirection() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		debugFetchDirection(fetchdirection);
		drv.debugEnd();
		return fetchdirection;
	}

	public
	int getFetchSize() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		int	rows=(int)sqlrcur.getResultSetBufferSize();
		drv.debugPrintln("fetch size: "+rows);
		drv.debugEnd();
		return rows;
	}

	public
	ResultSet getGeneratedKeys() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();

		if (resultset!=null) {
			resultset.close();
			resultset=null;
		}

		boolean	result=false;
		synchronized (networklock) {
			result=sqlrcur.getLastInsertIdList();
		}

		if (result) {

			drv.debugPrintln("colcount: "+sqlrcur.colCount());

			if (sqlrcur.colCount()>0) {
				resultset=new SQLRelayResultSet(drv);
				resultset.setNetworkLock(networklock);
				resultset.setStatement(this);
				resultset.setConnection(conn);
				resultset.setSQLRCursor(sqlrcur);
			}
		} else {
			conn.throwException(sqlrcur.errorMessage());
		}

		drv.debugEnd();
		return resultset;
	}

	public
	int getMaxFieldSize() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugPrintln("max field size: "+maxfieldsize);
		drv.debugEnd();
		return maxfieldsize;
	}

	public
	int getMaxRows() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugPrintln("max rows: "+maxrows);
		drv.debugEnd();
		return maxrows;
	}

	public
	boolean getMoreResults() throws SQLException {
		drv.debugFunction(this);
		boolean	gmr=getMoreResults(Statement.CLOSE_CURRENT_RESULT);
		drv.debugEnd();
		return gmr;
	}

	public
	boolean getMoreResults(int current) throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();

		debugResultSetHandling(current);

		// we only support CLOSE_CURRENT_RESULT and CLOSE_ALL_RESULTS
		// (and we handle them both the same way)
		throwResultSetHandlingNotSupportedException(current);

		boolean	retval=false;

		if (resultset!=null) {
			resultset.close();
			resultset=null;
		}
		updatecount=-1;

		if (sqlrcur.nextResultSet()) {
			createResultSet();
			retval=true;
		}

		drv.debugEnd();
		return retval;
	}

	public
	int getQueryTimeout() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		// NOTE: this gets the timeout at the connection level,
		// SQL Relay doesn't have a per-cursor timeout
		int	sec=sqlrcon.getResponseTimeoutSeconds();
		int	usec=sqlrcon.getResponseTimeoutMicroseconds();
		drv.debugPrintln("timeout seconds: "+sec);
		drv.debugPrintln("timeout microseconds: "+usec);
		int	seconds=sec;
		if (sec==-1 || usec==-1) {
			seconds=0;
		}
		drv.debugPrintln("seconds: "+seconds);
		drv.debugEnd();
		return seconds;
	}

	public
	ResultSet getResultSet() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugPrintln("result set: "+
				((resultset!=null)?"not null":"null"));
		drv.debugEnd();
		return resultset;
	}

	public
	int getResultSetConcurrency() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugEnd();
		// we only support CONCUR_READ_ONLY
		return ResultSet.CONCUR_READ_ONLY;
	}

	public
	int getResultSetHoldability() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugEnd();
		// we only support HOLD_CURSORS_OVER_COMMIT
		return ResultSet.HOLD_CURSORS_OVER_COMMIT;
	}

	public
	int getResultSetType() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugEnd();
		// we only support ResultSet.TYPE_SCROLL_INSENSITIVE and
		// ResultSet.TYPE_FORWARD_ONLY
		return (sqlrcur.getResultSetBufferSize()==0)?
					ResultSet.TYPE_SCROLL_INSENSITIVE:
					ResultSet.TYPE_FORWARD_ONLY;
	}

	public
	int getUpdateCount() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugPrintln("update count: "+updatecount);
		drv.debugEnd();
		return updatecount;
	}

	public
	SQLWarning getWarnings() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugEnd();
		return null;
	}

	public
	boolean isClosed() throws SQLException {
		drv.debugFunction(this);
		boolean	closed=(sqlrcur==null);
		drv.debugEnd();
		return closed;
	}

	public
	boolean isCloseOnCompletion() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugEnd();
		return false;
	}

	public
	boolean isPoolable() throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugEnd();
		return poolable;
	}

	public
	void setCursorName(String name) throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugPrintln("cursor name: "+name);
		cursorname=name;
		drv.debugEnd();
	}

	String getCursorName() {
		drv.debugFunction(this);
		drv.debugPrintln("cursor name: "+cursorname);
		drv.debugEnd();
		return cursorname;
	}

	public
	void setEscapeProcessing(boolean enable) throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugPrintln("escape processing: "+enable);
		escapeprocessing=enable;
		drv.debugEnd();
	}

	public
	void setFetchDirection(int direction) throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		debugFetchDirection(direction);
		fetchdirection=direction;
		drv.debugEnd();
	}

	public
	void setFetchSize(int rows) throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugPrintln("fetch size: "+rows);
		sqlrcur.setResultSetBufferSize(rows);
		drv.debugEnd();
	}

	public
	void setMaxFieldSize(int max) throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugPrintln("max field size: "+max);
		maxfieldsize=max;
		drv.debugEnd();
	}

	public
	void setMaxRows(int max) throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugPrintln("max rows: "+max);
		maxrows=max;
		drv.debugEnd();
	}

	public
	void setPoolable(boolean poolable) throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugPrintln("poolable: "+poolable);
		this.poolable=poolable;
		drv.debugEnd();
	}

	public
	void setQueryTimeout(int seconds) throws SQLException {
		drv.debugFunction(this);
		throwExceptionIfClosed();
		drv.debugPrintln("seconds: "+seconds);
		// NOTE: this sets the timeout at the connection level,
		// SQL Relay doesn't have a per-cursor timeout
		if (seconds==0) {
			sqlrcon.setResponseTimeout(-1,-1);
		} else {
			sqlrcon.setResponseTimeout(seconds,0);
		}
		drv.debugEnd();
	}

	private
	void debugFetchDirection(int fetchdirection) {
		 switch (fetchdirection) {
			case ResultSet.FETCH_FORWARD:
				drv.debugPrintln("fetch direction: "+
							"FETCH_FORWARD");
				break;
			case ResultSet.FETCH_REVERSE:
				drv.debugPrintln("fetch direction: "+
							"FETCH_REVERSE");
				break;
			case ResultSet.FETCH_UNKNOWN:
				drv.debugPrintln("fetch direction: "+
							"FETCH_UNKNOWN");
				break;
			default:
				drv.debugPrintln("fetch direction: "+
							"unknown - "+
							fetchdirection);
				break;
		}
	}

	private
	void debugResultSetHandling(int resultsethandling) {
		switch (resultsethandling) {
			case Statement.CLOSE_CURRENT_RESULT:	
				drv.debugPrintln("result handling: "+
							"CLOSE_CURRENT_RESULT");
				break;
			case Statement.KEEP_CURRENT_RESULT:
				drv.debugPrintln("result handling: "+
							"KEEP_CURRENT_RESULT");
				break;
			case Statement.CLOSE_ALL_RESULTS:
				drv.debugPrintln("result handling: "+
							"CLOSE_ALL_RESULTS");
				break;
			default:
				drv.debugPrintln("result handling: "+
							"unknown - "+
							fetchdirection);
				break;
		}
	}

	protected
	void throwExceptionIfClosed() throws SQLException {
		if (sqlrcur==null) {
			conn.throwException("statement is closed");
		}
	}

	void throwErrorMessageException() throws SQLException {
		String	err=sqlrcur.errorMessage();
		if (err==null) {
			err=sqlrcon.errorMessage();
		}
		conn.throwException(err);
	}

	private
	void throwResultSetHandlingNotSupportedException(
						int resultsethandling)
						throws SQLException {
		switch (resultsethandling) {
			case Statement.CLOSE_CURRENT_RESULT:	
				break;
			case Statement.KEEP_CURRENT_RESULT:
				drv.debugPrintln("not supported: "+
							"KEEP_CURRENT_RESULT");
				break;
			case Statement.CLOSE_ALL_RESULTS:
				break;
			default:
				drv.debugPrintln("not supported: "+
							"unknown - "+
							resultsethandling);
				break;
		}
	}

	public
	boolean isWrapperFor(Class<?> iface) throws SQLException {
		drv.debugFunction(this);
		drv.debugEnd();
		return (iface==SQLRCursor.class);
	}

	@SuppressWarnings({"unchecked"})
	public
	<T> T unwrap(Class<T> iface) throws SQLException {
		drv.debugFunction(this);
		drv.debugEnd();
		return (T)((iface==SQLRCursor.class)?sqlrcur:null);
	}
};
