package com.firstworks.sql;

import java.sql.*;
import java.util.List;
import java.util.ArrayList;

import com.firstworks.sqlrelay.*;

public class SQLRelayStatement implements Statement {

	private Connection		connection;
	private SQLRConnection		sqlrcon;
	protected SQLRCursor		sqlrcur;
	private List<String>		batch;
	private boolean			closeoncompletion;
	protected SQLRelayResultSet	resultset;
	private int			fetchdirection;
	private int			maxfieldsize;
	private int			maxrows;
	private boolean			poolable;
	protected int			updatecount;
	private boolean			escapeprocessing;
	protected SQLRelayDriver	driver;

	public SQLRelayStatement(SQLRelayDriver driver) {
		this.driver=driver;
		driver.debugStart("SQLRelayStatement");
		reset();
		driver.debugEnd();
	}

	private void	reset() {
		driver.debugFunction();
		connection=null;
		sqlrcon=null;
		sqlrcur=null;
		batch=new ArrayList<String>();
		closeoncompletion=false;
		resultset=null;
		fetchdirection=ResultSet.FETCH_FORWARD;
		maxfieldsize=0;
		maxrows=0;
		poolable=false;
		updatecount=-1;
		escapeprocessing=true;
		driver.debugEnd();
	}

	public void	setConnection(Connection connection) {
		driver.debugFunction();
		this.connection=connection;
		driver.debugEnd();
	}

	public void	setSQLRConnection(SQLRConnection sqlrcon) {
		driver.debugFunction();
		this.sqlrcon=sqlrcon;
		driver.debugEnd();
	}

	public void	setSQLRCursor(SQLRCursor sqlrcur) {
		driver.debugFunction();
		this.sqlrcur=sqlrcur;
		driver.debugEnd();
	}

	public void 	addBatch(String sql) throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		batch.add(sql);
		driver.debugEnd();
	}

	public void 	cancel() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		// FIXME: maybe we can support this somehow?
		driver.debugEnd();
	}

	public void 	clearBatch() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		batch.clear();
		driver.debugEnd();
	}

	public void 	clearWarnings() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		driver.debugEnd();
	}

	public void 	close() throws SQLException {
		driver.debugFunction();
		if (resultset!=null) {
			resultset.close();
		}
		reset();
		driver.debugEnd();
	}

	public void 	closeOnCompletion() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		closeoncompletion=true;
		driver.debugEnd();
	}

	public boolean 	execute(String sql) throws SQLException {
		driver.debugFunction();
		driver.debugPrintln("sql: "+sql);

		throwExceptionIfClosed();

		// FIXME: handle timeout
		resultset=null;
		updatecount=-1;

		boolean	result=sqlrcur.sendQuery(sql);

		driver.debugPrintln("result: "+result);

		if (result) {

			updatecount=(int)sqlrcur.affectedRows();

			driver.debugPrintln("updatecount: "+updatecount);
			driver.debugPrintln("colcount: "+sqlrcur.colCount());

			if (sqlrcur.colCount()>0) {
				resultset=new SQLRelayResultSet(driver);
				resultset.setStatement(this);
				resultset.setSQLRCursor(sqlrcur);
			}
		} else {
			throwErrorMessageException();
		}
		driver.debugEnd();
		return result;
	}

	public boolean 	execute(String sql, int autoGeneratedKeys)
						throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		driver.debugEnd();
		return false;
	}

	public boolean 	execute(String sql, int[] columnIndexes)
						throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		driver.debugEnd();
		return false;
	}

	public boolean 	execute(String sql, String[] columnNames)
						throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		driver.debugEnd();
		return false;
	}

	public int[] 	executeBatch() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		// FIXME: handle timeout
		int[]	results=new int[batch.size()];
		int	count=0;
		for (String sql: batch) {
			results[count++]=executeUpdate(sql);
		}
		driver.debugEnd();
		return results;
	}

	public ResultSet 	executeQuery(String sql) throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		// FIXME: handle timeout
		resultset=null;
		updatecount=-1;
		if (sqlrcur.sendQuery(sql)) {
			resultset=new SQLRelayResultSet(driver);
			resultset.setStatement(this);
			resultset.setSQLRCursor(sqlrcur);
		} else {
			throw new SQLException(sqlrcur.errorMessage());
		}
		driver.debugEnd();
		return resultset;
	}

	public int 	executeUpdate(String sql) throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		// FIXME: handle timeout
		resultset=null;
		updatecount=-1;
		if (sqlrcur.sendQuery(sql)) {
			updatecount=(int)sqlrcur.affectedRows();
		} else {
			throwErrorMessageException();
		}
		driver.debugEnd();
		return updatecount;
	}

	public int 	executeUpdate(String sql, int autoGeneratedKeys)
						throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		driver.debugEnd();
		return 0;
	}

	public int 	executeUpdate(String sql, int[] columnIndexes)
						throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		driver.debugEnd();
		return 0;
	}

	public int 	executeUpdate(String sql, String[] columnNames)
						throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		driver.debugEnd();
		return 0;
	}

	public Connection 	getConnection() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		driver.debugEnd();
		return connection;
	}

	public int 	getFetchDirection() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		driver.debugEnd();
		return fetchdirection;
	}

	public int 	getFetchSize() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		int	rsbs=(int)sqlrcur.getResultSetBufferSize();
		driver.debugEnd();
		return rsbs;
	}

	public ResultSet 	getGeneratedKeys() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		// FIXME: maybe we can support this somehow?
		driver.debugEnd();
		return null;
	}

	public int 	getMaxFieldSize() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		driver.debugEnd();
		return maxfieldsize;
	}

	public int 	getMaxRows() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		driver.debugEnd();
		return maxrows;
	}

	public boolean 	getMoreResults() throws SQLException {
		driver.debugFunction();
		boolean	gmr=getMoreResults(Statement.CLOSE_CURRENT_RESULT);
		driver.debugEnd();
		return gmr;
	}

	public boolean 	getMoreResults(int current) throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		switch (current) {
			case Statement.CLOSE_CURRENT_RESULT:
				if (resultset!=null) {
					resultset.close();
					resultset=null;
					updatecount=-1;
				}
				// FIXME: we could support this...
				driver.debugEnd();
				return false;
			case Statement.KEEP_CURRENT_RESULT:
				throwFeatureNotSupportedException();
				driver.debugEnd();
				return false;
			case Statement.CLOSE_ALL_RESULTS:
				throwFeatureNotSupportedException();
				driver.debugEnd();
				return false;
			default:
				throwFeatureNotSupportedException();
				driver.debugEnd();
				return false;
		}
	}

	public int 	getQueryTimeout() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		// FIXME: this can be supported
		//return sqlrcon.getResponseTimeout();
		driver.debugEnd();
		return 0;
	}

	public ResultSet 	getResultSet() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		driver.debugEnd();
		return resultset;
	}

	public int 	getResultSetConcurrency() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		// FIXME: is this correct?
		driver.debugEnd();
		return ResultSet.CONCUR_READ_ONLY;
	}

	public int 	getResultSetHoldability() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		// FIXME: is this correct?
		driver.debugEnd();
		return ResultSet.CLOSE_CURSORS_AT_COMMIT;
	}

	public int 	getResultSetType() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		driver.debugEnd();
		return ResultSet.TYPE_FORWARD_ONLY;
	}

	public int 	getUpdateCount() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		driver.debugPrintln("updatecount="+updatecount);
		driver.debugEnd();
		return updatecount;
	}

	public SQLWarning 	getWarnings() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		driver.debugEnd();
		return null;
	}

	public boolean 	isClosed() throws SQLException {
		driver.debugFunction();
		boolean	closed=(sqlrcur==null);
		driver.debugEnd();
		return closed;
	}

	public boolean 	isCloseOnCompletion() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		driver.debugEnd();
		return false;
	}

	public boolean 	isPoolable() throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		driver.debugEnd();
		return poolable;
	}

	public void 	setCursorName(String name) throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		throwFeatureNotSupportedException();
		driver.debugEnd();
	}

	public void 	setEscapeProcessing(boolean enable)
						throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		escapeprocessing=enable;
		// FIXME: do something with this...
		driver.debugEnd();
	}

	public void 	setFetchDirection(int direction) throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		fetchdirection=direction;
		driver.debugEnd();
	}

	public void 	setFetchSize(int rows) throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		sqlrcur.setResultSetBufferSize(rows);
		driver.debugEnd();
	}

	public void 	setMaxFieldSize(int max) throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		maxfieldsize=max;
		driver.debugEnd();
	}

	public void 	setMaxRows(int max) throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		maxrows=max;
		driver.debugEnd();
	}

	public void 	setPoolable(boolean poolable) throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		this.poolable=poolable;
		driver.debugEnd();
	}

	public void 	setQueryTimeout(int seconds) throws SQLException {
		driver.debugFunction();
		throwExceptionIfClosed();
		// FIXME: hmm... this is at the connection level
		sqlrcon.setResponseTimeout(seconds,0);
		driver.debugEnd();
	}

	public boolean	isWrapperFor(Class<?> iface) throws SQLException {
		driver.debugFunction();
		driver.debugEnd();
		return (iface==SQLRCursor.class);
	}

	@SuppressWarnings({"unchecked"})
	public <T> T	unwrap(Class<T> iface) throws SQLException {
		driver.debugFunction();
		driver.debugEnd();
		return (T)((iface==SQLRCursor.class)?sqlrcur:null);
	}

	protected void throwExceptionIfClosed() throws SQLException {
		if (sqlrcur==null) {
			throwException("statement is closed");
		}
	}

	protected void throwErrorMessageException() throws SQLException {
		throwException(sqlrcur.errorMessage());
	}

	protected void throwFeatureNotSupportedException() throws SQLException {
		driver.debugZeroIndent();
		throw new SQLFeatureNotSupportedException();
	}

	protected void throwException(String reason) throws SQLException {
		driver.debugZeroIndent();
		throw new SQLException(reason);
	}

	public SQLRCursor getSQLRCursor() {
		driver.debugFunction();
		driver.debugEnd();
		return sqlrcur;
	}
};
