top_builddir = ../..

include ../../config.mk

.SUFFIXES: .wt .html.in .html

SRCS = getting-started-with-firebird.wt \
	getting-started-with-ibm-db2.wt \
	getting-started-with-mysql.wt \
	getting-started-with-odbc-on-non-ms.wt \
	getting-started-with-oracle.wt \
	getting-started-with-postgresql.wt \
	getting-started-with-sapsybase.wt \
	getting-started-with-sqlite.wt \
	initializing-sybase-ase-11033-on-linux.wt \
	initializing-sybase-ase-1192-on-linux.wt \
	initializing-sybase-ase-125-on-linux.wt \
	initializing-sybase-ase-1251-on-linux.wt \
	initializing-sybase-ase-1252-on-linux.wt \
	initializing-sybase-ase-1502-on-linux.wt \
	initializing-sybase-ase-155-on-linux.wt \
	initializing-sybase-ase-157-on-linux.wt \
	installing-ibm-db2-101-express-on-linux.wt \
	installing-ibm-db2-105-express-on-linux.wt \
	installing-ibm-db2-81-enterprise-on.wt \
	installing-ibm-db2-82-personal-on-linux.wt \
	installing-ibm-db2-824-express-on-linux.wt \
	installing-ibm-db2-91-express-on-linux.wt \
	installing-ibm-db2-971-express-on-linux.wt \
	installing-ibm-db2-enterprise-72-on.wt \
	installing-oracle-10g-on-fedora-core-1.wt \
	installing-oracle-10g-on-fedora-core-2.wt \
	installing-oracle-10g-on-fedora-core-3.wt \
	installing-oracle-10g-on-fedora-core-5.wt \
	installing-oracle-11g-on-fedora-12.wt \
	installing-oracle-11g-on-fedora-13.wt \
	installing-oracle-12c-on-fedora-19.wt \
	installing-oracle-805-on-redhat-52.wt \
	installing-oracle-816-or-817-on-redhat.wt \
	installing-oracle-816-or-817-on-redhat_12.wt \
	installing-oracle-9ir2-on-fedora-core-1.wt \
	installing-oracle-9ir2-on-redhat-8.wt \
	installing-oracle-9ir2-on-redhat-9.wt

INS = getting-started-with-firebird.html.in \
	getting-started-with-ibm-db2.html.in \
	getting-started-with-mysql.html.in \
	getting-started-with-odbc-on-non-ms.html.in \
	getting-started-with-oracle.html.in \
	getting-started-with-postgresql.html.in \
	getting-started-with-sapsybase.html.in \
	getting-started-with-sqlite.html.in \
	header.html.in \
	initializing-sybase-ase-11033-on-linux.html.in \
	initializing-sybase-ase-1192-on-linux.html.in \
	initializing-sybase-ase-1251-on-linux.html.in \
	initializing-sybase-ase-1252-on-linux.html.in \
	initializing-sybase-ase-125-on-linux.html.in \
	initializing-sybase-ase-1502-on-linux.html.in \
	initializing-sybase-ase-155-on-linux.html.in \
	initializing-sybase-ase-157-on-linux.html.in \
	installing-ibm-db2-101-express-on-linux.html.in \
	installing-ibm-db2-105-express-on-linux.html.in \
	installing-ibm-db2-81-enterprise-on.html.in \
	installing-ibm-db2-824-express-on-linux.html.in \
	installing-ibm-db2-82-personal-on-linux.html.in \
	installing-ibm-db2-91-express-on-linux.html.in \
	installing-ibm-db2-971-express-on-linux.html.in \
	installing-ibm-db2-enterprise-72-on.html.in \
	installing-oracle-10g-on-fedora-core-1.html.in \
	installing-oracle-10g-on-fedora-core-2.html.in \
	installing-oracle-10g-on-fedora-core-3.html.in \
	installing-oracle-10g-on-fedora-core-5.html.in \
	installing-oracle-11g-on-fedora-12.html.in \
	installing-oracle-11g-on-fedora-13.html.in \
	installing-oracle-12c-on-fedora-19.html.in \
	installing-oracle-805-on-redhat-52.html.in \
	installing-oracle-816-or-817-on-redhat_12.html.in \
	installing-oracle-816-or-817-on-redhat.html.in \
	installing-oracle-9ir2-on-fedora-core-1.html.in \
	installing-oracle-9ir2-on-redhat-8.html.in \
	installing-oracle-9ir2-on-redhat-9.html.in

# the subset of INS that wt generates from SRCS; the rest are checkout files
WTOBJS = getting-started-with-firebird.html.in \
	getting-started-with-ibm-db2.html.in \
	getting-started-with-mysql.html.in \
	getting-started-with-odbc-on-non-ms.html.in \
	getting-started-with-oracle.html.in \
	getting-started-with-postgresql.html.in \
	getting-started-with-sapsybase.html.in \
	getting-started-with-sqlite.html.in \
	initializing-sybase-ase-11033-on-linux.html.in \
	initializing-sybase-ase-1192-on-linux.html.in \
	initializing-sybase-ase-1251-on-linux.html.in \
	initializing-sybase-ase-1252-on-linux.html.in \
	initializing-sybase-ase-125-on-linux.html.in \
	initializing-sybase-ase-1502-on-linux.html.in \
	initializing-sybase-ase-155-on-linux.html.in \
	initializing-sybase-ase-157-on-linux.html.in \
	installing-ibm-db2-101-express-on-linux.html.in \
	installing-ibm-db2-105-express-on-linux.html.in \
	installing-ibm-db2-81-enterprise-on.html.in \
	installing-ibm-db2-824-express-on-linux.html.in \
	installing-ibm-db2-82-personal-on-linux.html.in \
	installing-ibm-db2-91-express-on-linux.html.in \
	installing-ibm-db2-971-express-on-linux.html.in \
	installing-ibm-db2-enterprise-72-on.html.in \
	installing-oracle-10g-on-fedora-core-1.html.in \
	installing-oracle-10g-on-fedora-core-2.html.in \
	installing-oracle-10g-on-fedora-core-3.html.in \
	installing-oracle-10g-on-fedora-core-5.html.in \
	installing-oracle-11g-on-fedora-12.html.in \
	installing-oracle-11g-on-fedora-13.html.in \
	installing-oracle-12c-on-fedora-19.html.in \
	installing-oracle-805-on-redhat-52.html.in \
	installing-oracle-816-or-817-on-redhat_12.html.in \
	installing-oracle-816-or-817-on-redhat.html.in \
	installing-oracle-9ir2-on-fedora-core-1.html.in \
	installing-oracle-9ir2-on-redhat-8.html.in \
	installing-oracle-9ir2-on-redhat-9.html.in

OBJS = getting-started-with-firebird.html \
	getting-started-with-ibm-db2.html \
	getting-started-with-mysql.html \
	getting-started-with-odbc-on-non-ms.html \
	getting-started-with-oracle.html \
	getting-started-with-postgresql.html \
	getting-started-with-sapsybase.html \
	getting-started-with-sqlite.html \
	header.html \
	initializing-sybase-ase-11033-on-linux.html \
	initializing-sybase-ase-1192-on-linux.html \
	initializing-sybase-ase-1251-on-linux.html \
	initializing-sybase-ase-1252-on-linux.html \
	initializing-sybase-ase-125-on-linux.html \
	initializing-sybase-ase-1502-on-linux.html \
	initializing-sybase-ase-155-on-linux.html \
	initializing-sybase-ase-157-on-linux.html \
	installing-ibm-db2-101-express-on-linux.html \
	installing-ibm-db2-105-express-on-linux.html \
	installing-ibm-db2-81-enterprise-on.html \
	installing-ibm-db2-824-express-on-linux.html \
	installing-ibm-db2-82-personal-on-linux.html \
	installing-ibm-db2-91-express-on-linux.html \
	installing-ibm-db2-971-express-on-linux.html \
	installing-ibm-db2-enterprise-72-on.html \
	installing-oracle-10g-on-fedora-core-1.html \
	installing-oracle-10g-on-fedora-core-2.html \
	installing-oracle-10g-on-fedora-core-3.html \
	installing-oracle-10g-on-fedora-core-5.html \
	installing-oracle-11g-on-fedora-12.html \
	installing-oracle-11g-on-fedora-13.html \
	installing-oracle-12c-on-fedora-19.html \
	installing-oracle-805-on-redhat-52.html \
	installing-oracle-816-or-817-on-redhat_12.html \
	installing-oracle-816-or-817-on-redhat.html \
	installing-oracle-9ir2-on-fedora-core-1.html \
	installing-oracle-9ir2-on-redhat-8.html \
	installing-oracle-9ir2-on-redhat-9.html

# fragments the pages here include; editing one rebuilds all of them
FRAGMENTS = ../contentend.html \
	../contentstart.html \
	../title.html \
	../tracker.html \
	footer.html \
	header.html.in \
	projectheader.html

.PRECIOUS: $(INS)

.wt.html.in:
	wt -i $< -o $@

.html.in.html:
	$(SSI) $<

all: $(OBJS)
	$(CHMOD) 644 $(OBJS)

$(OBJS): $(FRAGMENTS)

clean:
	$(RM) $(OBJS) $(WTOBJS)
