<html><pre><?php
	# Copyright (c) David Muse
	# See the file COPYING for more information.

	include("./assert.php");


	$host="sqlrelay";
	$port=9000;
	$socket="/tmp/test.socket";
	$user="db2inst1";
	$password="testpassword";

	# instantiation
	$con=sqlrcon_alloc($host,$port,$socket,$user,$password,0,1);
	$cur=sqlrcur_alloc($con);

	# get database type
	echo("IDENTIFY: \n");
	assertEqual(sqlrcon_identify($con),"db2");
	echo("\n");

	# ping
	echo("PING: \n");
	assertTrue(sqlrcon_ping($con));
	echo("\n");

	# drop existing table
	sqlrcur_sendQuery($cur,"drop table testtable");

	echo("CREATE TEMPTABLE: \n");
	assertTrue(sqlrcur_sendQuery($cur,"create table testtable (testsmallint smallint, testint integer, testbigint bigint, testdecimal decimal(10,2), testreal real, testdouble double, testchar char(40), testvarchar varchar(40), testdate date, testtime time, testtimestamp timestamp)"));
	echo("\n");

	echo("INSERT: \n");
	assertTrue(sqlrcur_sendQuery($cur,"insert into testtable values (1,1,1,1.1,1.1,1.1,'testchar1','testvarchar1','01/01/2001','01:00:00',NULL)"));
	echo("\n");

	echo("BIND BY POSITION: \n");
	sqlrcur_prepareQuery($cur,"insert into testtable values (?,?,?,?,?,?,?,?,?,?,NULL)");
	assertEqual(sqlrcur_countBindVariables($cur),10);
	sqlrcur_inputBind($cur,"1",2);
	sqlrcur_inputBind($cur,"2",2);
	sqlrcur_inputBind($cur,"3",2);
	sqlrcur_inputBind($cur,"4",2.2,4,2);
	sqlrcur_inputBind($cur,"5",2.2,4,2);
	sqlrcur_inputBind($cur,"6",2.2,4,2);
	sqlrcur_inputBind($cur,"7","testchar2");
	sqlrcur_inputBind($cur,"8","testvarchar2");
	sqlrcur_inputBind($cur,"9","01/01/2002");
	sqlrcur_inputBind($cur,"10","02:00:00");
	assertTrue(sqlrcur_executeQuery($cur));
	sqlrcur_clearBinds($cur);
	sqlrcur_inputBind($cur,"1",3);
	sqlrcur_inputBind($cur,"2",3);
	sqlrcur_inputBind($cur,"3",3);
	sqlrcur_inputBind($cur,"4",3.3,4,2);
	sqlrcur_inputBind($cur,"5",3.3,4,2);
	sqlrcur_inputBind($cur,"6",3.3,4,2);
	sqlrcur_inputBind($cur,"7","testchar3");
	sqlrcur_inputBind($cur,"8","testvarchar3");
	sqlrcur_inputBind($cur,"9","01/01/2003");
	sqlrcur_inputBind($cur,"10","03:00:00");
	assertTrue(sqlrcur_executeQuery($cur));
	echo("\n");

	echo("ARRAY OF BINDS BY POSITION: \n");
	sqlrcur_clearBinds($cur);
	$bindvars=array("1","2","3","4","5","6","7","8","9","10");
	$bindvals=array("4","4","4","4.4","4.4","4.4",
			"testchar4","testvarchar4","01/01/2004","04:00:00");
	sqlrcur_inputBinds($cur,$bindvars,$bindvals);
	assertTrue(sqlrcur_executeQuery($cur));
	echo("\n");

	echo("INSERT: \n");
	assertTrue(sqlrcur_sendQuery($cur,"insert into testtable values (5,5,5,5.5,5.5,5.5,'testchar5','testvarchar5','01/01/2005','05:00:00',NULL)"));
	assertTrue(sqlrcur_sendQuery($cur,"insert into testtable values (6,6,6,6.6,6.6,6.6,'testchar6','testvarchar6','01/01/2006','06:00:00',NULL)"));
	assertTrue(sqlrcur_sendQuery($cur,"insert into testtable values (7,7,7,7.7,7.7,7.7,'testchar7','testvarchar7','01/01/2007','07:00:00',NULL)"));
	assertTrue(sqlrcur_sendQuery($cur,"insert into testtable values (8,8,8,8.8,8.8,8.8,'testchar8','testvarchar8','01/01/2008','08:00:00',NULL)"));
	echo("\n");

	echo("AFFECTED ROWS: \n");
	assertEqual(sqlrcur_affectedRows($cur),1);
	echo("\n");

	echo("STORED PROCEDURE: \n");
	sqlrcur_sendQuery($cur,"drop procedure testproc");
	assertTrue(sqlrcur_sendQuery($cur,"create procedure testproc(in invar int, out outvar int) language sql begin set outvar = invar; end"));
	sqlrcur_prepareQuery($cur,"call testproc(?,?)");
	sqlrcur_inputBind($cur,"1",5);
	sqlrcur_defineOutputBindString($cur,"2",10);
	assertTrue(sqlrcur_executeQuery($cur));
	assertEqual(sqlrcur_getOutputBindString($cur,"2"),"5");
	assertTrue(sqlrcur_sendQuery($cur,"drop procedure testproc"));
	echo("\n");

	echo("SELECT: \n");
	assertTrue(sqlrcur_sendQuery($cur,"select * from testtable order by testsmallint"));
	echo("\n");

	echo("COLUMN COUNT: \n");
	assertEqual(sqlrcur_colCount($cur),11);
	echo("\n");

	echo("COLUMN NAMES: \n");
	assertEqual(sqlrcur_getColumnName($cur,0),"TESTSMALLINT");
	assertEqual(sqlrcur_getColumnName($cur,1),"TESTINT");
	assertEqual(sqlrcur_getColumnName($cur,2),"TESTBIGINT");
	assertEqual(sqlrcur_getColumnName($cur,3),"TESTDECIMAL");
	assertEqual(sqlrcur_getColumnName($cur,4),"TESTREAL");
	assertEqual(sqlrcur_getColumnName($cur,5),"TESTDOUBLE");
	assertEqual(sqlrcur_getColumnName($cur,6),"TESTCHAR");
	assertEqual(sqlrcur_getColumnName($cur,7),"TESTVARCHAR");
	assertEqual(sqlrcur_getColumnName($cur,8),"TESTDATE");
	assertEqual(sqlrcur_getColumnName($cur,9),"TESTTIME");
	assertEqual(sqlrcur_getColumnName($cur,10),"TESTTIMESTAMP");
	$cols=sqlrcur_getColumnNames($cur);
	assertEqual($cols[0],"TESTSMALLINT");
	assertEqual($cols[1],"TESTINT");
	assertEqual($cols[2],"TESTBIGINT");
	assertEqual($cols[3],"TESTDECIMAL");
	assertEqual($cols[4],"TESTREAL");
	assertEqual($cols[5],"TESTDOUBLE");
	assertEqual($cols[6],"TESTCHAR");
	assertEqual($cols[7],"TESTVARCHAR");
	assertEqual($cols[8],"TESTDATE");
	assertEqual($cols[9],"TESTTIME");
	assertEqual($cols[10],"TESTTIMESTAMP");
	echo("\n");

	echo("COLUMN TYPES: \n");
	assertEqual(sqlrcur_getColumnType($cur,0),"SMALLINT");
	assertEqual(sqlrcur_getColumnType($cur,"TESTSMALLINT"),"SMALLINT");
	assertEqual(sqlrcur_getColumnType($cur,1),"INTEGER");
	assertEqual(sqlrcur_getColumnType($cur,"TESTINT"),"INTEGER");
	assertEqual(sqlrcur_getColumnType($cur,2),"BIGINT");
	assertEqual(sqlrcur_getColumnType($cur,"TESTBIGINT"),"BIGINT");
	assertEqual(sqlrcur_getColumnType($cur,3),"DECIMAL");
	assertEqual(sqlrcur_getColumnType($cur,"TESTDECIMAL"),"DECIMAL");
	assertEqual(sqlrcur_getColumnType($cur,4),"REAL");
	assertEqual(sqlrcur_getColumnType($cur,"TESTREAL"),"REAL");
	assertEqual(sqlrcur_getColumnType($cur,5),"DOUBLE");
	assertEqual(sqlrcur_getColumnType($cur,"TESTDOUBLE"),"DOUBLE");
	assertEqual(sqlrcur_getColumnType($cur,6),"CHAR");
	assertEqual(sqlrcur_getColumnType($cur,"TESTCHAR"),"CHAR");
	assertEqual(sqlrcur_getColumnType($cur,7),"VARCHAR");
	assertEqual(sqlrcur_getColumnType($cur,"TESTVARCHAR"),"VARCHAR");
	assertEqual(sqlrcur_getColumnType($cur,8),"DATE");
	assertEqual(sqlrcur_getColumnType($cur,"TESTDATE"),"DATE");
	assertEqual(sqlrcur_getColumnType($cur,9),"TIME");
	assertEqual(sqlrcur_getColumnType($cur,"TESTTIME"),"TIME");
	assertEqual(sqlrcur_getColumnType($cur,10),"TIMESTAMP");
	assertEqual(sqlrcur_getColumnType($cur,"TESTTIMESTAMP"),"TIMESTAMP");
	echo("\n");

	echo("COLUMN LENGTH: \n");
	assertEqual(sqlrcur_getColumnLength($cur,0),2);
	assertEqual(sqlrcur_getColumnLength($cur,"TESTSMALLINT"),2);
	assertEqual(sqlrcur_getColumnLength($cur,1),4);
	assertEqual(sqlrcur_getColumnLength($cur,"TESTINT"),4);
	assertEqual(sqlrcur_getColumnLength($cur,2),8);
	assertEqual(sqlrcur_getColumnLength($cur,"TESTBIGINT"),8);
	assertEqual(sqlrcur_getColumnLength($cur,3),12);
	assertEqual(sqlrcur_getColumnLength($cur,"TESTDECIMAL"),12);
	assertEqual(sqlrcur_getColumnLength($cur,4),4);
	assertEqual(sqlrcur_getColumnLength($cur,"TESTREAL"),4);
	assertEqual(sqlrcur_getColumnLength($cur,5),8);
	assertEqual(sqlrcur_getColumnLength($cur,"TESTDOUBLE"),8);
	assertEqual(sqlrcur_getColumnLength($cur,6),40);
	assertEqual(sqlrcur_getColumnLength($cur,"TESTCHAR"),40);
	assertEqual(sqlrcur_getColumnLength($cur,7),40);
	assertEqual(sqlrcur_getColumnLength($cur,"TESTVARCHAR"),40);
	assertEqual(sqlrcur_getColumnLength($cur,8),6);
	assertEqual(sqlrcur_getColumnLength($cur,"TESTDATE"),6);
	assertEqual(sqlrcur_getColumnLength($cur,9),6);
	assertEqual(sqlrcur_getColumnLength($cur,"TESTTIME"),6);
	assertEqual(sqlrcur_getColumnLength($cur,10),16);
	assertEqual(sqlrcur_getColumnLength($cur,"TESTTIMESTAMP"),16);
	echo("\n");

	echo("LONGEST COLUMN: \n");
	assertEqual(sqlrcur_getLongest($cur,0),1);
	assertEqual(sqlrcur_getLongest($cur,"TESTSMALLINT"),1);
	assertEqual(sqlrcur_getLongest($cur,1),1);
	assertEqual(sqlrcur_getLongest($cur,"TESTINT"),1);
	assertEqual(sqlrcur_getLongest($cur,2),1);
	assertEqual(sqlrcur_getLongest($cur,"TESTBIGINT"),1);
	assertEqual(sqlrcur_getLongest($cur,3),4);
	assertEqual(sqlrcur_getLongest($cur,"TESTDECIMAL"),4);
	#assertEqual(sqlrcur_getLongest($cur,4),3);
	#assertEqual(sqlrcur_getLongest($cur,"TESTREAL"),3);
	#assertEqual(sqlrcur_getLongest($cur,5),3);
	#assertEqual(sqlrcur_getLongest($cur,"TESTDOUBLE"),3);
	assertEqual(sqlrcur_getLongest($cur,6),40);
	assertEqual(sqlrcur_getLongest($cur,"TESTCHAR"),40);
	assertEqual(sqlrcur_getLongest($cur,7),12);
	assertEqual(sqlrcur_getLongest($cur,"TESTVARCHAR"),12);
	assertEqual(sqlrcur_getLongest($cur,8),10);
	assertEqual(sqlrcur_getLongest($cur,"TESTDATE"),10);
	assertEqual(sqlrcur_getLongest($cur,9),8);
	assertEqual(sqlrcur_getLongest($cur,"TESTTIME"),8);
	echo("\n");

	echo("ROW COUNT: \n");
	assertEqual(sqlrcur_rowCount($cur),8);
	echo("\n");

	echo("TOTAL ROWS: \n");
	assertEqual(sqlrcur_totalRows($cur),0);
	echo("\n");

	echo("FIRST ROW INDEX: \n");
	assertEqual(sqlrcur_firstRowIndex($cur),0);
	echo("\n");

	echo("END OF RESULT SET: \n");
	assertTrue(sqlrcur_endOfResultSet($cur));
	echo("\n");

	echo("FIELDS BY INDEX: \n");
	assertEqual(sqlrcur_getField($cur,0,0),"1");
	assertEqual(sqlrcur_getField($cur,0,1),"1");
	assertEqual(sqlrcur_getField($cur,0,2),"1");
	assertEqual(sqlrcur_getField($cur,0,3),"1.10");
	#assertEqual(sqlrcur_getField($cur,0,4),"1.1");
	#assertEqual(sqlrcur_getField($cur,0,5),"1.1");
	assertEqual(sqlrcur_getField($cur,0,6),"testchar1                               ");
	assertEqual(sqlrcur_getField($cur,0,7),"testvarchar1");
	assertEqual(sqlrcur_getField($cur,0,8),"2001-01-01");
	assertEqual(sqlrcur_getField($cur,0,9),"01:00:00");
	echo("\n");
	assertEqual(sqlrcur_getField($cur,7,0),"8");
	assertEqual(sqlrcur_getField($cur,7,1),"8");
	assertEqual(sqlrcur_getField($cur,7,2),"8");
	assertEqual(sqlrcur_getField($cur,7,3),"8.80");
	#assertEqual(sqlrcur_getField($cur,7,4),"8.8");
	#assertEqual(sqlrcur_getField($cur,7,5),"8.8");
	assertEqual(sqlrcur_getField($cur,7,6),"testchar8                               ");
	assertEqual(sqlrcur_getField($cur,7,7),"testvarchar8");
	assertEqual(sqlrcur_getField($cur,7,8),"2008-01-01");
	assertEqual(sqlrcur_getField($cur,7,9),"08:00:00");
	echo("\n");

	echo("FIELD LENGTHS BY INDEX: \n");
	assertEqual(sqlrcur_getFieldLength($cur,0,0),1);
	assertEqual(sqlrcur_getFieldLength($cur,0,1),1);
	assertEqual(sqlrcur_getFieldLength($cur,0,2),1);
	assertEqual(sqlrcur_getFieldLength($cur,0,3),4);
	#assertEqual(sqlrcur_getFieldLength($cur,0,4),3);
	#assertEqual(sqlrcur_getFieldLength($cur,0,5),3);
	assertEqual(sqlrcur_getFieldLength($cur,0,6),40);
	assertEqual(sqlrcur_getFieldLength($cur,0,7),12);
	assertEqual(sqlrcur_getFieldLength($cur,0,8),10);
	assertEqual(sqlrcur_getFieldLength($cur,0,9),8);
	echo("\n");
	assertEqual(sqlrcur_getFieldLength($cur,7,0),1);
	assertEqual(sqlrcur_getFieldLength($cur,7,1),1);
	assertEqual(sqlrcur_getFieldLength($cur,7,2),1);
	assertEqual(sqlrcur_getFieldLength($cur,7,3),4);
	#assertEqual(sqlrcur_getFieldLength($cur,7,4),3);
	#assertEqual(sqlrcur_getFieldLength($cur,7,5),3);
	assertEqual(sqlrcur_getFieldLength($cur,7,6),40);
	assertEqual(sqlrcur_getFieldLength($cur,7,7),12);
	assertEqual(sqlrcur_getFieldLength($cur,7,8),10);
	assertEqual(sqlrcur_getFieldLength($cur,7,9),8);
	echo("\n");

	echo("FIELDS BY NAME: \n");
	assertEqual(sqlrcur_getField($cur,0,"TESTSMALLINT"),"1");
	assertEqual(sqlrcur_getField($cur,0,"TESTINT"),"1");
	assertEqual(sqlrcur_getField($cur,0,"TESTBIGINT"),"1");
	assertEqual(sqlrcur_getField($cur,0,"TESTDECIMAL"),"1.10");
	#assertEqual(sqlrcur_getField($cur,0,"TESTREAL"),"1.1");
	#assertEqual(sqlrcur_getField($cur,0,"TESTDOUBLE"),"1.1");
	assertEqual(sqlrcur_getField($cur,0,"TESTCHAR"),"testchar1                               ");
	assertEqual(sqlrcur_getField($cur,0,"TESTVARCHAR"),"testvarchar1");
	assertEqual(sqlrcur_getField($cur,0,"TESTDATE"),"2001-01-01");
	assertEqual(sqlrcur_getField($cur,0,"TESTTIME"),"01:00:00");
	echo("\n");
	assertEqual(sqlrcur_getField($cur,7,"TESTSMALLINT"),"8");
	assertEqual(sqlrcur_getField($cur,7,"TESTINT"),"8");
	assertEqual(sqlrcur_getField($cur,7,"TESTBIGINT"),"8");
	assertEqual(sqlrcur_getField($cur,7,"TESTDECIMAL"),"8.80");
	#assertEqual(sqlrcur_getField($cur,7,"TESTREAL"),"8.8");
	#assertEqual(sqlrcur_getField($cur,7,"TESTDOUBLE"),"8.8");
	assertEqual(sqlrcur_getField($cur,7,"TESTCHAR"),"testchar8                               ");
	assertEqual(sqlrcur_getField($cur,7,"TESTVARCHAR"),"testvarchar8");
	assertEqual(sqlrcur_getField($cur,7,"TESTDATE"),"2008-01-01");
	assertEqual(sqlrcur_getField($cur,7,"TESTTIME"),"08:00:00");
	echo("\n");

	echo("FIELD LENGTHS BY NAME: \n");
	assertEqual(sqlrcur_getFieldLength($cur,0,"TESTSMALLINT"),1);
	assertEqual(sqlrcur_getFieldLength($cur,0,"TESTINT"),1);
	assertEqual(sqlrcur_getFieldLength($cur,0,"TESTBIGINT"),1);
	assertEqual(sqlrcur_getFieldLength($cur,0,"TESTDECIMAL"),4);
	#assertEqual(sqlrcur_getFieldLength($cur,0,"TESTREAL"),3);
	#assertEqual(sqlrcur_getFieldLength($cur,0,"TESTDOUBLE"),3);
	assertEqual(sqlrcur_getFieldLength($cur,0,"TESTCHAR"),40);
	assertEqual(sqlrcur_getFieldLength($cur,0,"TESTVARCHAR"),12);
	assertEqual(sqlrcur_getFieldLength($cur,0,"TESTDATE"),10);
	assertEqual(sqlrcur_getFieldLength($cur,0,"TESTTIME"),8);
	echo("\n");
	assertEqual(sqlrcur_getFieldLength($cur,7,"TESTSMALLINT"),1);
	assertEqual(sqlrcur_getFieldLength($cur,7,"TESTINT"),1);
	assertEqual(sqlrcur_getFieldLength($cur,7,"TESTBIGINT"),1);
	assertEqual(sqlrcur_getFieldLength($cur,7,"TESTDECIMAL"),4);
	#assertEqual(sqlrcur_getFieldLength($cur,7,"TESTREAL"),3);
	#assertEqual(sqlrcur_getFieldLength($cur,7,"TESTDOUBLE"),3);
	assertEqual(sqlrcur_getFieldLength($cur,7,"TESTCHAR"),40);
	assertEqual(sqlrcur_getFieldLength($cur,7,"TESTVARCHAR"),12);
	assertEqual(sqlrcur_getFieldLength($cur,7,"TESTDATE"),10);
	assertEqual(sqlrcur_getFieldLength($cur,7,"TESTTIME"),8);
	echo("\n");

	echo("FIELDS BY ARRAY: \n");
	$fields=sqlrcur_getRow($cur,0);
	assertEqual($fields[0],"1");
	assertEqual($fields[1],"1");
	assertEqual($fields[2],"1");
	assertEqual($fields[3],"1.10");
	#assertEqual($fields[4],"1.1");
	#assertEqual($fields[5],"1.1");
	assertEqual($fields[6],"testchar1                               ");
	assertEqual($fields[7],"testvarchar1");
	assertEqual($fields[8],"2001-01-01");
	assertEqual($fields[9],"01:00:00");
	echo("\n");

	echo("FIELD LENGTHS BY ARRAY: \n");
	$fieldlens=sqlrcur_getRowLengths($cur,0);
	assertEqual($fieldlens[0],1);
	assertEqual($fieldlens[1],1);
	assertEqual($fieldlens[2],1);
	assertEqual($fieldlens[3],4);
	#assertEqual($fieldlens[4],3);
	#assertEqual($fieldlens[5],3);
	assertEqual($fieldlens[6],40);
	assertEqual($fieldlens[7],12);
	assertEqual($fieldlens[8],10);
	assertEqual($fieldlens[9],8);
	echo("\n");

	echo("FIELDS BY ASSOCIATIVE ARRAY: \n");
	$fields=sqlrcur_getRowAssoc($cur,0);
	assertEqual($fields["TESTSMALLINT"],"1");
	assertEqual($fields["TESTINT"],"1");
	assertEqual($fields["TESTBIGINT"],"1");
	assertEqual($fields["TESTDECIMAL"],"1.10");
	#assertEqual($fields["TESTREAL"],"1.1");
	#assertEqual($fields["TESTDOUBLE"],"1.1");
	assertEqual($fields["TESTCHAR"],"testchar1                               ");
	assertEqual($fields["TESTVARCHAR"],"testvarchar1");
	assertEqual($fields["TESTDATE"],"2001-01-01");
	assertEqual($fields["TESTTIME"],"01:00:00");
	echo("\n");
	$fields=sqlrcur_getRowAssoc($cur,7);
	assertEqual($fields["TESTSMALLINT"],"8");
	assertEqual($fields["TESTINT"],"8");
	assertEqual($fields["TESTBIGINT"],"8");
	assertEqual($fields["TESTDECIMAL"],"8.80");
	#assertEqual($fields["TESTREAL"],"8.8");
	#assertEqual($fields["TESTDOUBLE"],"8.8");
	assertEqual($fields["TESTCHAR"],"testchar8                               ");
	assertEqual($fields["TESTVARCHAR"],"testvarchar8");
	assertEqual($fields["TESTDATE"],"2008-01-01");
	assertEqual($fields["TESTTIME"],"08:00:00");
	echo("\n");

	echo("FIELD LENGTHS BY ASSOCIATIVE ARRAY: \n");
	$fieldlengths=sqlrcur_getRowLengthsAssoc($cur,0);
	assertEqual($fieldlengths["TESTSMALLINT"],1);
	assertEqual($fieldlengths["TESTINT"],1);
	assertEqual($fieldlengths["TESTBIGINT"],1);
	assertEqual($fieldlengths["TESTDECIMAL"],4);
	#assertEqual($fieldlengths["TESTREAL"],3);
	#assertEqual($fieldlengths["TESTDOUBLE"],3);
	assertEqual($fieldlengths["TESTCHAR"],40);
	assertEqual($fieldlengths["TESTVARCHAR"],12);
	assertEqual($fieldlengths["TESTDATE"],10);
	assertEqual($fieldlengths["TESTTIME"],8);
	echo("\n");
	$fieldlengths=sqlrcur_getRowLengthsAssoc($cur,7);
	assertEqual($fieldlengths["TESTSMALLINT"],1);
	assertEqual($fieldlengths["TESTINT"],1);
	assertEqual($fieldlengths["TESTBIGINT"],1);
	assertEqual($fieldlengths["TESTDECIMAL"],4);
	#assertEqual($fieldlengths["TESTREAL"],3);
	#assertEqual($fieldlengths["TESTDOUBLE"],3);
	assertEqual($fieldlengths["TESTCHAR"],40);
	assertEqual($fieldlengths["TESTVARCHAR"],12);
	assertEqual($fieldlengths["TESTDATE"],10);
	assertEqual($fieldlengths["TESTTIME"],8);
	echo("\n");

	echo("INDIVIDUAL SUBSTITUTIONS: \n");
	sqlrcur_prepareQuery($cur,"values ($(var1),'$(var2)','$(var3)')");
	sqlrcur_substitution($cur,"var1",1);
	sqlrcur_substitution($cur,"var2","hello");
	sqlrcur_substitution($cur,"var3",10.5556,6,4);
	assertTrue(sqlrcur_executeQuery($cur));
	echo("\n");

	echo("FIELDS: \n");
	assertEqual(sqlrcur_getField($cur,0,0),"1");
	assertEqual(sqlrcur_getField($cur,0,1),"hello");
	assertEqual(sqlrcur_getField($cur,0,2),"10.5556");
	echo("\n");

	echo("ARRAY SUBSTITUTIONS: \n");
	sqlrcur_prepareQuery($cur,"values ($(var1),'$(var2)',$(var3))");
	$vars=array("var1","var2","var3");
	$vals=array(1,"hello",10.5556);
	$precs=array(0,0,6);
	$scales=array(0,0,4);
	sqlrcur_substitutions($cur,$vars,$vals,$precs,$scales);
	assertTrue(sqlrcur_executeQuery($cur));
	echo("\n");

	echo("FIELDS: \n");
	assertEqual(sqlrcur_getField($cur,0,0),"1");
	assertEqual(sqlrcur_getField($cur,0,1),"hello");
	assertEqual(sqlrcur_getField($cur,0,2),"10.5556");
	echo("\n");

	echo("NULLS as Nulls: \n");
	sqlrcur_sendQuery($cur,"drop table testtable1");
	sqlrcur_sendQuery($cur,"create table testtable1 (col1 char(1), col2 char(1), col3 char(1))");
	sqlrcur_getNullsAsNulls($cur);
	assertTrue(sqlrcur_sendQuery($cur,"insert into testtable1 values ('1',NULL,NULL)"));
	assertTrue(sqlrcur_sendQuery($cur,"select * from testtable1"));
	assertEqual(sqlrcur_getField($cur,0,0),"1");
	assertEqual(sqlrcur_getField($cur,0,1),NULL);
	assertEqual(sqlrcur_getField($cur,0,2),NULL);
	sqlrcur_getNullsAsEmptyStrings($cur);
	assertTrue(sqlrcur_sendQuery($cur,"select * from testtable1"));
	assertEqual(sqlrcur_getField($cur,0,0),"1");
	assertEqual(sqlrcur_getField($cur,0,1),"");
	assertEqual(sqlrcur_getField($cur,0,2),"");
	assertTrue(sqlrcur_sendQuery($cur,"drop table testtable1"));
	sqlrcur_getNullsAsNulls($cur);
	echo("\n");
	
	echo("RESULT SET BUFFER SIZE: \n");
	assertEqual(sqlrcur_getResultSetBufferSize($cur),0);
	sqlrcur_setResultSetBufferSize($cur,2);
	assertTrue(sqlrcur_sendQuery($cur,"select * from testtable order by testsmallint"));
	assertEqual(sqlrcur_getResultSetBufferSize($cur),2);
	echo("\n");
	assertEqual(sqlrcur_firstRowIndex($cur),0);
	assertFalse(sqlrcur_endOfResultSet($cur));
	assertEqual(sqlrcur_rowCount($cur),2);
	assertEqual(sqlrcur_getField($cur,0,0),"1");
	assertEqual(sqlrcur_getField($cur,1,0),"2");
	assertEqual(sqlrcur_getField($cur,2,0),"3");
	echo("\n");
	assertEqual(sqlrcur_firstRowIndex($cur),2);
	assertFalse(sqlrcur_endOfResultSet($cur));
	assertEqual(sqlrcur_rowCount($cur),4);
	assertEqual(sqlrcur_getField($cur,6,0),"7");
	assertEqual(sqlrcur_getField($cur,7,0),"8");
	echo("\n");
	assertEqual(sqlrcur_firstRowIndex($cur),6);
	assertFalse(sqlrcur_endOfResultSet($cur));
	assertEqual(sqlrcur_rowCount($cur),8);
	assertEqual(sqlrcur_getField($cur,8,0),NULL);
	echo("\n");
	assertEqual(sqlrcur_firstRowIndex($cur),8);
	assertTrue(sqlrcur_endOfResultSet($cur));
	assertEqual(sqlrcur_rowCount($cur),8);
	echo("\n");

	echo("DONT GET COLUMN INFO: \n");
	sqlrcur_dontGetColumnInfo($cur);
	assertTrue(sqlrcur_sendQuery($cur,"select * from testtable order by testsmallint"));
	assertEqual(sqlrcur_getColumnName($cur,0),NULL);
	assertEqual(sqlrcur_getColumnLength($cur,0),0);
	assertEqual(sqlrcur_getColumnType($cur,0),NULL);
	sqlrcur_getColumnInfo($cur);
	assertTrue(sqlrcur_sendQuery($cur,"select * from testtable order by testsmallint"));
	assertEqual(sqlrcur_getColumnName($cur,0),"TESTSMALLINT");
	assertEqual(sqlrcur_getColumnLength($cur,0),2);
	assertEqual(sqlrcur_getColumnType($cur,0),"SMALLINT");
	echo("\n");

	echo("SUSPENDED SESSION: \n");
	assertTrue(sqlrcur_sendQuery($cur,"select * from testtable order by testsmallint"));
	sqlrcur_suspendResultSet($cur);
	assertTrue(sqlrcon_suspendSession($con));
	$conport=sqlrcon_getConnectionPort($con);
	$consocket=sqlrcon_getConnectionSocket($con);
	assertTrue(sqlrcon_resumeSession($con,$conport,$consocket));
	echo("\n");
	assertEqual(sqlrcur_getField($cur,0,0),"1");
	assertEqual(sqlrcur_getField($cur,1,0),"2");
	assertEqual(sqlrcur_getField($cur,2,0),"3");
	assertEqual(sqlrcur_getField($cur,3,0),"4");
	assertEqual(sqlrcur_getField($cur,4,0),"5");
	assertEqual(sqlrcur_getField($cur,5,0),"6");
	assertEqual(sqlrcur_getField($cur,6,0),"7");
	assertEqual(sqlrcur_getField($cur,7,0),"8");
	echo("\n");
	assertTrue(sqlrcur_sendQuery($cur,"select * from testtable order by testsmallint"));
	sqlrcur_suspendResultSet($cur);
	assertTrue(sqlrcon_suspendSession($con));
	$conport=sqlrcon_getConnectionPort($con);
	$consocket=sqlrcon_getConnectionSocket($con);
	assertTrue(sqlrcon_resumeSession($con,$conport,$consocket));
	echo("\n");
	assertEqual(sqlrcur_getField($cur,0,0),"1");
	assertEqual(sqlrcur_getField($cur,1,0),"2");
	assertEqual(sqlrcur_getField($cur,2,0),"3");
	assertEqual(sqlrcur_getField($cur,3,0),"4");
	assertEqual(sqlrcur_getField($cur,4,0),"5");
	assertEqual(sqlrcur_getField($cur,5,0),"6");
	assertEqual(sqlrcur_getField($cur,6,0),"7");
	assertEqual(sqlrcur_getField($cur,7,0),"8");
	echo("\n");
	assertTrue(sqlrcur_sendQuery($cur,"select * from testtable order by testsmallint"));
	sqlrcur_suspendResultSet($cur);
	assertTrue(sqlrcon_suspendSession($con));
	$conport=sqlrcon_getConnectionPort($con);
	$consocket=sqlrcon_getConnectionSocket($con);
	assertTrue(sqlrcon_resumeSession($con,$conport,$consocket));
	echo("\n");
	assertEqual(sqlrcur_getField($cur,0,0),"1");
	assertEqual(sqlrcur_getField($cur,1,0),"2");
	assertEqual(sqlrcur_getField($cur,2,0),"3");
	assertEqual(sqlrcur_getField($cur,3,0),"4");
	assertEqual(sqlrcur_getField($cur,4,0),"5");
	assertEqual(sqlrcur_getField($cur,5,0),"6");
	assertEqual(sqlrcur_getField($cur,6,0),"7");
	assertEqual(sqlrcur_getField($cur,7,0),"8");
	echo("\n");

	echo("SUSPENDED RESULT SET: \n");
	sqlrcur_setResultSetBufferSize($cur,2);
	assertTrue(sqlrcur_sendQuery($cur,"select * from testtable order by testsmallint"));
	assertEqual(sqlrcur_getField($cur,2,0),"3");
	$id=sqlrcur_getResultSetId($cur);
	sqlrcur_suspendResultSet($cur);
	assertTrue(sqlrcon_suspendSession($con));
	$conport=sqlrcon_getConnectionPort($con);
	$consocket=sqlrcon_getConnectionSocket($con);
	assertTrue(sqlrcon_resumeSession($con,$conport,$consocket));
	assertTrue(sqlrcur_resumeResultSet($cur,$id));
	echo("\n");
	assertEqual(sqlrcur_firstRowIndex($cur),4);
	assertFalse(sqlrcur_endOfResultSet($cur));
	assertEqual(sqlrcur_rowCount($cur),6);
	assertEqual(sqlrcur_getField($cur,7,0),"8");
	echo("\n");
	assertEqual(sqlrcur_firstRowIndex($cur),6);
	assertFalse(sqlrcur_endOfResultSet($cur));
	assertEqual(sqlrcur_rowCount($cur),8);
	assertEqual(sqlrcur_getField($cur,8,0),NULL);
	echo("\n");
	assertEqual(sqlrcur_firstRowIndex($cur),8);
	assertTrue(sqlrcur_endOfResultSet($cur));
	assertEqual(sqlrcur_rowCount($cur),8);
	sqlrcur_setResultSetBufferSize($cur,0);
	echo("\n");

	echo("CACHED RESULT SET: \n");
	sqlrcur_cacheToFile($cur,"cachefile1");
	sqlrcur_setCacheTtl($cur,200);
	assertTrue(sqlrcur_sendQuery($cur,"select * from testtable order by testsmallint"));
	$filename=sqlrcur_getCacheFileName($cur);
	assertEqual($filename,"cachefile1");
	sqlrcur_cacheOff($cur);
	assertTrue(sqlrcur_openCachedResultSet($cur,$filename));
	assertEqual(sqlrcur_getField($cur,7,0),"8");
	echo("\n");

	echo("COLUMN COUNT FOR CACHED RESULT SET: \n");
	assertEqual(sqlrcur_colCount($cur),11);
	echo("\n");

	echo("COLUMN NAMES FOR CACHED RESULT SET: \n");
	assertEqual(sqlrcur_getColumnName($cur,0),"TESTSMALLINT");
	assertEqual(sqlrcur_getColumnName($cur,1),"TESTINT");
	assertEqual(sqlrcur_getColumnName($cur,2),"TESTBIGINT");
	assertEqual(sqlrcur_getColumnName($cur,3),"TESTDECIMAL");
	assertEqual(sqlrcur_getColumnName($cur,4),"TESTREAL");
	assertEqual(sqlrcur_getColumnName($cur,5),"TESTDOUBLE");
	assertEqual(sqlrcur_getColumnName($cur,6),"TESTCHAR");
	assertEqual(sqlrcur_getColumnName($cur,7),"TESTVARCHAR");
	assertEqual(sqlrcur_getColumnName($cur,8),"TESTDATE");
	assertEqual(sqlrcur_getColumnName($cur,9),"TESTTIME");
	assertEqual(sqlrcur_getColumnName($cur,10),"TESTTIMESTAMP");
	$cols=sqlrcur_getColumnNames($cur);
	assertEqual($cols[0],"TESTSMALLINT");
	assertEqual($cols[1],"TESTINT");
	assertEqual($cols[2],"TESTBIGINT");
	assertEqual($cols[3],"TESTDECIMAL");
	assertEqual($cols[4],"TESTREAL");
	assertEqual($cols[5],"TESTDOUBLE");
	assertEqual($cols[6],"TESTCHAR");
	assertEqual($cols[7],"TESTVARCHAR");
	assertEqual($cols[8],"TESTDATE");
	assertEqual($cols[9],"TESTTIME");
	assertEqual($cols[10],"TESTTIMESTAMP");
	echo("\n");

	echo("CACHED RESULT SET WITH RESULT SET BUFFER SIZE: \n");
	sqlrcur_setResultSetBufferSize($cur,2);
	sqlrcur_cacheToFile($cur,"cachefile1");
	sqlrcur_setCacheTtl($cur,200);
	assertTrue(sqlrcur_sendQuery($cur,"select * from testtable order by testsmallint"));
	$filename=sqlrcur_getCacheFileName($cur);
	assertEqual($filename,"cachefile1");
	sqlrcur_cacheOff($cur);
	assertTrue(sqlrcur_openCachedResultSet($cur,$filename));
	assertEqual(sqlrcur_getField($cur,7,0),"8");
	assertEqual(sqlrcur_getField($cur,8,0),NULL);
	sqlrcur_setResultSetBufferSize($cur,0);
	echo("\n");

	echo("FROM ONE CACHE FILE TO ANOTHER: \n");
	sqlrcur_cacheToFile($cur,"cachefile2");
	assertTrue(sqlrcur_openCachedResultSet($cur,"cachefile1"));
	sqlrcur_cacheOff($cur);
	assertTrue(sqlrcur_openCachedResultSet($cur,"cachefile2"));
	assertEqual(sqlrcur_getField($cur,7,0),"8");
	assertEqual(sqlrcur_getField($cur,8,0),NULL);
	echo("\n");

	echo("FROM ONE CACHE FILE TO ANOTHER WITH RESULT SET BUFFER SIZE: \n");
	sqlrcur_setResultSetBufferSize($cur,2);
	sqlrcur_cacheToFile($cur,"cachefile2");
	assertTrue(sqlrcur_openCachedResultSet($cur,"cachefile1"));
	sqlrcur_cacheOff($cur);
	assertTrue(sqlrcur_openCachedResultSet($cur,"cachefile2"));
	assertEqual(sqlrcur_getField($cur,7,0),"8");
	assertEqual(sqlrcur_getField($cur,8,0),NULL);
	sqlrcur_setResultSetBufferSize($cur,0);
	echo("\n");

	echo("CACHED RESULT SET WITH SUSPEND AND RESULT SET BUFFER SIZE: \n");
	sqlrcur_setResultSetBufferSize($cur,2);
	sqlrcur_cacheToFile($cur,"cachefile1");
	sqlrcur_setCacheTtl($cur,200);
	assertTrue(sqlrcur_sendQuery($cur,"select * from testtable order by testsmallint"));
	assertEqual(sqlrcur_getField($cur,2,0),"3");
	$filename=sqlrcur_getCacheFileName($cur);
	assertEqual($filename,"cachefile1");
	$id=sqlrcur_getResultSetId($cur);
	sqlrcur_suspendResultSet($cur);
	assertTrue(sqlrcon_suspendSession($con));
	$conport=sqlrcon_getConnectionPort($con);
	$consocket=sqlrcon_getConnectionSocket($con);
	echo("\n");
	assertTrue(sqlrcon_resumeSession($con,$conport,$consocket));
	assertTrue(sqlrcur_resumeCachedResultSet($cur,$id,$filename));
	echo("\n");
	assertEqual(sqlrcur_firstRowIndex($cur),4);
	assertFalse(sqlrcur_endOfResultSet($cur));
	assertEqual(sqlrcur_rowCount($cur),6);
	assertEqual(sqlrcur_getField($cur,7,0),"8");
	echo("\n");
	assertEqual(sqlrcur_firstRowIndex($cur),6);
	assertFalse(sqlrcur_endOfResultSet($cur));
	assertEqual(sqlrcur_rowCount($cur),8);
	assertEqual(sqlrcur_getField($cur,8,0),NULL);
	echo("\n");
	assertEqual(sqlrcur_firstRowIndex($cur),8);
	assertTrue(sqlrcur_endOfResultSet($cur));
	assertEqual(sqlrcur_rowCount($cur),8);
	sqlrcur_cacheOff($cur);
	echo("\n");
	assertTrue(sqlrcur_openCachedResultSet($cur,$filename));
	assertEqual(sqlrcur_getField($cur,7,0),"8");
	assertEqual(sqlrcur_getField($cur,8,0),NULL);
	sqlrcur_setResultSetBufferSize($cur,0);
	echo("\n");

	# drop existing table
	sqlrcon_commit($con);
	sqlrcur_sendQuery($cur,"drop table testtable");
	echo("\n");

	# invalid queries...
	echo("INVALID QUERIES: \n");
	assertFalse(sqlrcur_sendQuery($cur,"select * from testtable order by testsmallint"));
	assertFalse(sqlrcur_sendQuery($cur,"select * from testtable order by testsmallint"));
	assertFalse(sqlrcur_sendQuery($cur,"select * from testtable order by testsmallint"));
	assertFalse(sqlrcur_sendQuery($cur,"select * from testtable order by testsmallint"));
	echo("\n");
	assertFalse(sqlrcur_sendQuery($cur,"insert into testtable values (1,2,3,4)"));
	assertFalse(sqlrcur_sendQuery($cur,"insert into testtable values (1,2,3,4)"));
	assertFalse(sqlrcur_sendQuery($cur,"insert into testtable values (1,2,3,4)"));
	assertFalse(sqlrcur_sendQuery($cur,"insert into testtable values (1,2,3,4)"));
	echo("\n");
	assertFalse(sqlrcur_sendQuery($cur,"create table testtable"));
	assertFalse(sqlrcur_sendQuery($cur,"create table testtable"));
	assertFalse(sqlrcur_sendQuery($cur,"create table testtable"));
	assertFalse(sqlrcur_sendQuery($cur,"create table testtable"));
	echo("\n");
?></pre></html>
