// Copyright (c) David Muse
// See the file COPYING for more information.

var	sqlrelay=require("sqlrelay");
var	{assertEqual, getStatus, reportTestStatus}=require("./asserts.js");



var	subvars=["var1","var2","var3"];
var	subvalstrings=["hi","hello","bye"];
var	subvallongs=[1,2,3];
var	subvaldoubles=[10.55,10.556,10.5556];
var	precs=[4,5,6];
var	scales=[2,3,4];
var	cols;
var	fields;
var	port;
var	socket;
var	id;
var	filename;
var	fieldlens;


// instantiation
var	con=new sqlrelay.SQLRConnection("sqlrelay",9000,"/tmp/test.socket","testuser","testpassword",0,1);
var	cur=new sqlrelay.SQLRCursor(con);

// get database type
console.log("IDENTIFY: ");
assertEqual(con.identify(),"mysql");
console.log("\n");

// get the db version
var	dbversion=con.dbVersion();
var	majorversion=parseInt(dbversion.substring(0,1));

// ping
console.log("PING: ");
assertEqual(con.ping(),1);
console.log("\n");

// isolation levels
console.log("ISOLATION LEVELS: ");
var	isolationlevels=["REPEATABLE-READ","READ-UNCOMMITTED","READ-COMMITTED","SERIALIZABLE"];
for (var i=0; i<isolationlevels.length; i++) {
	assertEqual(con.setIsolationLevel(isolationlevels[i]),1);
	assertEqual(con.getIsolationLevel(),isolationlevels[i]);
	console.log();
}
// reset to the default isolation level
assertEqual(con.setIsolationLevel(isolationlevels[0]),1);
console.log("\n");

// drop existing table
cur.sendQuery("drop table testtable");

// create a new table
console.log("CREATE TEMPTABLE: ");
assertEqual(cur.sendQuery("create table testtable (testtinyint tinyint, testsmallint smallint, testmediumint mediumint, testint int, testbigint bigint, testfloat float, testreal real, testdecimal decimal(2,1), testdate date, testtime time, testdatetime datetime, testyear year, testchar char(40), testtext text, testvarchar varchar(40), testtinytext tinytext, testmediumtext mediumtext, testlongtext longtext, testtimestamp timestamp)"),1);
console.log("\n");

console.log("BEGIN TRANSACTION:");
assertEqual(cur.sendQuery("begin"),1);
console.log();

console.log("INSERT: ");
assertEqual(cur.sendQuery("insert into testtable values (1,1,1,1,1,1.1,1.1,1.1,'2001-01-01','01:00:00','2001-01-01 01:00:00','2001','char1','text1','varchar1','tinytext1','mediumtext1','longtext1',null)"),1);
assertEqual(cur.sendQuery("insert into testtable values (2,2,2,2,2,2.1,2.1,2.1,'2002-01-01','02:00:00','2002-01-01 02:00:00','2002','char2','text2','varchar2','tinytext2','mediumtext2','longtext2',null)"),1);
assertEqual(cur.sendQuery("insert into testtable values (3,3,3,3,3,3.1,3.1,3.1,'2003-01-01','03:00:00','2003-01-01 03:00:00','2003','char3','text3','varchar3','tinytext3','mediumtext3','longtext3',null)"),1);
assertEqual(cur.sendQuery("insert into testtable values (4,4,4,4,4,4.1,4.1,4.1,'2004-01-01','04:00:00','2004-01-01 04:00:00','2004','char4','text4','varchar4','tinytext4','mediumtext4','longtext4',null)"),1);
console.log("\n");

console.log("AFFECTED ROWS: ");
assertEqual(cur.affectedRows(),1);
console.log("\n");

console.log("BIND BY POSITION: ");
cur.prepareQuery("insert into testtable values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,null)");
assertEqual(cur.countBindVariables(),18);
cur.inputBind("1",5);
cur.inputBind("2",5);
cur.inputBind("3",5);
cur.inputBind("4",5);
cur.inputBind("5",5);
cur.inputBind("6",5.1,2,1);
cur.inputBind("7",5.1,2,1);
cur.inputBind("8",5.1,2,1);
cur.inputBind("9","2005-01-01");
cur.inputBind("10","05:00:00");
cur.inputBind("11","2005-01-01 05:00:00");
cur.inputBind("12","2005");
cur.inputBind("13","char5");
cur.inputBind("14","text5");
cur.inputBind("15","varchar5");
cur.inputBind("16","tinytext5");
cur.inputBind("17","mediumtext5");
cur.inputBind("18","longtext5");
assertEqual(cur.executeQuery(),1);
cur.clearBinds();
cur.inputBind("1",6);
cur.inputBind("2",6);
cur.inputBind("3",6);
cur.inputBind("4",6);
cur.inputBind("5",6);
cur.inputBind("6",6.1,2,1);
cur.inputBind("7",6.1,2,1);
cur.inputBind("8",6.1,2,1);
cur.inputBind("9","2006-01-01");
cur.inputBind("10","06:00:00");
cur.inputBind("11","2006-01-01 06:00:00");
cur.inputBind("12","2006");
cur.inputBind("13","char6");
cur.inputBind("14","text6");
cur.inputBind("15","varchar6");
cur.inputBind("16","tinytext6");
cur.inputBind("17","mediumtext6");
cur.inputBind("18","longtext6");
assertEqual(cur.executeQuery(),1);
cur.clearBinds();
cur.inputBind("1",7);
cur.inputBind("2",7);
cur.inputBind("3",7);
cur.inputBind("4",7);
cur.inputBind("5",7);
cur.inputBind("6",7.1,2,1);
cur.inputBind("7",7.1,2,1);
cur.inputBind("8",7.1,2,1);
cur.inputBind("9","2007-01-01");
cur.inputBind("10","07:00:00");
cur.inputBind("11","2007-01-01 07:00:00");
cur.inputBind("12","2007");
cur.inputBind("13","char7");
cur.inputBind("14","text7");
cur.inputBind("15","varchar7");
cur.inputBind("16","tinytext7");
cur.inputBind("17","mediumtext7");
cur.inputBind("18","longtext7");
assertEqual(cur.executeQuery(),1);
console.log("\n");

console.log("BIND BY POSITION WITH VALIDATION: ");
cur.clearBinds();
cur.inputBind("1",8);
cur.inputBind("2",8);
cur.inputBind("3",8);
cur.inputBind("4",8);
cur.inputBind("5",8);
cur.inputBind("6",8.1,2,1);
cur.inputBind("7",8.1,2,1);
cur.inputBind("8",8.1,2,1);
cur.inputBind("9","2008-01-01");
cur.inputBind("10","08:00:00");
cur.inputBind("11","2008-01-01 08:00:00");
cur.inputBind("12","2008");
cur.inputBind("13","char8");
cur.inputBind("14","text8");
cur.inputBind("15","varchar8");
cur.inputBind("16","tinytext8");
cur.inputBind("17","mediumtext8");
cur.inputBind("18","longtext8");
cur.validateBinds();
assertEqual(cur.executeQuery(),1);
console.log("\n");

console.log("SELECT: ");
assertEqual(cur.sendQuery("select * from testtable order by testtinyint"),1);
console.log("\n");

console.log("COLUMN COUNT: ");
assertEqual(cur.colCount(),19);
console.log("\n");

console.log("COLUMN NAMES: ");
assertEqual(cur.getColumnName(0),"testtinyint");
assertEqual(cur.getColumnName(1),"testsmallint");
assertEqual(cur.getColumnName(2),"testmediumint");
assertEqual(cur.getColumnName(3),"testint");
assertEqual(cur.getColumnName(4),"testbigint");
assertEqual(cur.getColumnName(5),"testfloat");
assertEqual(cur.getColumnName(6),"testreal");
assertEqual(cur.getColumnName(7),"testdecimal");
assertEqual(cur.getColumnName(8),"testdate");
assertEqual(cur.getColumnName(9),"testtime");
assertEqual(cur.getColumnName(10),"testdatetime");
assertEqual(cur.getColumnName(11),"testyear");
assertEqual(cur.getColumnName(12),"testchar");
assertEqual(cur.getColumnName(13),"testtext");
assertEqual(cur.getColumnName(14),"testvarchar");
assertEqual(cur.getColumnName(15),"testtinytext");
assertEqual(cur.getColumnName(16),"testmediumtext");
assertEqual(cur.getColumnName(17),"testlongtext");
assertEqual(cur.getColumnName(18),"testtimestamp");
cols=cur.getColumnNames();
assertEqual(cols[0],"testtinyint");
assertEqual(cols[1],"testsmallint");
assertEqual(cols[2],"testmediumint");
assertEqual(cols[3],"testint");
assertEqual(cols[4],"testbigint");
assertEqual(cols[5],"testfloat");
assertEqual(cols[6],"testreal");
assertEqual(cols[7],"testdecimal");
assertEqual(cols[8],"testdate");
assertEqual(cols[9],"testtime");
assertEqual(cols[10],"testdatetime");
assertEqual(cols[11],"testyear");
assertEqual(cols[12],"testchar");
assertEqual(cols[13],"testtext");
assertEqual(cols[14],"testvarchar");
assertEqual(cols[15],"testtinytext");
assertEqual(cols[16],"testmediumtext");
assertEqual(cols[17],"testlongtext");
assertEqual(cols[18],"testtimestamp");
console.log("\n");

console.log("COLUMN TYPES: ");
assertEqual(cur.getColumnType(0),"TINYINT");
assertEqual(cur.getColumnType(1),"SMALLINT");
assertEqual(cur.getColumnType(2),"MEDIUMINT");
assertEqual(cur.getColumnType(3),"INT");
assertEqual(cur.getColumnType(4),"BIGINT");
assertEqual(cur.getColumnType(5),"FLOAT");
assertEqual(cur.getColumnType(6),"REAL");
assertEqual(cur.getColumnType(7),"DECIMAL");
assertEqual(cur.getColumnType(8),"DATE");
assertEqual(cur.getColumnType(9),"TIME");
assertEqual(cur.getColumnType(10),"DATETIME");
assertEqual(cur.getColumnType(11),"YEAR");
if (majorversion==3) {
	assertEqual(cur.getColumnType(12),"VARSTRING");
} else {
	assertEqual(cur.getColumnType(12),"STRING");
}
assertEqual(cur.getColumnType(13),"BLOB");
assertEqual(cur.getColumnType(14),"VARSTRING");
assertEqual(cur.getColumnType(15),"TINYBLOB");
assertEqual(cur.getColumnType(16),"MEDIUMBLOB");
assertEqual(cur.getColumnType(17),"LONGBLOB");
assertEqual(cur.getColumnType(18),"TIMESTAMP");
assertEqual(cur.getColumnType("testtinyint"),"TINYINT");
assertEqual(cur.getColumnType("testsmallint"),"SMALLINT");
assertEqual(cur.getColumnType("testmediumint"),"MEDIUMINT");
assertEqual(cur.getColumnType("testint"),"INT");
assertEqual(cur.getColumnType("testbigint"),"BIGINT");
assertEqual(cur.getColumnType("testfloat"),"FLOAT");
assertEqual(cur.getColumnType("testreal"),"REAL");
assertEqual(cur.getColumnType("testdecimal"),"DECIMAL");
assertEqual(cur.getColumnType("testdate"),"DATE");
assertEqual(cur.getColumnType("testtime"),"TIME");
assertEqual(cur.getColumnType("testdatetime"),"DATETIME");
assertEqual(cur.getColumnType("testyear"),"YEAR");
if (majorversion==3) {
	assertEqual(cur.getColumnType("testchar"),"VARSTRING");
} else {
	assertEqual(cur.getColumnType("testchar"),"STRING");
}
assertEqual(cur.getColumnType("testtext"),"BLOB");
assertEqual(cur.getColumnType("testvarchar"),"VARSTRING");
assertEqual(cur.getColumnType("testtinytext"),"TINYBLOB");
assertEqual(cur.getColumnType("testmediumtext"),"MEDIUMBLOB");
assertEqual(cur.getColumnType("testlongtext"),"LONGBLOB");
assertEqual(cur.getColumnType("testtimestamp"),"TIMESTAMP");
console.log("\n");

console.log("COLUMN LENGTH: ");
assertEqual(cur.getColumnLength(0),1);
assertEqual(cur.getColumnLength(1),2);
assertEqual(cur.getColumnLength(2),3);
assertEqual(cur.getColumnLength(3),4);
assertEqual(cur.getColumnLength(4),8);
assertEqual(cur.getColumnLength(5),4);
assertEqual(cur.getColumnLength(6),8);
assertEqual(cur.getColumnLength(7),6);
assertEqual(cur.getColumnLength(8),3);
assertEqual(cur.getColumnLength(9),3);
assertEqual(cur.getColumnLength(10),8);
assertEqual(cur.getColumnLength(11),1);
//assertEqual(cur.getColumnLength(12),40);
assertEqual(cur.getColumnLength(13),65535);
//assertEqual(cur.getColumnLength(14),41);
assertEqual(cur.getColumnLength(15),255);
assertEqual(cur.getColumnLength(16),16777215);
assertEqual(cur.getColumnLength(17),2147483647);
assertEqual(cur.getColumnLength(18),4);
assertEqual(cur.getColumnLength("testtinyint"),1);
assertEqual(cur.getColumnLength("testsmallint"),2);
assertEqual(cur.getColumnLength("testmediumint"),3);
assertEqual(cur.getColumnLength("testint"),4);
assertEqual(cur.getColumnLength("testbigint"),8);
assertEqual(cur.getColumnLength("testfloat"),4);
assertEqual(cur.getColumnLength("testreal"),8);
assertEqual(cur.getColumnLength("testdecimal"),6);
assertEqual(cur.getColumnLength("testdate"),3);
assertEqual(cur.getColumnLength("testtime"),3);
assertEqual(cur.getColumnLength("testdatetime"),8);
assertEqual(cur.getColumnLength("testyear"),1);
//assertEqual(cur.getColumnLength("testchar"),40);
assertEqual(cur.getColumnLength("testtext"),65535);
//assertEqual(cur.getColumnLength("testvarchar"),41);
assertEqual(cur.getColumnLength("testtinytext"),255);
assertEqual(cur.getColumnLength("testmediumtext"),16777215);
assertEqual(cur.getColumnLength("testlongtext"),2147483647);
assertEqual(cur.getColumnLength("testtimestamp"),4);
console.log("\n");

console.log("LONGEST COLUMN: ");
assertEqual(cur.getLongest(0),1);
assertEqual(cur.getLongest(1),1);
assertEqual(cur.getLongest(2),1);
assertEqual(cur.getLongest(3),1);
assertEqual(cur.getLongest(4),1);
//assertEqual(cur.getLongest(5),3);
assertEqual(cur.getLongest(6),3);
assertEqual(cur.getLongest(7),3);
assertEqual(cur.getLongest(8),10);
assertEqual(cur.getLongest(9),8);
assertEqual(cur.getLongest(10),19);
assertEqual(cur.getLongest(11),4);
assertEqual(cur.getLongest(12),5);
assertEqual(cur.getLongest(13),5);
assertEqual(cur.getLongest(14),8);
assertEqual(cur.getLongest(15),9);
assertEqual(cur.getLongest(16),11);
assertEqual(cur.getLongest(17),9);
if (majorversion==3) {
	assertEqual(cur.getLongest(18),14);
} else {
	assertEqual(cur.getLongest(18),19);
}
assertEqual(cur.getLongest("testtinyint"),1);
assertEqual(cur.getLongest("testsmallint"),1);
assertEqual(cur.getLongest("testmediumint"),1);
assertEqual(cur.getLongest("testint"),1);
assertEqual(cur.getLongest("testbigint"),1);
//assertEqual(cur.getLongest("testfloat"),3);
assertEqual(cur.getLongest("testreal"),3);
assertEqual(cur.getLongest("testdecimal"),3);
assertEqual(cur.getLongest("testdate"),10);
assertEqual(cur.getLongest("testtime"),8);
assertEqual(cur.getLongest("testdatetime"),19);
assertEqual(cur.getLongest("testyear"),4);
assertEqual(cur.getLongest("testchar"),5);
assertEqual(cur.getLongest("testtext"),5);
assertEqual(cur.getLongest("testvarchar"),8);
assertEqual(cur.getLongest("testtinytext"),9);
assertEqual(cur.getLongest("testmediumtext"),11);
assertEqual(cur.getLongest("testlongtext"),9);
if (majorversion==3) {
	assertEqual(cur.getLongest("testtimestamp"),14);
} else {
	assertEqual(cur.getLongest("testtimestamp"),19);
}
console.log("\n");

console.log("ROW COUNT: ");
assertEqual(cur.rowCount(),8);
console.log("\n");

console.log("TOTAL ROWS: ");
// older versions of mysql know this
//assertEqual(cur.totalRows(),0);
console.log("\n");

console.log("FIRST ROW INDEX: ");
assertEqual(cur.firstRowIndex(),0);
console.log("\n");

console.log("END OF RESULT SET: ");
assertEqual(cur.endOfResultSet(),1);
console.log("\n");

console.log("FIELDS BY INDEX: ");
assertEqual(cur.getField(0,0),"1");
assertEqual(cur.getField(0,1),"1");
assertEqual(cur.getField(0,2),"1");
assertEqual(cur.getField(0,3),"1");
assertEqual(cur.getField(0,4),"1");
//assertEqual(cur.getField(0,5),"1.1");
assertEqual(cur.getField(0,6),"1.1");
assertEqual(cur.getField(0,7),"1.1");
assertEqual(cur.getField(0,8),"2001-01-01");
assertEqual(cur.getField(0,9),"01:00:00");
assertEqual(cur.getField(0,10),"2001-01-01 01:00:00");
assertEqual(cur.getField(0,11),"2001");
assertEqual(cur.getField(0,12),"char1");
assertEqual(cur.getField(0,13),"text1");
assertEqual(cur.getField(0,14),"varchar1");
assertEqual(cur.getField(0,15),"tinytext1");
assertEqual(cur.getField(0,16),"mediumtext1");
assertEqual(cur.getField(0,17),"longtext1");
console.log();
assertEqual(cur.getField(7,0),"8");
assertEqual(cur.getField(7,1),"8");
assertEqual(cur.getField(7,2),"8");
assertEqual(cur.getField(7,3),"8");
assertEqual(cur.getField(7,4),"8");
//assertEqual(cur.getField(7,5),"8.1");
assertEqual(cur.getField(7,6),"8.1");
assertEqual(cur.getField(7,7),"8.1");
assertEqual(cur.getField(7,8),"2008-01-01");
assertEqual(cur.getField(7,9),"08:00:00");
assertEqual(cur.getField(7,10),"2008-01-01 08:00:00");
assertEqual(cur.getField(7,11),"2008");
assertEqual(cur.getField(7,12),"char8");
assertEqual(cur.getField(7,13),"text8");
assertEqual(cur.getField(7,14),"varchar8");
assertEqual(cur.getField(7,15),"tinytext8");
assertEqual(cur.getField(7,16),"mediumtext8");
assertEqual(cur.getField(7,17),"longtext8");
console.log();

console.log("FIELD LENGTHS BY INDEX: ");
assertEqual(cur.getFieldLength(0,0),1);
assertEqual(cur.getFieldLength(0,1),1);
assertEqual(cur.getFieldLength(0,2),1);
assertEqual(cur.getFieldLength(0,3),1);
assertEqual(cur.getFieldLength(0,4),1);
//assertEqual(cur.getFieldLength(0,5),3);
assertEqual(cur.getFieldLength(0,6),3);
assertEqual(cur.getFieldLength(0,7),3);
assertEqual(cur.getFieldLength(0,8),10);
assertEqual(cur.getFieldLength(0,9),8);
assertEqual(cur.getFieldLength(0,10),19);
assertEqual(cur.getFieldLength(0,11),4);
assertEqual(cur.getFieldLength(0,12),5);
assertEqual(cur.getFieldLength(0,13),5);
assertEqual(cur.getFieldLength(0,14),8);
assertEqual(cur.getFieldLength(0,15),9);
assertEqual(cur.getFieldLength(0,16),11);
assertEqual(cur.getFieldLength(0,17),9);
console.log();
assertEqual(cur.getFieldLength(7,0),1);
assertEqual(cur.getFieldLength(7,1),1);
assertEqual(cur.getFieldLength(7,2),1);
assertEqual(cur.getFieldLength(7,3),1);
assertEqual(cur.getFieldLength(7,4),1);
//assertEqual(cur.getFieldLength(7,5),3);
assertEqual(cur.getFieldLength(7,6),3);
assertEqual(cur.getFieldLength(7,7),3);
assertEqual(cur.getFieldLength(7,8),10);
assertEqual(cur.getFieldLength(7,9),8);
assertEqual(cur.getFieldLength(7,10),19);
assertEqual(cur.getFieldLength(7,11),4);
assertEqual(cur.getFieldLength(7,12),5);
assertEqual(cur.getFieldLength(7,13),5);
assertEqual(cur.getFieldLength(7,14),8);
assertEqual(cur.getFieldLength(7,15),9);
assertEqual(cur.getFieldLength(7,16),11);
assertEqual(cur.getFieldLength(7,17),9);
console.log();

console.log("FIELDS BY NAME: ");
assertEqual(cur.getField(0,"testtinyint"),"1");
assertEqual(cur.getField(0,"testsmallint"),"1");
assertEqual(cur.getField(0,"testmediumint"),"1");
assertEqual(cur.getField(0,"testint"),"1");
assertEqual(cur.getField(0,"testbigint"),"1");
//assertEqual(cur.getField(0,"testfloat"),"1.1");
assertEqual(cur.getField(0,"testreal"),"1.1");
assertEqual(cur.getField(0,"testdecimal"),"1.1");
assertEqual(cur.getField(0,"testdate"),"2001-01-01");
assertEqual(cur.getField(0,"testtime"),"01:00:00");
assertEqual(cur.getField(0,"testdatetime"),"2001-01-01 01:00:00");
assertEqual(cur.getField(0,"testyear"),"2001");
assertEqual(cur.getField(0,"testchar"),"char1");
assertEqual(cur.getField(0,"testtext"),"text1");
assertEqual(cur.getField(0,"testvarchar"),"varchar1");
assertEqual(cur.getField(0,"testtinytext"),"tinytext1");
assertEqual(cur.getField(0,"testmediumtext"),"mediumtext1");
assertEqual(cur.getField(0,"testlongtext"),"longtext1");
console.log();
assertEqual(cur.getField(7,"testtinyint"),"8");
assertEqual(cur.getField(7,"testsmallint"),"8");
assertEqual(cur.getField(7,"testmediumint"),"8");
assertEqual(cur.getField(7,"testint"),"8");
assertEqual(cur.getField(7,"testbigint"),"8");
//assertEqual(cur.getField(7,"testfloat"),"8.1");
assertEqual(cur.getField(7,"testreal"),"8.1");
assertEqual(cur.getField(7,"testdecimal"),"8.1");
assertEqual(cur.getField(7,"testdate"),"2008-01-01");
assertEqual(cur.getField(7,"testtime"),"08:00:00");
assertEqual(cur.getField(7,"testdatetime"),"2008-01-01 08:00:00");
assertEqual(cur.getField(7,"testyear"),"2008");
assertEqual(cur.getField(7,"testchar"),"char8");
assertEqual(cur.getField(7,"testtext"),"text8");
assertEqual(cur.getField(7,"testvarchar"),"varchar8");
assertEqual(cur.getField(7,"testtinytext"),"tinytext8");
assertEqual(cur.getField(7,"testmediumtext"),"mediumtext8");
assertEqual(cur.getField(7,"testlongtext"),"longtext8");
console.log();

console.log("FIELD LENGTHS BY NAME: ");
assertEqual(cur.getFieldLength(0,"testtinyint"),1);
assertEqual(cur.getFieldLength(0,"testsmallint"),1);
assertEqual(cur.getFieldLength(0,"testmediumint"),1);
assertEqual(cur.getFieldLength(0,"testint"),1);
assertEqual(cur.getFieldLength(0,"testbigint"),1);
//assertEqual(cur.getFieldLength(0,"testfloat"),3);
assertEqual(cur.getFieldLength(0,"testreal"),3);
assertEqual(cur.getFieldLength(0,"testdecimal"),3);
assertEqual(cur.getFieldLength(0,"testdate"),10);
assertEqual(cur.getFieldLength(0,"testtime"),8);
assertEqual(cur.getFieldLength(0,"testdatetime"),19);
assertEqual(cur.getFieldLength(0,"testyear"),4);
assertEqual(cur.getFieldLength(0,"testchar"),5);
assertEqual(cur.getFieldLength(0,"testtext"),5);
assertEqual(cur.getFieldLength(0,"testvarchar"),8);
assertEqual(cur.getFieldLength(0,"testtinytext"),9);
assertEqual(cur.getFieldLength(0,"testmediumtext"),11);
assertEqual(cur.getFieldLength(0,"testlongtext"),9);
console.log();
assertEqual(cur.getFieldLength(7,"testtinyint"),1);
assertEqual(cur.getFieldLength(7,"testsmallint"),1);
assertEqual(cur.getFieldLength(7,"testmediumint"),1);
assertEqual(cur.getFieldLength(7,"testint"),1);
assertEqual(cur.getFieldLength(7,"testbigint"),1);
//assertEqual(cur.getFieldLength(7,"testfloat"),3);
assertEqual(cur.getFieldLength(7,"testreal"),3);
assertEqual(cur.getFieldLength(7,"testdecimal"),3);
assertEqual(cur.getFieldLength(7,"testdate"),10);
assertEqual(cur.getFieldLength(7,"testtime"),8);
assertEqual(cur.getFieldLength(7,"testdatetime"),19);
assertEqual(cur.getFieldLength(7,"testyear"),4);
assertEqual(cur.getFieldLength(7,"testchar"),5);
assertEqual(cur.getFieldLength(7,"testtext"),5);
assertEqual(cur.getFieldLength(7,"testvarchar"),8);
assertEqual(cur.getFieldLength(7,"testtinytext"),9);
assertEqual(cur.getFieldLength(7,"testmediumtext"),11);
assertEqual(cur.getFieldLength(7,"testlongtext"),9);
console.log();

console.log("FIELDS BY ARRAY: ");
fields=cur.getRow(0);
assertEqual(fields[0],"1");
assertEqual(fields[1],"1");
assertEqual(fields[2],"1");
assertEqual(fields[3],"1");
assertEqual(fields[4],"1");
//assertEqual(fields[5],"1.1");
assertEqual(fields[6],"1.1");
assertEqual(fields[7],"1.1");
assertEqual(fields[8],"2001-01-01");
assertEqual(fields[9],"01:00:00");
assertEqual(fields[10],"2001-01-01 01:00:00");
assertEqual(fields[11],"2001");
assertEqual(fields[12],"char1");
assertEqual(fields[13],"text1");
assertEqual(fields[14],"varchar1");
assertEqual(fields[15],"tinytext1");
assertEqual(fields[16],"mediumtext1");
assertEqual(fields[17],"longtext1");
console.log("\n");

console.log("FIELD LENGTHS BY ARRAY: ");
fieldlens=cur.getRowLengths(0);
assertEqual(fieldlens[0],1);
assertEqual(fieldlens[1],1);
assertEqual(fieldlens[2],1);
assertEqual(fieldlens[3],1);
assertEqual(fieldlens[4],1);
//assertEqual(fieldlens[5],3);
assertEqual(fieldlens[6],3);
assertEqual(fieldlens[7],3);
assertEqual(fieldlens[8],10);
assertEqual(fieldlens[9],8);
assertEqual(fieldlens[10],19);
assertEqual(fieldlens[11],4);
assertEqual(fieldlens[12],5);
assertEqual(fieldlens[13],5);
assertEqual(fieldlens[14],8);
assertEqual(fieldlens[15],9);
assertEqual(fieldlens[16],11);
assertEqual(fieldlens[17],9);
console.log("\n");

console.log("INDIVIDUAL SUBSTITUTIONS: ");
cur.prepareQuery("select $(var1),'$(var2)',$(var3)");
cur.substitution("var1",1);
cur.substitution("var2","hello");
cur.substitution("var3",10.5556,6,4);
assertEqual(cur.executeQuery(),1);
console.log("\n");

console.log("FIELDS: ");
assertEqual(cur.getField(0,0),"1");
assertEqual(cur.getField(0,1),"hello");
assertEqual(cur.getField(0,2),"10.5556");
console.log("\n");

console.log("ARRAY SUBSTITUTIONS: ");
cur.prepareQuery("select $(var1),$(var2),$(var3)");
cur.substitutions(subvars,subvallongs);
assertEqual(cur.executeQuery(),1);
console.log("\n");

console.log("FIELDS: ");
assertEqual(cur.getField(0,0),"1");
assertEqual(cur.getField(0,1),"2");
assertEqual(cur.getField(0,2),"3");
console.log("\n");

console.log("ARRAY SUBSTITUTIONS: ");
cur.prepareQuery("select '$(var1)','$(var2)','$(var3)'");
cur.substitutions(subvars,subvalstrings);
assertEqual(cur.executeQuery(),1);
console.log("\n");

console.log("FIELDS: ");
assertEqual(cur.getField(0,0),"hi");
assertEqual(cur.getField(0,1),"hello");
assertEqual(cur.getField(0,2),"bye");
console.log("\n");

console.log("ARRAY SUBSTITUTIONS: ");
cur.prepareQuery("select $(var1),$(var2),$(var3)");
cur.substitutions(subvars,subvaldoubles,precs,scales);
assertEqual(cur.executeQuery(),1);
console.log("\n");

console.log("FIELDS: ");
assertEqual(cur.getField(0,0),"10.55");
assertEqual(cur.getField(0,1),"10.556");
assertEqual(cur.getField(0,2),"10.5556");
console.log("\n");

console.log("nullS as Nulls: ");
cur.getNullsAsNulls();
assertEqual(cur.sendQuery("select null,1,null"),1);
assertEqual(cur.getField(0,0),null);
assertEqual(cur.getField(0,1),"1");
assertEqual(cur.getField(0,2),null);
cur.getNullsAsEmptyStrings();
assertEqual(cur.sendQuery("select null,1,null"),1);
assertEqual(cur.getField(0,0),"");
assertEqual(cur.getField(0,1),"1");
assertEqual(cur.getField(0,2),"");
cur.getNullsAsNulls();
console.log("\n");

console.log("RESULT SET BUFFER SIZE: ");
assertEqual(cur.getResultSetBufferSize(),0);
cur.setResultSetBufferSize(2);
assertEqual(cur.sendQuery("select * from testtable order by testtinyint"),1);
assertEqual(cur.getResultSetBufferSize(),2);
console.log();
assertEqual(cur.firstRowIndex(),0);
assertEqual(cur.endOfResultSet(),0);
assertEqual(cur.rowCount(),2);
assertEqual(cur.getField(0,0),"1");
assertEqual(cur.getField(1,0),"2");
assertEqual(cur.getField(2,0),"3");
console.log();
assertEqual(cur.firstRowIndex(),2);
assertEqual(cur.endOfResultSet(),0);
assertEqual(cur.rowCount(),4);
assertEqual(cur.getField(6,0),"7");
assertEqual(cur.getField(7,0),"8");
console.log();
assertEqual(cur.firstRowIndex(),6);
assertEqual(cur.endOfResultSet(),0);
assertEqual(cur.rowCount(),8);
assertEqual(cur.getField(8,0),null);
console.log();
assertEqual(cur.firstRowIndex(),8);
assertEqual(cur.endOfResultSet(),1);
assertEqual(cur.rowCount(),8);
console.log("\n");

console.log("DONT GET COLUMN INFO: ");
cur.dontGetColumnInfo();
assertEqual(cur.sendQuery("select * from testtable order by testtinyint"),1);
assertEqual(cur.getColumnName(0),null);
assertEqual(cur.getColumnLength(0),0);
assertEqual(cur.getColumnType(0),null);
console.log();
cur.getColumnInfo();
assertEqual(cur.sendQuery("select * from testtable order by testtinyint"),1);
assertEqual(cur.getColumnName(0),"testtinyint");
assertEqual(cur.getColumnLength(0),1);
assertEqual(cur.getColumnType(0),"TINYINT");
console.log("\n");

console.log("SUSPENDED SESSION: ");
assertEqual(cur.sendQuery("select * from testtable order by testtinyint"),1);
cur.suspendResultSet();
assertEqual(con.suspendSession(),1);
port=con.getConnectionPort();
socket=con.getConnectionSocket();
assertEqual(con.resumeSession(port,socket),1);
console.log();
assertEqual(cur.getField(0,0),"1");
assertEqual(cur.getField(1,0),"2");
assertEqual(cur.getField(2,0),"3");
assertEqual(cur.getField(3,0),"4");
assertEqual(cur.getField(4,0),"5");
assertEqual(cur.getField(5,0),"6");
assertEqual(cur.getField(6,0),"7");
assertEqual(cur.getField(7,0),"8");
console.log();
assertEqual(cur.sendQuery("select * from testtable order by testtinyint"),1);
cur.suspendResultSet();
assertEqual(con.suspendSession(),1);
port=con.getConnectionPort();
socket=con.getConnectionSocket();
assertEqual(con.resumeSession(port,socket),1);
console.log();
assertEqual(cur.getField(0,0),"1");
assertEqual(cur.getField(1,0),"2");
assertEqual(cur.getField(2,0),"3");
assertEqual(cur.getField(3,0),"4");
assertEqual(cur.getField(4,0),"5");
assertEqual(cur.getField(5,0),"6");
assertEqual(cur.getField(6,0),"7");
assertEqual(cur.getField(7,0),"8");
console.log();
assertEqual(cur.sendQuery("select * from testtable order by testtinyint"),1);
cur.suspendResultSet();
assertEqual(con.suspendSession(),1);
port=con.getConnectionPort();
socket=con.getConnectionSocket();
assertEqual(con.resumeSession(port,socket),1);
console.log();
assertEqual(cur.getField(0,0),"1");
assertEqual(cur.getField(1,0),"2");
assertEqual(cur.getField(2,0),"3");
assertEqual(cur.getField(3,0),"4");
assertEqual(cur.getField(4,0),"5");
assertEqual(cur.getField(5,0),"6");
assertEqual(cur.getField(6,0),"7");
assertEqual(cur.getField(7,0),"8");
console.log("\n");

console.log("SUSPENDED RESULT SET: ");
cur.setResultSetBufferSize(2);
assertEqual(cur.sendQuery("select * from testtable order by testtinyint"),1);
assertEqual(cur.getField(2,0),"3");
id=cur.getResultSetId();
cur.suspendResultSet();
assertEqual(con.suspendSession(),1);
port=con.getConnectionPort();
socket=con.getConnectionSocket();
assertEqual(con.resumeSession(port,socket),1);
assertEqual(cur.resumeResultSet(id),1);
console.log();
assertEqual(cur.firstRowIndex(),4);
assertEqual(cur.endOfResultSet(),0);
assertEqual(cur.rowCount(),6);
assertEqual(cur.getField(7,0),"8");
console.log();
assertEqual(cur.firstRowIndex(),6);
assertEqual(cur.endOfResultSet(),0);
assertEqual(cur.rowCount(),8);
assertEqual(cur.getField(8,0),null);
console.log();
assertEqual(cur.firstRowIndex(),8);
assertEqual(cur.endOfResultSet(),1);
assertEqual(cur.rowCount(),8);
cur.setResultSetBufferSize(0);
console.log("\n");

console.log("CACHED RESULT SET: ");
cur.cacheToFile("cachefile1");
cur.setCacheTtl(200);
assertEqual(cur.sendQuery("select * from testtable order by testtinyint"),1);
filename=cur.getCacheFileName();
assertEqual(filename,"cachefile1");
cur.cacheOff();
assertEqual(cur.openCachedResultSet(filename),1);
assertEqual(cur.getField(7,0),"8");
console.log("\n");

console.log("COLUMN COUNT FOR CACHED RESULT SET: ");
assertEqual(cur.colCount(),19);
console.log("\n");

console.log("COLUMN NAMES FOR CACHED RESULT SET: ");
assertEqual(cur.getColumnName(0),"testtinyint");
assertEqual(cur.getColumnName(1),"testsmallint");
assertEqual(cur.getColumnName(2),"testmediumint");
assertEqual(cur.getColumnName(3),"testint");
assertEqual(cur.getColumnName(4),"testbigint");
assertEqual(cur.getColumnName(5),"testfloat");
assertEqual(cur.getColumnName(6),"testreal");
assertEqual(cur.getColumnName(7),"testdecimal");
assertEqual(cur.getColumnName(8),"testdate");
assertEqual(cur.getColumnName(9),"testtime");
assertEqual(cur.getColumnName(10),"testdatetime");
assertEqual(cur.getColumnName(11),"testyear");
assertEqual(cur.getColumnName(12),"testchar");
assertEqual(cur.getColumnName(13),"testtext");
assertEqual(cur.getColumnName(14),"testvarchar");
assertEqual(cur.getColumnName(15),"testtinytext");
assertEqual(cur.getColumnName(16),"testmediumtext");
assertEqual(cur.getColumnName(17),"testlongtext");
cols=cur.getColumnNames();
assertEqual(cols[0],"testtinyint");
assertEqual(cols[1],"testsmallint");
assertEqual(cols[2],"testmediumint");
assertEqual(cols[3],"testint");
assertEqual(cols[4],"testbigint");
assertEqual(cols[5],"testfloat");
assertEqual(cols[6],"testreal");
assertEqual(cols[7],"testdecimal");
assertEqual(cols[8],"testdate");
assertEqual(cols[9],"testtime");
assertEqual(cols[10],"testdatetime");
assertEqual(cols[11],"testyear");
assertEqual(cols[12],"testchar");
assertEqual(cols[13],"testtext");
assertEqual(cols[14],"testvarchar");
assertEqual(cols[15],"testtinytext");
assertEqual(cols[16],"testmediumtext");
assertEqual(cols[17],"testlongtext");
console.log("\n");

console.log("CACHED RESULT SET WITH RESULT SET BUFFER SIZE: ");
cur.setResultSetBufferSize(2);
cur.cacheToFile("cachefile1");
cur.setCacheTtl(200);
assertEqual(cur.sendQuery("select * from testtable order by testtinyint"),1);
filename=cur.getCacheFileName();
assertEqual(filename,"cachefile1");
cur.cacheOff();
assertEqual(cur.openCachedResultSet(filename),1);
assertEqual(cur.getField(7,0),"8");
assertEqual(cur.getField(8,0),null);
cur.setResultSetBufferSize(0);
console.log("\n");

console.log("FROM ONE CACHE FILE TO ANOTHER: ");
cur.cacheToFile("cachefile2");
assertEqual(cur.openCachedResultSet("cachefile1"),1);
cur.cacheOff();
assertEqual(cur.openCachedResultSet("cachefile2"),1);
assertEqual(cur.getField(7,0),"8");
assertEqual(cur.getField(8,0),null);
console.log("\n");

console.log("FROM ONE CACHE FILE TO ANOTHER WITH RESULT SET BUFFER SIZE: ");
cur.setResultSetBufferSize(2);
cur.cacheToFile("cachefile2");
assertEqual(cur.openCachedResultSet("cachefile1"),1);
cur.cacheOff();
assertEqual(cur.openCachedResultSet("cachefile2"),1);
assertEqual(cur.getField(7,0),"8");
assertEqual(cur.getField(8,0),null);
cur.setResultSetBufferSize(0);
console.log("\n");

console.log("CACHED RESULT SET WITH SUSPEND AND RESULT SET BUFFER SIZE: ");
cur.setResultSetBufferSize(2);
cur.cacheToFile("cachefile1");
cur.setCacheTtl(200);
assertEqual(cur.sendQuery("select * from testtable order by testtinyint"),1);
assertEqual(cur.getField(2,0),"3");
filename=cur.getCacheFileName();
assertEqual(filename,"cachefile1");
id=cur.getResultSetId();
cur.suspendResultSet();
assertEqual(con.suspendSession(),1);
port=con.getConnectionPort();
socket=con.getConnectionSocket();
console.log();
assertEqual(con.resumeSession(port,socket),1);
assertEqual(cur.resumeCachedResultSet(id,filename),1);
console.log();
assertEqual(cur.firstRowIndex(),4);
assertEqual(cur.endOfResultSet(),0);
assertEqual(cur.rowCount(),6);
assertEqual(cur.getField(7,0),"8");
console.log();
assertEqual(cur.firstRowIndex(),6);
assertEqual(cur.endOfResultSet(),0);
assertEqual(cur.rowCount(),8);
assertEqual(cur.getField(8,0),null);
console.log();
assertEqual(cur.firstRowIndex(),8);
assertEqual(cur.endOfResultSet(),1);
assertEqual(cur.rowCount(),8);
cur.cacheOff();
console.log();
assertEqual(cur.openCachedResultSet(filename),1);
assertEqual(cur.getField(7,0),"8");
assertEqual(cur.getField(8,0),null);
cur.setResultSetBufferSize(0);
console.log("\n");

console.log("COMMIT AND ROLLBACK: ");
// Note: Mysql's default isolation level is repeatable-read,
// not read-committed like most other db's.  Both sessions must
// commit to see the changes that each other has made.
var	secondcon=new sqlrelay.SQLRConnection("sqlrelay",9000,"/tmp/test.socket","testuser","testpassword",0,1);
var	 secondcur=new sqlrelay.SQLRCursor(secondcon);
assertEqual(secondcur.sendQuery("select count(*) from testtable"),1);
if (majorversion>3) {
	assertEqual(secondcur.getField(0,0),"0");
} else {
	assertEqual(secondcur.getField(0,0),"8");
}
assertEqual(con.commit(),1);
assertEqual(secondcon.commit(),1);
assertEqual(secondcur.sendQuery("select count(*) from testtable"),1);
assertEqual(secondcur.getField(0,0),"8");
assertEqual(con.autoCommitOn(),1);
assertEqual(cur.sendQuery("insert into testtable values (10,10,10,10,10,10.1,10.1,1.1,'2010-01-01','10:00:00','2010-01-01 10:00:00','2010','char10','text10','varchar10','tinytext10','mediumtext10','longtext10',null)"),1);
assertEqual(secondcon.commit(),1);
assertEqual(secondcur.sendQuery("select count(*) from testtable"),1);
assertEqual(secondcur.getField(0,0),"9");
assertEqual(con.autoCommitOff(),1);
secondcon.commit();
console.log("\n");

console.log("FINISHED SUSPENDED SESSION: ");
assertEqual(cur.sendQuery("select * from testtable order by testint"),1);
assertEqual(cur.getField(4,0),"5");
assertEqual(cur.getField(5,0),"6");
assertEqual(cur.getField(6,0),"7");
assertEqual(cur.getField(7,0),"8");
id=cur.getResultSetId();
cur.suspendResultSet();
assertEqual(con.suspendSession(),1);
port=con.getConnectionPort();
socket=con.getConnectionSocket();
assertEqual(con.resumeSession(port,socket),1);
assertEqual(cur.resumeResultSet(id),1);
assertEqual(cur.getField(4,0),null);
assertEqual(cur.getField(5,0),null);
assertEqual(cur.getField(6,0),null);
assertEqual(cur.getField(7,0),null);
console.log("\n");

// drop existing table
cur.sendQuery("drop table testtable");

// invalid queries...
console.log("INVALID QUERIES: ");
assertEqual(cur.sendQuery("select * from testtable order by testtinyint"),0);
assertEqual(cur.sendQuery("select * from testtable order by testtinyint"),0);
assertEqual(cur.sendQuery("select * from testtable order by testtinyint"),0);
assertEqual(cur.sendQuery("select * from testtable order by testtinyint"),0);
console.log();
assertEqual(cur.sendQuery("insert into testtable values (1,2,3,4)"),0);
assertEqual(cur.sendQuery("insert into testtable values (1,2,3,4)"),0);
assertEqual(cur.sendQuery("insert into testtable values (1,2,3,4)"),0);
assertEqual(cur.sendQuery("insert into testtable values (1,2,3,4)"),0);
console.log();
assertEqual(cur.sendQuery("create table testtable"),0);
assertEqual(cur.sendQuery("create table testtable"),0);
assertEqual(cur.sendQuery("create table testtable"),0);
assertEqual(cur.sendQuery("create table testtable"),0);
console.log("\n");

reportTestStatus();

process.exit(getStatus());
